get10101/10101

docs/003-onchain-monitoring.adoc

docs: Add 003 onchain monitoring ADR

---

docs/004-solution-architecture.adoc

docs: Add 004 solution architecture ADR

---

docs/002-database.adoc

docs: Add 002 database ADR

---

mobile/lib/features/trade/trade_screen.dart
mobile/lib/features/trade/trade_theme.dart
mobile/lib/main.dart

resolves https://github.com/get10101/10101/issues/98
Using `ThemeExtension` was inspired by [this blogpost](https://lakshay-parnami.medium.com/flutter-3-themedata-finally-extendeddd-aa0069cc9996)

refactor: add trade theme

---

mobile/android/app/build.gradle
mobile/android/app/src/debug/AndroidManifest.xml
mobile/android/app/src/main/AndroidManifest.xml
mobile/android/app/src/main/kotlin/com/example/flutter_rust_bridge_template/MainActivity.kt
mobile/android/app/src/profile/AndroidManifest.xml
mobile/lib/main.dart

The first commit updates the manifest files so we are able to build and deploy.
The second commit changes the the strategy to remove the splashscreen - on my phone I keep running into an error when initializing the rust logging, resulting in the app being stuck on the splashscreen. 
Note that several sections of the old `Manifest` file were not actually needed - I tried to reduce what is needed to fix this to a minimum. If something looks like it slipped in unnecessarily nonetheless please point it out!
I also removed a whole section of the `build.gradle` file because we did not have that in the POC, and it does not seem to be needed to build and deploy - but maybe I'm missing something. @bonomat might know more :)

Fix/android build and running the application on Android phone

---

.github/workflows/ci.yml
.gitignore
README.md
justfile
mobile/lib/features/trade/application/trade_values_service.dart
mobile/lib/features/trade/domain/direction.dart
mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/order_change_notifier.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/trade/trade_bottom_sheet.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_screen.dart
mobile/lib/features/trade/trade_tabs.dart
mobile/lib/features/trade/trade_value_change_notifier.dart
mobile/lib/main.dart
mobile/lib/util/constants.dart
mobile/pubspec.lock
mobile/pubspec.yaml
mobile/test/trade_test.dart
mobile/test/widget_test.dart

This was already merged - but into the wrong branch 😅
See: https://github.com/get10101/10101/pull/150
@bonomat do we have to manually configure to automatically change the base if the underlying PR merges? We used to have that :D

Order test

---

mobile/lib/features/trade/domain/leverage.dart
mobile/lib/features/trade/domain/order.dart
mobile/lib/features/trade/order_list_item.dart
mobile/native/src/api_model/order.rs
mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/order/mod.rs

- Some beautifying
- Display the execution price if it is set

Display the order according to it's state

---

Cargo.lock
coordinator/Cargo.toml
coordinator/src/main.rs
coordinator/src/routes.rs

this is a preparation for adding the orderbook

chore: replace rocket with axum

---

crates/ln-dlc-node/src/node.rs

LDK will reject any final (incoming) HTLC if the available `final_cltv_expiry` smaller than 23. This is the reason why LDK has a `MIN_FINAL_CLTV_EXPIRY` constant set to 24. 20 was probably working, because of some buffers added by lnd or ldk. Not entirely sure about that. However, using the LDK defined constant for that seems to be the reasonable choice.

chore: Use constant for min final cltv expiry

---

mobile/macos/Podfile.lock
mobile/pubspec.lock

When I try to run the app for the first time, these changes appeared.

Bump flutter package versions

---

coordinator/src/cli.rs
maker/src/bin/maker.rs
maker/src/cli.rs
mobile/pubspec.lock

Adds the network cli flag to the maker bin.

feat: maker configurable network

---

coordinator/src/orderbook/routes.rs
crates/orderbook-client/examples/authenticated_api.rs
crates/orderbook-client/src/lib.rs
mobile/native/src/api.rs
mobile/native/src/lib.rs
mobile/native/src/orderbook.rs

chore: minor clean-ups

---

Cargo.lock
coordinator/src/node.rs
coordinator/src/routes.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/mod.rs
crates/trade/Cargo.toml
crates/trade/src/lib.rs
mobile/native/src/ln_dlc/accept.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs
mobile/native/src/orderbook.rs
mobile/native/src/trade/order/handler.rs

see also
- https://github.com/get10101/10101/issues/181#issuecomment-1458458216
- https://github.com/get10101/10101/issues/220#issuecomment-1458349496
This PR introduces closing a position using the rust-dlc implementation of a linear payout curve. I've created a ticket for the [inverse payout curve](https://github.com/get10101/10101/issues/250).
This PR also fixes an issue with starting the mobile app, which I had to fix here a795ec10c4891f4146413814a5a41706ef7f0e83 as I was blocked otherwise.
There are loads of todos left in the code, but for demo this should be good enough for merging. We can address the todos, in follow up PRs.

feat: Close position

---

coordinator/src/node.rs
crates/trade/src/cfd.rs
mobile/native/src/ln_dlc/accept.rs

Follow-up to https://github.com/get10101/10101/pull/228.

Improve upon close-position PR

---

coordinator/src/orderbook/routes.rs
coordinator/src/orderbook/trading.rs

chore: rename test

---

coordinator/src/orderbook/db/orders.rs
coordinator/src/orderbook/routes.rs
coordinator/src/orderbook/tests/sample_test.rs

mark orders as taken in db

---

README.md
justfile

Simply run `just wipe` to reset the dev environment.

Add capability to easily reset dev environment

---

.github/workflows/publish_docker.yml

missed this commit in https://github.com/get10101/10101/pull/267
🙈

chore: use custom github token

---

README.md
coordinator/src/routes.rs
crates/ln-dlc-node/examples/fund.rs
crates/ln-dlc-node/src/node/mod.rs
justfile

after chatting with @da-kami I have not implemented passing in the lightning invoice from the app, if we need to automate that stage, it can be added in a follow-up.

Automate dev setup

---

.gitignore
Cargo.lock
DEVELOPMENT.md
README.md
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/wallet/create_invoice_screen.dart
mobile/lib/features/wallet/share_invoice_screen.dart

My apologies for such a non-focussed PR, but this is all the small things I have spotted along the way when I was coming up to speed with the project.
I'd be happy to split it into separate PRs, but I'm not sure whether it's worth it.

Bunch of small fixes spotted whilst coming up to speed with the project

---

justfile

Start `coordinator` and `maker` after Electrum server is ready in `justfile`

---

mobile/lib/common/settings_screen.dart
mobile/lib/features/trade/settings_screen.dart

I found myself wondering if the environment variables are working as expected and quickly added some app info into the settings. 
Design could need some love but it's functional:

feat: show app info in settings

---

.github/workflows/ci.yml
coordinator/src/bin/coordinator.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/mod.rs
justfile
maker/src/bin/maker.rs
mobile/native/src/ln_dlc/mod.rs

The problem on our VM was that we could not listen on our public ip address from inside the container. Instead, we should listen on 0.0.0.0

chore: listen on broadcast address

---

mobile/lib/common/settings_screen.dart

Share the logs as file (Even though the logs are not useful yet)

feat: add a button to share logs

---

.github/workflows/ci.yml
crates/ln-dlc-node/src/ln/event_handler.rs
justfile

hence we need to fail the intercepted htlc backwards

fix: on restart a node is not registered anymore

---

mobile/lib/features/wallet/wallet_screen.dart

Add a refresh indicator so that we can update the wallet manually

---

mobile/native/src/api.rs
mobile/native/src/db/mod.rs

Ensure separate sqlite DB is used for different networks

---

mobile/macos/Runner/AppDelegate.swift

Fixes #315 
frb template already had a fix for iOS, but not for macOS:
https://github.com/fzyzcjy/flutter_rust_bridge/issues/1025

Fix rust_flutter_bridge not being a singleton issue

---

crates/ln-dlc-node/src/node/mod.rs

At least the ones that are spawned in the constructor. Otherwise they could keep running indefinitely unexpectedly in situations where we remake a `Node` e.g. in tests.

Stop all spawned tasks on `Node` drop

---

justfile
mobile/lib/common/settings_screen.dart

feat: Add commit and branch to app info

---

crates/ln-dlc-node/src/node/connection.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/multiple_payments.rs
crates/ln-dlc-node/src/tests/multi_hop_payment.rs
crates/ln-dlc-node/src/tests/onboard_from_lnd.rs
crates/ln-dlc-node/src/tests/single_hop_payment.rs
maker/src/routes.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs

I have some very small hope that these changes might fix our intermittent CI issues.

Improve LN connection handling

---

coordinator/src/lib.rs
coordinator/src/orderbook/routes.rs

An order with zero price does not make any sense and should be rejected.

feat: The orderbook rejects orders with zero price

---

maker/src/trading/mod.rs
mobile/native/src/trade/position/handler.rs

The second commit might have been the reason why we saw weird prices and quick P/L

Flip ask/bid once for all

---

coordinator/migrations/2023-04-12-184910_positions/down.sql
coordinator/migrations/2023-04-12-184910_positions/up.sql
coordinator/src/bin/coordinator.rs
coordinator/src/db/custom_types.rs
coordinator/src/db/mod.rs
coordinator/src/db/positions.rs
coordinator/src/lib.rs
coordinator/src/node.rs
coordinator/src/orderbook/mod.rs
coordinator/src/position/mod.rs
coordinator/src/position/models.rs
coordinator/src/schema.rs
crates/coordinator-commons/src/lib.rs
crates/trade/src/cfd.rs
mobile/native/migrations/2023-03-06-005404_orders/up.sql
mobile/native/migrations/2023-03-20-005447_positions/up.sql
mobile/native/src/api.rs
mobile/native/src/calculations/mod.rs
mobile/native/src/db/models.rs
mobile/native/src/schema.rs
mobile/native/src/trade/order/api.rs
mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/order/mod.rs
mobile/native/src/trade/position/api.rs
mobile/native/src/trade/position/handler.rs
mobile/native/src/trade/position/mod.rs

resolves #226
// edit: Executed one manual test run opening and closing a channel successfully.

feat: Add expiry and persistence to position

---

coordinator/src/node.rs

Settling a position must calculate the accept settlement amount from the viewpoint of the position at the time it was opened. The reversed order in terms of direction has to be flipped. Accordingly, we need to also flip the leverage as we would otherwise use the coordinators leverage.

fix: Accept settlement amount calculation

---

mobile/lib/features/trade/trade_screen.dart

- If there is no position / orders then show placeholder message
- If there is an order currently being filled then show an according message in position tab

Placeholders for empty position / orders tabs

---

mobile/lib/features/trade/position_list_item.dart

Button was unused so I removed it for now.

chore: remove dead button

---

mobile/lib/main.dart
mobile/native/src/db/mod.rs

Fixes #336.
Tested it at least once and it works™️.

Prevent order state from going back in time for app

---

coordinator/src/routes.rs
crates/ln-dlc-node/src/ln/config.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/node/ln_channel.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/ln-dlc-node/src/tests/multi_hop_payment.rs
crates/ln-dlc-node/src/tests/single_hop_payment.rs
maker/src/routes.rs
mobile/native/src/ln_dlc/mod.rs

resolves https://github.com/get10101/10101/issues/406

Extend coordinator HTP API

---

.github/workflows/create_release.yml

fix: ci was complaining abou thtis :)

---

.github/workflows/build-release-binaries.yml

feat: also release docker image on release

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4703189288.
I've bumped the versions in the manifest files in this commit: 9333ab2776e75db7b52c4b9180f10c1ce8ebf492.

Release version 1.0.3

---

.github/workflows/build-release-binaries.yml

fix: use github ref_name

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @1010Tom!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4704059463.
I've bumped the versions in the manifest files in this commit: a616219b0506ff53b8056ba79c7b85344f410c01.

Release version 1.0.4

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @1010Tom!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4715113448.
I've bumped the versions in the manifest files in this commit: adca29fa7ebf8faaf9a701242540f6f3d92a8db5.

Release version 1.0.5

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4721754512.
I've bumped the versions in the manifest files in this commit: cf28aec409ddbd2b2bb3b9b078ddf6db4ce02f4a.

Release version 1.0.6

---

crates/bdk-ldk/src/lib.rs

We want to be able to predict how much money we use for tx fee, hence, we set a upper limit of 20 sats

fix max sats/vbyte for predictability

---

coordinator/migrations/2023-04-17-185626_create_users/down.sql
coordinator/migrations/2023-04-17-185626_create_users/up.sql
coordinator/src/db/mod.rs
coordinator/src/db/user.rs
coordinator/src/orderbook/tests/mod.rs
coordinator/src/orderbook/tests/registration_test.rs
coordinator/src/orderbook/tests/sample_test.rs
coordinator/src/routes.rs
coordinator/src/schema.rs
crates/coordinator-commons/src/lib.rs
justfile
mobile/lib/features/welcome/welcome_screen.dart
mobile/lib/main.dart
mobile/lib/util/preferences.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/trade/order/api.rs
mobile/native/src/trade/order/mod.rs

Add welcome screen

---

coordinator/src/admin.rs
crates/ln-dlc-node/src/node/ln_channel.rs

this seems to be the correct function to use.
It works, i.e. you can sign, but I did not manage to log into amboss or lightningswap yet :)

fix: signing a message using our nodes key

---

coordinator/src/node.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/mod.rs
mobile/native/src/ln_dlc/node.rs

I noticed this when I was looking into #410.
Sorry about the last two patches effectively being fixups of the first one. I chose to leave it like this because rebasing was annoying.
I'm pretty sure it works, but I wasn't able to test it in full because of #438.

Some tweaks to our DLC message handling

---

mobile/native/src/db/mod.rs
mobile/native/src/db/models.rs
mobile/native/src/trade/order/handler.rs

Fixes https://github.com/get10101/10101/issues/438.
Fixes https://github.com/get10101/10101/issues/273.

Improve resilience of updates to app's `Order`

---

mobile/lib/common/value_data_row.dart
mobile/lib/features/trade/order_list_item.dart
mobile/lib/features/trade/position_change_notifier.dart
mobile/lib/features/trade/position_list_item.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_screen.dart
mobile/lib/main.dart
mobile/native/src/trade/position/handler.rs
mobile/test/trade_test.dart

Close position flow should show a close bottom sheet and success screen

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4734957868.
I've bumped the versions in the manifest files in this commit: 8121ae89b46dac6d6923e284e6ef0ba7b580c9ff.

Release version 1.0.7

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @1010Tom!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4736313748.
I've bumped the versions in the manifest files in this commit: b63dda911bbe49976e71a2b1f39754ec74d50058.

Release version 1.0.8

---

crates/ln-dlc-node/src/node/invoice.rs
mobile/lib/common/submission_status_dialog.dart
mobile/lib/common/value_data_row.dart
mobile/lib/features/wallet/application/wallet_service.dart
mobile/lib/features/wallet/create_invoice_screen.dart
mobile/lib/features/wallet/domain/lightning_invoice.dart
mobile/lib/features/wallet/send_payment_change_notifier.dart
mobile/lib/features/wallet/send_screen.dart
mobile/lib/features/wallet/wallet_screen.dart
mobile/lib/main.dart
mobile/native/src/api.rs

- Decode invoice
- Form validation
Note: we are not displaying the decoded values yet.
TODO:
---

Send screen overhaul

---

mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_value_change_notifier.dart

Make sure that the balance of the counterparty can fulfil the calculated counterparty margin.

Ensure that the counterparty is able to fulfil

---

mobile/lib/common/settings_screen.dart
mobile/macos/Flutter/GeneratedPluginRegistrant.swift
mobile/macos/Podfile.lock
mobile/native/src/api.rs
mobile/pubspec.lock
mobile/pubspec.yaml

feat: show build number and node id in settings

---

Cargo.lock
Cargo.toml
coordinator/src/bin/coordinator.rs
coordinator/src/node.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/connection.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/sub_channel_manager.rs
crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs

Resend pending messages

---

Cargo.lock
Cargo.toml

Fixes https://github.com/get10101/10101/issues/470.

Update `rust-dlc` to fix restart bug

---

Cargo.lock
Cargo.toml

Fixes https://github.com/get10101/10101/issues/476.
By updating to latest `rust-dlc`.

Fix attempted-to-subtract-with-overflow error on restart

---

mobile/lib/common/settings_screen.dart

Fixes #465.
The gif is from the native version, but you get the idea.
https://user-images.githubusercontent.com/9418575/233560940-efe2afb0-bb5d-463b-8690-9c2991328d27.mp4
I've also reversed the order so that the latest logs appear at the top, since they're more likely to be relevant.

Display scrollable and better-looking logs in-app

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4773518511.
I've bumped the versions in the manifest files in this commit: 1dd8c912d9460210e932d73fb5746cddb5d14654.

Release version 1.0.9

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4780824505.
I've bumped the versions in the manifest files in this commit: 6ae29aa8b78c22453f07ebc75251dd4b48be510d.

Release version 1.0.10

---

.github/workflows/build-release-binaries.yml

until we fix the cause of this, we disable this to not waste valuable CI minutes
Issue is documented in : https://github.com/get10101/10101/issues/496

chore: apks don't show up in the release

---

mobile/lib/common/settings_screen.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

Related to #410.
This is extremely dumb at the moment, but it worked nicely for testing as it allowed me to keep going without having to wipe any data.

Add LN close buttons to app's settings page

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4790140177.
I've bumped the versions in the manifest files in this commit: 19352f34ff68e5f019a1dcd7b85b119f02aeb6ef.

Release version 1.0.11

---

maker/src/routes.rs

Helpful to test locally using the maker binary

feat(maker): helper function to connect to peer

---

utils/auto_mine.sh

A simply script to automatically mine every 60 seconds a new block. I am using it for testing locally and thought it might be useful to others as well.

chore: add auto mining script

---

crates/ln-dlc-node/src/node/connection.rs

It is better to retry not too often as we might annoy poor nodes by retrying to often. Additionally, the retry mechanism should happen less often than the check on the outside.
It's an attempt to make our connection handling a bit smarter. 
I'm not sure it will change much though.

chore: exponentially retry

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4812635074.
I've bumped the versions in the manifest files in this commit: 7f0b41cc2fbbb903e6ecce440259c51c93daa013.

Release version 1.0.12

---

crates/ln-dlc-node/src/node/oracle_client.rs

Current setting - retry every 1s up to 10 times.
I created easy consts to adjust the settings if needed.
Tested by unplugging internet temporarily on desktop.

Retry connecting to the oracle a few times before bailing

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4834191836.
I've bumped the versions in the manifest files in this commit: b2e07acdd24bb23da3b531c1388bc1e082c5f48f.

Release version 1.0.13

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4854319961.
I've bumped the versions in the manifest files in this commit: ef50b1b865a3810c060ab1821869abd3ded770dc.

Release version 1.0.14

---

Cargo.lock
Cargo.toml

This update attempts to deal with losing connection between parties during
closing of the DLC.

Bump rust-dlc

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @klochowicz!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4876183576.
I've bumped the versions in the manifest files in this commit: a9433afe98dbe12912c3f37aa8459ce6b1c07c7c.

Release version 1.0.15

---

mobile/lib/common/app_bar_wrapper.dart
mobile/lib/common/color.dart
mobile/lib/features/trade/trade_theme.dart
mobile/lib/main.dart

See commit description for details.
new looks:

Improve our branding in the app

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @klochowicz!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4877542875.
I've bumped the versions in the manifest files in this commit: bdbf870e659570e481ce09912c2a2113daad4537.

Release version 1.0.16

---

.github/workflows/deliverables-push-main.yml
CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/4883269057.
I've bumped the versions in the manifest files in this commit: fdb3b84d336a97dd459de1cc326dcaf28b0cacb9.

Release version 1.0.17

---

crates/ln-dlc-node/src/node/mod.rs
maker/src/trading/mod.rs
maker/src/trading/orderbook_client.rs
mobile/native/src/commons/mod.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/trade/order/mod.rs
mobile/native/src/trade/order/orderbook_client.rs

Reqwest doesn't add request timeout by default.

Add timeout to all HTTP requests

---

.github/workflows/deliverables-push-main.yml

in most examples I could find the logic is like this. Let's see if this helps

fix: use unified boolean logic

---

Cargo.lock
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/examples/fund.rs
justfile

Add a new just command `just fund-regtest` (run from local machine).

Adapt fund binary to be able to fund public regtest instance

---

Cargo.lock
Cargo.toml

See https://github.com/p2pderivatives/rust-lightning/commit/5329979edb415c0dfa6c310677f2575ad6bd5f06.
I'm hoping that this will give us more context if we run into #610 or #627.

Update `rust-dlc` and `rust-lightning` to add some logs

---

.gitignore
Cargo.lock
coordinator/Cargo.toml
coordinator/src/bin/coordinator.rs
coordinator/src/cli.rs
coordinator/src/lib.rs
coordinator/src/node.rs
coordinator/src/routes.rs
coordinator/src/settings.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/ln-dlc-node/src/tests/onboard_from_lnd.rs

Control the coordinator via the API and persisted settings file.

Add configurable coordinator settings

---

crates/ln-dlc-node/src/node/channel_manager.rs

Fixes #627.
Fixes #610 (probably).
We removed this code snippet with 5921ccd57008b77df5e243c5c3da7229b4c41687 by mistake.

Instruct `ChainMonitor` to watch channels on restart

---

justfile

This allows us to ship the apk to selected users that are on Android.

Add commands to build and release apk for regtest

---

CONTRIBUTING.md
README.md

Based on our template from a previous project

chore: Add contributing guidelines

---

mobile/lib/features/trade/position_list_item.dart

resolves #519 
A small fix to ensure that the user cant close a position that has already expired.

fix: Disable close button if position is expired

---

crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs

In 6749e08fee6bf3e1eb73b20e96d106e674677b97 we changed the way of checking
invoice being claimed to the payer instead of payee.
This turned out to have a side effect of test failures due to timing issues.
Revert to checking at the payee side.

fix: Reduce the amount of intermittent test failures

---

crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/node/mod.rs

Hoping to stop running into Blockstream rate limits.

Sync on-chain wallet less frequently

---

.github/workflows/deliverables-push-main.yml

fix: maybe fixed?

---

.gitignore
coordinator/src/bin/coordinator.rs
coordinator/src/settings.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/mod.rs

- store settings file in the relevant data dir
- allow adjusting BDK settings

Improve settings

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/5030110963.
I've bumped the versions in the manifest files in this commit: f8ca30b68d9b90edb8cbf2b732fbd472e40272ef.

Release version 1.0.18

---

mobile/lib/features/wallet/wallet_change_notifier.dart
mobile/lib/features/wallet/wallet_screen.dart
mobile/lib/main.dart

Wallet sync indicator

---

coordinator/src/bin/coordinator.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/channel_manager.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/oracle_client.rs
crates/ln-dlc-node/src/tests/mod.rs
maker/src/bin/maker.rs
mobile/native/src/ln_dlc/mod.rs

This code was unnecessarily complex and calling `std::thread::spawn` from within an async tokio context is not recommended.

Remove unnecessary async

---

crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/connection.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/node/ln_channel.rs
crates/ln-dlc-node/src/node/sub_channel_manager.rs

Metrics are created to facilitate debugging

chore: Add more metrics inside ln-dlc-node

---

crates/ln-dlc-node/src/node/mod.rs

I am not sure if this fixes anything.

Remove `AtomicBool`s

---

mobile/native/src/db/mod.rs
mobile/native/src/trade/order/handler.rs

We cannot rely on only one order being open, because it can currently happen that the user triggers multiple orders. In order to not get stuck with an open order in the app we fail all open orders that are older than `5` minutes periodically.

Fail *all* outdated orders

---

coordinator/src/orderbook/routes.rs
coordinator/src/orderbook/trading.rs

See commit messages for details. Hopefully this will reduce our amount of blocks
note: the commits are unrelated, and could come in separate PRs if that's preferred.

Bunch of small fixes around potentially blocking operations

---

coordinator/src/orderbook/routes.rs
coordinator/src/routes.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs

According to tokio documentation, sync Mutex is preferred over
the tokio Mutex.

Avoid using tokio Mutex

---

crates/ln-dlc-node/src/node/mod.rs

We need this check to run and removing it didn't actually fix any other problems.

Re-introduce DLC periodic check

---

Cargo.lock
coordinator/Cargo.toml
coordinator/src/logger.rs
crates/coordinator-commons/Cargo.toml
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/fee_rate_estimator.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/trade/Cargo.toml
maker/Cargo.toml
maker/src/logger.rs
mobile/native/Cargo.toml
mobile/native/src/logger.rs

Use blocking esplora client

---

coordinator/src/bin/coordinator.rs
mobile/native/src/ln_dlc/mod.rs

Only spawn_blocking the blocking part.
An alternative solution for the recently submitted PR, where I spawned a
dedicated OS thread.

chore: Don't block whole thread for processing DLC messages

---

Cargo.lock
Cargo.toml

https://github.com/get10101/rust-dlc/tree/chore/add-logging-messages-for-debugging

chore: Add more log messages for debugging dlc message processing

---

coordinator/src/db/positions.rs
coordinator/src/db/trades.rs
coordinator/src/node.rs
coordinator/src/orderbook/routes.rs
coordinator/src/routes.rs

Annotate public functions in the coordinator in its various modules.

chore: Add more autometrics into coordinator code

---

Cargo.lock
Cargo.toml

See: https://github.com/get10101/rust-dlc/commit/a6fc2777d9b8cd1d0a8619c4ddbaad09e0756bee

chore: Add more logging into rust-dlc

---

.cargo/config.toml
crates/ln-dlc-node/src/node/payment_persister.rs
rust-toolchain.toml

Reverts get10101/10101#752.
See https://github.com/get10101/10101/pull/752#issuecomment-1583975622.

Revert "Build `rust-lightning` with `backtrace` flag"

---

Cargo.lock
Cargo.toml

See https://github.com/get10101/rust-lightning/commit/29703c9e.
We are very optimistic that this fixes https://github.com/get10101/10101/issues/692. But we have to test it using https://github.com/get10101/10101/pull/744.

Fix deadlock in `rust-lightning`

---

coordinator/src/logger.rs

This reverts commit c999267a1114a99f46cd83980e3482656aad589a.

Revert "chore: Increase log level of rust-lightning"

---

crates/ln-dlc-node/src/node/ln_channel.rs

As requested here: https://github.com/get10101/10101/pull/612#discussion_r1199331398.

Improve error message when trying to collab close LN with DLC channel

---

coordinator/src/admin.rs
crates/ln-dlc-node/src/node/ln_channel.rs

As requested here: https://github.com/get10101/10101/pull/612#discussion_r1199325151.

Simplify deserialisation of channel ID

---

mobile/lib/features/trade/trade_screen.dart

A proper fix should be implemented with https://github.com/get10101/10101/issues/714
resolves #777

chore: Remove share on twitter button temporarily

---

maker/src/bin/maker.rs

The maker currently only creates orders. Letting it do anything else for the time being does not make sense.

Simplify maker binary

---

crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/dlc/non_collaborative_settlement.rs

The `SubChannelManager::periodic_check` already calls it!

Do not trigger DLC manager periodic check twice

---

Cargo.toml

See https://github.com/get10101/rust-dlc/commit/4e85d15.

Fix error-prone periodic checks in `rust-dlc`

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/5290787778.
I've bumped the versions in the manifest files in this commit: 6555f6fe173f7e5567892b69b4986792a66769b5.

Release version 1.0.20

---

.github/workflows/add-new-issues-to-board.yml

Same should be done in other repositories

Preparation for Q3: Add new issues to new board

---

README.md

We depend on Docker and docker-compose for running the dev setup.

docs: Mention Docker dependency

---

crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/node/mod.rs

Motivated by looking into #807.

Improve on-chain sync logs

---

mobile/lib/common/amount_text.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/wallet/create_invoice_screen.dart

Format sats in create invoice screen

---

coordinator/src/admin.rs
coordinator/src/db/user.rs

This will simplify looking at the channel details and knowing which channel belongs to which user. 
Looks like this: 
```
{
"channel_id": "ee6c346c1d397cd938fcae21d17259961bed965afab20a211b29c073db68ac59",
"counterparty": "03684a930aa72bbe1201f13378d610d1e0da5f9926e92dda1121a2f8ce81f8c126",
"funding_txo": "58ac68db73c0291b210ab2fa5a96ed1b965972d121aefc38d97c391d6c346cee:1",
"channel_type": "StaticRemoteKey: required, AnchorsZeroFeeHtlcTx: not supported, SCIDPrivacy: not supported, ZeroConf: not supported, unknown flags: none",
"channel_value_satoshis": 200000,
"unspendable_punishment_reserve": 2000,
"user_channel_id": 0,
"balance_msat": 100000000,
"outbound_capacity_msat": 98000000,
"next_outbound_htlc_limit_msat": 98000000,
"inbound_capacity_msat": 98000000,
"confirmations_required": 0, …
```

User email in channel details

---

README.md
coordinator/src/routes.rs
crates/ln-dlc-node/examples/fund.rs
justfile
mobile/lib/features/wallet/share_invoice_screen.dart

See commit messages for details

QoL dev improvements

---

mobile/lib/common/settings_screen.dart
mobile/lib/main.dart

We need this to actually fix https://github.com/get10101/10101/issues/799.

Show TRACE logs on the phone

---

coordinator/src/node.rs

Fixes #537
It is more likely that the proposing a dlc will fail. e.g. the oracle is not reachable, the peer lost connection. Hence, it's better to firstly try to propose the dlc and only when this is successful persist the position and trade to the database.
Our current integration test framework does not allow me to easily write a regression test for that. Waiting for the e2e test setup being introduced with https://github.com/get10101/10101/pull/841.
However I verified the fix by running the following manual test.
1. Startup coordinator with an incorrect oracle endpoint
2. Open a position with the app - this order will fail.
3. Check if a position has been created (note, prior to this fix a position would have been created as the propose dlc comes after persisting the position) - No …

fix: Persist position and trade after dlc has been proposed

---

Cargo.lock
crates/tests-e2e/Cargo.toml
crates/tests-e2e/src/app.rs
crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/src/http.rs
crates/tests-e2e/src/lib.rs
crates/tests-e2e/src/test_flow.rs
crates/tests-e2e/src/test_subscriber.rs
crates/tests-e2e/tests/basic.rs
crates/tests-e2e/tests/close_position.rs
crates/tests-e2e/tests/open_position.rs
mobile/native/src/ln_dlc/mod.rs

Test opening and closing a position.
Make the framework more ergonomic and solve some issues.

Expand end-to-end tests - add happy path

---

Cargo.lock
crates/tests-e2e/Cargo.toml
justfile
mobile/ios/Podfile.lock
mobile/macos/Podfile.lock
mobile/native/Cargo.toml
mobile/pubspec.lock
mobile/pubspec.yaml

Note: only the required packages got bumped, not all dependencies.
See:
https://dart.dev/resources/dart-3-migration#null-safety-migration-tools
I have tested both the macOS and iOS versions for opening / closing a position.

chore(mobile): Upgrade flutter packages to support sound null safety

---

.github/workflows/ci.yml

It should become faster to bootstrap Flutter env with it.

chore(ci): Enable cache on flutter-action

---

coordinator/src/admin.rs
coordinator/src/routes.rs

feat: add admin api to open channel to other nodes

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/5437102180.
I've bumped the versions in the manifest files in this commit: 69abd48f13eccb9f13361c24834b670f8ab61044.

Release version 1.0.21

---

CHANGELOG.md

I thought this could be handy in the changelog file :)

Update changelog for prometheus metrics

---

mobile/lib/features/trade/trade_screen.dart

Addresses #871 but does not calculate the realized P/L from the channel as per #895 (see Daniel's comment on #871).

Change "Unrealized P/L" to "P/L" when order closes position and is filled

---

mobile/lib/main.dart

Log app settings on startup

---

mobile/lib/features/wallet/share_invoice_screen.dart

Previous text was a bit repetitive and ungrammatical

Tweak 'understanding fees' text

---

coordinator/src/db/payments.rs
coordinator/src/db/positions.rs
coordinator/src/position/models.rs
crates/trade/src/bitmex_client.rs
crates/trade/src/lib.rs
mobile/native/src/calculations/mod.rs
mobile/native/src/db/models.rs

A `Quote` is basically a more detailed `Price`; the `Quote` uses the `Price`'s `get_price_for_direction` logic to get the price by direction.
---
@luckysori  comments from https://github.com/get10101/10101/pull/967 should all be worked in

Some cleanup and alignment

---

justfile

This uses a combination of answers in https://stackoverflow.com/a/25851186 and https://stackoverflow.com/a/49552792.
Fixes #989 (for me). @da-kami, can you confirm that this still works on OS X?

Replace `run-local-android` recipe's LOCAL_IP variable

---

mobile/lib/common/app_bar_wrapper.dart

Somehow that got lost in some of the last changes.

chore: Align settings icon

---

mobile/lib/features/trade/application/candlestick_service.dart

This seems like a very simple approach. Fixes #713

Convert candlestick chart to local time

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/5678506885.
I've bumped the versions in the manifest files in this commit: ccee8d6ddb7aafe6e94e918d5ab34f2ced34b815.

Release version 1.1.0

---

README.md

I always find myself struggling to remember the exact commands and links so I decided to just collate them here

Add some useful info for local debugging

---

.github/workflows/draft_new_release.yml

Verified in own fork: https://github.com/bonomat/10101/actions/runs/5761913231/job/15620690683

fix: install rust nightly and dprint

---

crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs
crates/tests-e2e/tests/open_position.rs

Resolves https://github.com/get10101/10101/issues/874
This test runs now on my machine.
I kept https://github.com/get10101/10101/pull/1064/commits/d3b53e3d762fd87f1de9dedae6974ba0bfde7359 separate for @holzeis to see.

test: Reproduce force-closure with reversed order

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/5762281370.
I've bumped the versions in the manifest files in this commit: 0533ac91c7c17614dd447fbfb1c33f63792988e6.
closes https://github.com/get10101/10101/milestone/3

Release version 1.2.0

---

.github/workflows/ci.yml

Improve names of CI actions

---

.github/workflows/build-release-binaries.yml
.github/workflows/deliverables-push-main.yml
.github/workflows/ios-fastlane.yml

deriving it from the input did not work as the env file was not set correctly
Follow-up from https://github.com/get10101/10101/pull/1088

fix: app_scheme needs to be mentioned

---

Cargo.lock
crates/bitmex-client/Cargo.toml
crates/bitmex-client/examples/example.rs
crates/bitmex-client/src/client.rs
crates/bitmex-client/src/lib.rs
crates/bitmex-client/src/models.rs

this will enable us to post orders to bitmex and retrieve the current position.
resolves [#974](https://github.com/get10101/10101/issues/974)

feat: add bitmex client

---

mobile/ios/Runner.xcodeproj/project.pbxproj

The resulting build crashes on the phone.
CC @klochowicz

fix: parallel build seems to break release

---

justfile
mobile/ios/Podfile.lock
mobile/lib/common/feedback.dart
mobile/lib/common/settings_screen.dart
mobile/lib/main.dart
mobile/macos/Flutter/GeneratedPluginRegistrant.swift
mobile/pubspec.lock
mobile/pubspec.yaml

Add feedback button into Settings screen

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/5928295982.
I've bumped the versions in the manifest files in this commit: 8d79bbe753e66921837d836b8ad6ff28142e9019.

Release version 1.2.1

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/5936906571.
I've bumped the versions in the manifest files in this commit: 81664ae29ee2f2799cb150e04c04d8ab1b7b193a.

Release version 1.2.2

---

mobile/native/src/db/mod.rs

Fixes this TODO in the codebase. I just happened to read this

refactor: collect into Result<Vec> instead of for loop

---

CHANGELOG.md
mobile/lib/common/fiat_input_form_field.dart
mobile/lib/common/value_data_row.dart
mobile/lib/features/stable/bitcoinize_confirmation_sheet.dart
mobile/lib/features/stable/stable_confirmation_sheet.dart
mobile/lib/features/stable/stable_dialog.dart
mobile/lib/features/stable/stable_screen.dart
mobile/lib/features/stable/stable_submission_status_dialog.dart
mobile/lib/features/stable/stable_value_change_notifier.dart
mobile/lib/features/trade/domain/position.dart
mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/position_change_notifier.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_value_change_notifier.dart
mobile/lib/main.dart
mobile/lib/util/constants.dart
mobile/native/src/ln_dlc/node.rs

resolves #1130
resolves #1132 
resolves #1133
fixes  #1145 
https://github.com/get10101/10101/assets/382048/effb7953-441c-49bb-9c82-6b1629927bc1

feat(stable): add stable screen

---

.github/workflows/build-release-binaries.yml
.github/workflows/ci.yml
.github/workflows/ios-fastlane.yml
.github/workflows/ios.yml

it looks like the wrong version is being used. Also adding cache which should speed up ci speed slightly.
Verified in own fork: https://github.com/bonomat/10101/actions/runs/5962763768/job/16174600731
Resolves https://github.com/get10101/10101/issues/1129

fix: ensure fix flutter version in ci

---

CHANGELOG.md
coordinator/src/node.rs
coordinator/src/rollover.rs
coordinator/src/routes.rs
coordinator/src/settings.rs
crates/coordinator-commons/src/lib.rs
crates/ln-dlc-node/src/config.rs
crates/ln-dlc-node/src/lib.rs
mobile/ios/Podfile.lock
mobile/ios/Runner/Info.plist
mobile/lib/common/application/channel_info_service.dart
mobile/lib/features/stable/stable_confirmation_sheet.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/wallet/create_invoice_screen.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs
mobile/test/trade_test.dart

While we can't update existing contracts, we can at least change the settings when needed for new contracts.
Resolves https://github.com/get10101/10101/issues/1159
Resolves #628

feat: make contract fee rate configurable

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/5999628547.
I've bumped the versions in the manifest files in this commit: 46cc25252e47a778dc53c634a215a8f7904c36d4.

Release version 1.2.3

---

crates/ln-dlc-node/src/node/wallet.rs

Remove log about pending on-chain balance

---

Cargo.lock
Cargo.toml

See https://github.com/lightningdevkit/rust-lightning/commit/3b69cecf.
---
Related to https://github.com/get10101/10101/issues/1187.

Increase `rust-lightning` PING_TIMER to 20 seconds

---

mobile/native/src/channel_fee.rs

It could happen that the channel already shows outbound capacity due to the received payment, but the channel updates are not completely finished yet. We suspect that this could lead to issues when trying to pay the JIT channel opening fees at the same time. Resulting in force closures or worst case and unresponsive app (deadlock?).
By waiting additional 500 milliseconds after the outbound capacity is set, we hopefully prevent paying an invoice while the channel is still updated.

fix: Add buffer delay after outbound capacity is ready

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6033504041.
I've bumped the versions in the manifest files in this commit: 6d3339afe21970be5514ae0ed331aa74ab22895f.

Release version 1.2.4

---

coordinator/Cargo.toml
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/node/mod.rs
mobile/lib/features/wallet/create_invoice_screen.dart
mobile/lib/main.dart
mobile/native/Cargo.toml

This stuff came up when investigating #1187.

Random patches

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CONTRIBUTING.md

Add issue templates to make it easier for potential contributors and users to report bugs / request features.

Add issue templates

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6093528088.
I've bumped the versions in the manifest files in this commit: 46ab45acc4b1c2e946d87287ef468ffe169c8695.

Release version 1.2.5

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6097689713.
I've bumped the versions in the manifest files in this commit: ef6ea778536e71180d5cb8536dfec3ae43e40e5b.

Release version 1.2.6

---

mobile/native/src/channel_fee.rs

it looks like we sometimes have a timing issue when fetching a tx because the publishment was not yet finalized, with this we simply retry after one second
resolves https://github.com/get10101/10101/issues/1205

chore: make fetching tx fee more resilliant

---

justfile

the old command does not return anything for me

fix: get local ip on mac

---

mobile/lib/features/trade/domain/direction.dart
mobile/lib/features/trade/position_list_item.dart

Hello 10101, 
I added some labels for the position orders cards

Add Positions Details for Orders

---

mobile/lib/features/wallet/share_invoice_screen.dart

fix: GoError: There is nothing to pop when paying with faucet

---

mobile/lib/features/trade/application/candlestick_service.dart
mobile/lib/features/trade/candlestick_change_notifier.dart
mobile/lib/main.dart
mobile/test/trade_test.dart

Mainnet looks better than the testnet version which comes handy when doing demo videos or screenshots.
I keep changing this manually when I need quickly some screenshots so I thought I'd just change this permanently. 
Downside: the price will now be different to what the chart shows.

chore: mainnet candle stick chart

---

mobile/native/src/ln_dlc/mod.rs

I'm not sure if this is considered as enough. Thoughts?

Wait for 3 confirmations to show on-chain payments as successful

---

mobile/android/fastlane/Fastfile

fixes https://github.com/get10101/10101/issues/1309
Tested locally successfully

fix: allow uploading to google playstore again

---

coordinator/src/bin/coordinator.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
maker/src/bin/maker.rs
mobile/lib/main.dart
mobile/native/src/ln_dlc/mod.rs

Ensure app wallet balance and history appear ready ASAP

---

.github/workflows/android-fastlane.yml
.github/workflows/build-release-binaries.yml
.github/workflows/ci.yml
.github/workflows/ios-fastlane.yml
mobile/ios/Runner.xcodeproj/project.pbxproj
mobile/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
mobile/lib/features/wallet/wallet_screen.dart
mobile/pubspec.lock
mobile/pubspec.yaml

After more people on the team started bumping into this issue, @luckysori and myself agreed that the best way forward would be to just bump flutter version, as it looks like they've fixed a bug that we were depending on 😅
it is recommended to update it locally to the latest version.
I've tested it locally and it seemed to work.

Bump flutter to 3.13.4

---

maker/src/bin/maker.rs
maker/src/position.rs
maker/src/position/tentenone.rs
maker/src/routes.rs

Get maker position information via HTTP API

---

Cargo.lock
maker/src/bin/maker.rs
maker/src/orderbook_ws.rs
maker/src/trading/mod.rs

- reconnect price feed stream if it closes
- don't crash upon start if the orderbook stream is unavailable
- convey status of orderbook stream into maker health status

Make maker more resilient against stream closures

---

coordinator/src/node/rollover.rs

We need to use the current time instead of the expiry time, as we would otherwise rollover everytime.

fix: Do not rollover already rolled over positions

---

coordinator/src/node.rs

We ended up in several instances with a pending match if for any other reason than the ones covered the trade failed.
The trade result is now handled at a single point for every err and ok scenario.

fix: Update order and match in all trade scenarios

---

coordinator/src/orderbook/db/orders.rs
coordinator/src/orderbook/routes.rs
coordinator/src/orderbook/tests/sample_test.rs
coordinator/src/orderbook/websocket.rs

fix: filter failed orders in getAllOrders message

---

mobile/ios/config/default/GoogleService-Info.plist
mobile/ios/config/default/firebase_app_id_file.json

In default mode we use production firebase setup as it is the default runner in XCode

fix: if no flavor is defined, default will be used

---

CHANGELOG.md
mobile/lib/common/recover_dlc_change_notifier.dart
mobile/lib/common/task_status_dialog.dart

feat: Add close button to dialog if it remains in pending for more than 30 seconds

---

mobile/native/src/ln_dlc/mod.rs

We've talked about removing the hacky logic of using the order index to derive the trades for a while.
This proposal can be relatively easily extended to support position resizing.
We still assume that filled orders are fetched in the correct order, and that all orders have the same contract symbol.

Enrich logic to derive wallet history trades based on filled orders

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6323461675.
I've bumped the versions in the manifest files in this commit: a8667f8fa5736018c713d673f11ad5011a4c9453.

Release version 1.3.0

---

mobile/lib/features/trade/position_list_item.dart

Resolves https://github.com/get10101/10101/issues/1319

chore: always show close button

---

mobile/android/fastlane/Fastfile

Otherwise releases are immediately available for all our users

fix: release to internal first

---

Cargo.lock
Cargo.toml
coordinator/src/routes.rs
coordinator/src/settings.rs
crates/ln-dlc-node/src/ln/common_handlers.rs
crates/ln-dlc-node/src/ln/coordinator_event_handler.rs
crates/ln-dlc-node/src/ln/manage_spendable_outputs.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/wallet.rs
crates/ln-dlc-node/src/shadow.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/payments.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/tests-e2e/examples/fund.rs
crates/tests-e2e/src/bitcoind.rs
crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/src/setup.rs
crates/tests-e2e/tests/basic.rs
crates/tests-e2e/tests/maker.rs
justfile
mobile/lib/features/trade/order_change_notifier.dart
mobile/lib/features/trade/position_list_item.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/wallet/wallet_change_notifier.dart

- address and remove simple TODOs
- refactor tests and `just fund` to use the same Bitcoind wrapper

Small fixes

---

crates/ln-dlc-node/src/ln/event_handler.rs
crates/orderbook-commons/src/lib.rs
mobile/native/src/db/mod.rs
mobile/native/src/ln_dlc/channel_status.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/orderbook.rs

Reduce some log spam

---

mobile/lib/features/wallet/balance_row.dart
mobile/lib/features/wallet/create_invoice_screen.dart
mobile/lib/features/wallet/create_on_chain_payment_request.dart
mobile/lib/features/wallet/domain/share_invoice.dart
mobile/lib/features/wallet/share_invoice_screen.dart
mobile/lib/main.dart

Share on-chain payment requests

---

justfile
mobile/android/fastlane/Fastfile

Otherwise we have to manually "promote" each release for our regtest testers.

fix: release differently for regtest and mainnet

---

mobile/native/src/ln_dlc/mod.rs

Fixes #1379.
By rounding the order quantities (contracts) to 2 decimal places it is _much less likely_ that opening and closing trades do not match.
A mismatch can break the trades in the wallet and trade history view, because a closing trade can  end up being ignored as an unsupported (extending, reducing, direction-changing) trade. This error can compound, as the error is carried forward an all subsequent trades will almost certainly be missing too.
Once we add support for all other forms of trading, this error can mostly go away as all cases will be handled.

Ensure match between opening and closing trades in app trade history

---

.github/workflows/ios-fastlane.yml
.github/workflows/ios.yml
check_compatibility.sh
justfile
mobile/ios/Podfile.lock
mobile/macos/Podfile.lock
mobile/macos/Runner.xcodeproj/project.pbxproj
mobile/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme

- catch firebase exception if cannot fetch fcm_token
- fix build errors in XCode 15

Upgrade to XCode 15

---

CHANGELOG.md
mobile/lib/features/wallet/onboarding/fund_wallet_modal.dart
mobile/lib/features/wallet/payment_claimed_change_notifier.dart
mobile/lib/features/wallet/share_invoice_screen.dart
mobile/lib/main.dart
mobile/native/src/event/api.rs

I did not wasted time on showing some kind of success dialog. I still think we should show something, but I guess this is something to do by somebody with a better eye for design than me :)
resolves #180

chore: Return to wallet dashboard on claimed payment

---

coordinator/src/bin/coordinator.rs
coordinator/src/db/positions.rs
coordinator/src/db/positions_helper.rs
coordinator/src/scheduler.rs
coordinator/src/settings.rs

chore: Notify only users that haven't rolled over yet

---

coordinator/src/node.rs

This is a simple quick fix to fix the max amounts of payouts to 100. This means, the higher the trader amount is, the higher the steps are. We should go for a proper discretized curve to fox this.
quick fix for https://github.com/get10101/10101/issues/1427

fix: reduce amount of CETs to be generated

---

coordinator/src/node.rs
crates/coordinator-commons/src/lib.rs

I guess this feedback was lost in the PR review

fix: serialize dates nicely

---

mobile/native/src/orderbook.rs

Fixes #1433.
The code was organised in such a way that if we failed to establish a connection with the orderbook's WS API we would `continue` and retry immediately. This was producing a ridiculous number of log messages as well as busy waiting.

Use app's orderbook WS reconnect timeout in all cases

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6431729035.
I've bumped the versions in the manifest files in this commit: 1886ba1ab14a4f33786a531dbfdf9e3c82764d92.

Release version 1.4.0

---

coordinator/migrations/2023-10-04-222654_add_liquidity_request_logs_table/down.sql
coordinator/migrations/2023-10-04-222654_add_liquidity_request_logs_table/up.sql
coordinator/src/db/liquidity.rs
coordinator/src/db/mod.rs
coordinator/src/lib.rs
coordinator/src/routes.rs
coordinator/src/schema.rs
coordinator/src/settings.rs
crates/coordinator-commons/src/lib.rs
mobile/lib/features/wallet/application/wallet_service.dart
mobile/lib/features/wallet/onboarding/liquidity_card.dart
mobile/native/src/ln_dlc/mod.rs

- Display alert dialog if there's no liquidity
- Log all the liquidity requests
- Define an arbitrary on-chain liquidity threshold of 0.1 BTC on the coordinator side.
extracted from https://github.com/get10101/10101/pull/1425
🚨 this is a breaking change, requiring a simultaneous rollout of coordinator and the app; otherwise app cannot be funded.
video:
https://github.com/get10101/10101/assets/8319440/1146ec1f-97d1-4f34-b04f-1a3109b3cb31
DB extract proving that we log all requests. The last one is after the `just fund` step, so it worked:
| id | trader\_pk | timestamp | requested\_amount\_sats | liquidity\_option | successfully\_requested |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 1 | 022ad1e55852aaa3badbc76950af2d8ba3878c62170db5047743cf00b8af4e8ca3 | 2023-10-05 05:34:17.984924 …

feat(coordinator): Restrict in-bound liquidity

---

Cargo.lock
justfile

Upgrade in XCode changed the application directory.

fix(justfile): Delete app data with just wipe-app on new XCode 

---

.github/workflows/draft_new_release.yml

See here: https://github.com/get10101/10101/actions/runs/6455126850/job/17522047620#step:11:16

fix: this file is not being changed

---

mobile/lib/common/service_status_notifier.dart

Those log message bloat our app logs and aren't really useful.
```
flutter: 2023-10-07 08:58:14.222  LogLevel.DEBUG  New message from orderbook msg: NewOrder
flutter: 2023-10-07 08:58:14.769  LogLevel.DEBUG  Getting all non-pending channels
flutter: 2023-10-07 08:58:15.382  LogLevel.TRACE  Successfully synced payment history
flutter: 2023-10-07 08:58:15.716  LogLevel.TRACE  Received event: Event.serviceHealthUpdate(field0: Instance of 'ServiceUpdate')
flutter: 2023-10-07 08:58:15.786  LogLevel.TRACE  lightning_background_processor: Calling PeerManager's timer_tick_occurred
flutter: 2023-10-07 08:58:15.787  LogLevel.TRACE  lightning_background_processor: Persisting scorer
flutter: 2023-10-07 08:58:17.722  LogLevel.TRACE  Received event: Event.serviceHealthUpdate(field0: Instance of …
```

chore: Remove received event log message

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6455389455.
I've bumped the versions in the manifest files in this commit: 819d1d3aa4dea2ebd77054af7ff9b6e09572c88d.

Release version 1.4.1

---

CHANGELOG.md
Cargo.lock
mobile/lib/common/amount_text_field.dart
mobile/lib/common/amount_text_input_form_field.dart
mobile/lib/common/domain/model.dart
mobile/lib/features/stable/bitcoinize_confirmation_sheet.dart
mobile/lib/features/stable/stable_confirmation_sheet.dart
mobile/lib/features/stable/stable_dialog.dart
mobile/lib/features/stable/stable_screen.dart
mobile/lib/features/stable/stable_value_change_notifier.dart
mobile/lib/features/trade/application/order_service.dart
mobile/lib/features/trade/application/position_service.dart
mobile/lib/features/trade/application/trade_values_service.dart
mobile/lib/features/trade/domain/order.dart
mobile/lib/features/trade/domain/position.dart
mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/order_list_item.dart
mobile/lib/features/trade/position_change_notifier.dart
mobile/lib/features/trade/position_list_item.dart
mobile/lib/features/trade/trade_bottom_sheet.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_value_change_notifier.dart
mobile/lib/features/wallet/create_invoice_screen.dart
mobile/lib/features/wallet/create_on_chain_payment_request.dart
mobile/lib/features/wallet/onboarding/onboarding_screen.dart
mobile/test/trade_test.dart

- Sets the new default amount to 10 dollars
- Margin can not be edited anymore, only contracts
- Margin is updated when price changes
- Contracts can only be entered in full amounts
This will also fix a well known old exception that was always thrown when either value (margin, quantity) was changed on the trade screen.
https://github.com/get10101/10101/assets/382048/48960ddd-e9e0-4604-beb4-ce657a2ff060
fixes #1408 
fixes #1409

feat: Enter contracts in full amounts

---

Cargo.lock
coordinator/src/metrics.rs

cc @holzeis you love this one :)
Signed-off-by: Philipp Hoenisch <philipp@coblox.tech>

feat: new metric for counting dlc channels

---

.github/workflows/ci.yml
crates/tests-e2e/src/fund.rs
crates/tests-e2e/tests/rollover_position.rs

fix: fail e2e tests if there was an error

---

crates/tests-e2e/examples/fund.rs

This is not a fix, but for me this significantly improves the chances of the funding script to succeed.
related to https://github.com/get10101/10101/issues/1390

chore: Create maker channel last

---

mobile/lib/features/wallet/receive_screen.dart
mobile/lib/features/wallet/send/enter_destination_modal.dart

Added additional improvements to make the view nice for smaller displays.

fix: Push modal up when keyboard is shown

---

coordinator/src/collaborative_revert.rs

This to help to debug https://github.com/get10101/10101/issues/1500

chore: log all values to calc revert values

---

coordinator/src/collaborative_revert.rs
coordinator/src/db/positions.rs
coordinator/src/position/models.rs

Signed-off-by: Philipp Hoenisch <philipp@coblox.tech>
resolves https://github.com/get10101/10101/issues/1500

fix overflow bug due to wrong position loading from db

---

mobile/android/app/src/local/google-services.json

fix: fix android local config

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6562608225.
I've bumped the versions in the manifest files in this commit: 70ab2cfd63d9d2decdea0f9564bbc17ffcc70807.

Release version 1.4.2

---

CHANGELOG.md
mobile/lib/common/app_bar_wrapper.dart
mobile/lib/features/stable/stable_screen.dart
mobile/lib/features/trade/order_list_item.dart
mobile/lib/features/wallet/balance.dart
mobile/lib/features/wallet/balance_row.dart
mobile/lib/features/wallet/wallet_history_item.dart
mobile/lib/features/wallet/wallet_screen.dart

- Total is now also adding the USDT balance in sats (amount with unrealized pnl). mid term idea is that you can choose the currency you like to see your total balance in.
- I removed the animation showing the send and receive buttons on the balance. It just didn't fit anymore. I can revert that and try to make it look nicer if somebody objects.

feat: Improve balance design

---

mobile/lib/features/trade/order_list_item.dart
mobile/lib/features/trade/trade_screen.dart
mobile/lib/features/wallet/wallet_history_item.dart
mobile/lib/features/wallet/wallet_screen.dart

chore: Group list in single card

---

crates/ln-dlc-node/src/tests/just_in_time_channel/payments.rs

Resolves https://github.com/get10101/10101/issues/1524

fix: ensure channel updates are propagated before doing payments

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6676368104.
I've bumped the versions in the manifest files in this commit: b2376b3a12606846abb2f080a448ff7ecc2d4187.

Release version 1.4.4

---

mobile/lib/features/wallet/send/send_screen.dart

Just for you @holzeis 😘
https://github.com/get10101/10101/assets/224613/285f6c37-083e-4b98-bd30-4bfbf18fafca

fix: only show for on-chain

---

Cargo.lock
Cargo.toml
coordinator/Cargo.toml
coordinator/src/lib.rs
coordinator/src/node.rs
coordinator/src/payout_curve.rs
crates/payout_curve/.gitignore
crates/payout_curve/Cargo.toml
crates/payout_curve/examples/payout_curve.gp
crates/payout_curve/examples/payout_curve_csv.rs
crates/payout_curve/src/lib.rs
crates/payout_curve/src/payout_curve/payout_curve.gp
crates/payout_curve/tests/integration_proptests.rs
crates/trade/Cargo.toml
crates/trade/src/cfd.rs

Took me longer than expected. 
Also plotting the computed points: 
A PR will follow once this is in which tackles:
- Apply fee in margin
- Cut-off payout points which are below dust
see here: https://github.com/get10101/10101/issues/1548

feat: payout curve

---

CHANGELOG.md
coordinator/src/admin.rs
coordinator/src/routes.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln/common_handlers.rs
crates/ln-dlc-node/src/node/mod.rs

Resolves https://github.com/get10101/10101/issues/1406

 feat: allow specifying tx fee for channel opening

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6770604016.
I've bumped the versions in the manifest files in this commit: 733a188cfa846613206d1dda2ee309e88c4548bb.

Release version 1.5.0

---

coordinator/src/payout_curve.rs
crates/payout_curve/src/lib.rs

Fixes to #1566.
@bonomat: Maybe you want to take this over, I just managed to reproduce the cause for the error seen in #1566 using the data from the logs. My understanding is that we just need to ensure that the price ranges can never surpass `2^20 - 1`. And that we should write a proptest to verify this too.

Ensure inverse payout curve does not go over oracle's maximum BTC price

---

mobile/lib/backend.dart

Before this was preventing the app from starting on Linux.

Handle missing FCM token gracefully

---

coordinator/src/admin.rs
coordinator/src/orderbook/routes.rs
coordinator/src/routes.rs

chore: Instrument routes

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6893710831.
I've bumped the versions in the manifest files in this commit: 6ea9b974b895b8012e91a847c41018fd3a4269d7.

Release version 1.5.1

---

mobile/lib/common/app_bar_wrapper.dart
mobile/lib/common/routes.dart
mobile/lib/common/settings/settings_screen.dart

https://github.com/get10101/10101/assets/382048/7485ee28-bbf0-424c-88f1-d94185edac7c

fix: Return to the correct screen after returning from settings

---

coordinator/src/admin.rs
crates/ln-dlc-node/src/node/ln_channel.rs
crates/ln-dlc-node/src/tests/dlc/non_collaborative_settlement.rs
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

fix: Spawn blocking on force-close and close channel

---

CHANGELOG.md
mobile/lib/backend.dart
mobile/lib/features/wallet/application/wallet_service.dart
mobile/lib/features/wallet/onboarding/fund_wallet_modal.dart
mobile/lib/features/wallet/receive_screen.dart
mobile/lib/features/wallet/wallet_change_notifier.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

feat: Refresh lightning wallet on received payment

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6935973732.
I've bumped the versions in the manifest files in this commit: f1066bad8d7b124afa4898d132f32976813438c4.

Release version 1.6.0

---

mobile/native/src/trade/position/mod.rs

Before, the trade cost (the main number associated with a trade in the wallet history screen) did not include the PNL or the order-matching fee. As such, it was only reflecting the margin change.
Now we actually do include these values in the calculation. These values were already available as they were being displayed separately.

Compute trade cost correctly in app wallet history

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6948576259.
I've bumped the versions in the manifest files in this commit: 51252a8dbbc3a22b38ec91e350ecfff2997017a5.

Release version 1.6.1

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6970202580.
I've bumped the versions in the manifest files in this commit: 004e669ec51f82385808976cfecbbade6ef10348.

Release version 1.6.2

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6980655597.
I've bumped the versions in the manifest files in this commit: 2a5c0cb7e58335135961abe93aaaf7e626a18613.

Release version 1.6.3

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/6982760920.
I've bumped the versions in the manifest files in this commit: de166c778409740ee650b9dee3da517693b2d8b0.

Release version 1.6.4

---

CHANGELOG.md
mobile/lib/backend.dart
mobile/lib/common/settings/share_logs_screen.dart
mobile/lib/logger/logger.dart
mobile/lib/main.dart
mobile/lib/util/preferences.dart
mobile/test/trade_test.dart

This should help us debugging the payment routing issues in production.

chore: Set log level to trace

---

maker/src/trading/mod.rs

Resolves https://github.com/get10101/10101/issues/1624

chore: increase the quantity for a single order to 5k

---

coordinator/src/payout_curve.rs
coordinator/src/position/models.rs
crates/payout_curve/examples/payout_curve_csv.rs
crates/payout_curve/src/lib.rs
crates/payout_curve/tests/integration_proptests.rs
crates/trade/src/cfd.rs
mobile/native/src/calculations/mod.rs

On the path to debug https://github.com/get10101/10101/issues/1563 I refactored the API a bit. 
I'm not sure why this refactoring fixed it, but I guess somewhere where the bounds incorrectly set 🙈.
Fixes [#1572](https://github.com/get10101/10101/issues/1572)

Fix: payout curve not continous

---

mobile/native/src/ln_dlc/mod.rs

As requested from the ldk team, I am logging the channel details on a failed payment attempt in the hope it gives us more insights on why a payment has failed.

chore: Log channel details on failed payment attempt

---

mobile/lib/features/wallet/balance.dart
mobile/lib/features/wallet/balance_row.dart
mobile/lib/features/wallet/wallet_screen.dart

Fixes #1677.
https://github.com/get10101/10101/assets/9418575/fdf631ad-7bd6-44c9-8bc2-ed5555e88877

Overhaul wallet balance

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/lib/features/wallet/send/send_lightning_screen.dart
mobile/lib/features/wallet/send/send_onchain_screen.dart
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7145463488.
I've bumped the versions in the manifest files in this commit: c103d603d6eacf2ff555ba4051fd0ee0e2d085f7.

Release version 1.7.1

---

coordinator/src/routes.rs

The Lightning sync is way cheaper anyway, so adding this just ensures that both wallets very likely agree on the state of the blockchain.
This could fix some intermittent failures in our e2e tests, as we were relying on manually triggering a coordinator sync in several spots. In particular, when creating Lightning funding transactions, we noticed that the two wallets could disagree on the latest block height. This could lead to an immediate force-closure of the pending channel due to:
```
Funding transaction absolute timelock is non-final
```

Ensure that coordinator's `post_sync` endpoint syncs both wallets

---

.github/workflows/deliverables-push-main.yml
.github/workflows/docker.yml

This will upload the binaries directly to our testvm. A script on the test vm will check for the existance of the file and deploy it if necessary

feat: upload released binaries to server

---

Cargo.lock
Cargo.toml
coordinator/migrations/2023-12-04-152138_add_position_state_proposed/down.sql
coordinator/migrations/2023-12-04-152138_add_position_state_proposed/up.sql
coordinator/migrations/2023-12-04-162031_add_position_state_failed/down.sql
coordinator/migrations/2023-12-04-162031_add_position_state_failed/up.sql
coordinator/migrations/2023-12-11-101131_add_position_resize_proposed/down.sql
coordinator/migrations/2023-12-11-101131_add_position_resize_proposed/up.sql
coordinator/src/db/custom_types.rs
coordinator/src/db/positions.rs
coordinator/src/node.rs
coordinator/src/position/models.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
mobile/native/Cargo.toml
mobile/native/src/db/custom_types.rs
mobile/native/src/db/models.rs
mobile/native/src/ln_dlc/node.rs
mobile/native/src/trade/order/mod.rs

resolves https://github.com/get10101/10101/issues/1670

feat: reject outdated dlc offers

---

coordinator/src/node.rs

This will help getting some context when reading the log messages.

chore: sprinkle a few log and context statements in the code

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7195343756.
I've bumped the versions in the manifest files in this commit: dded99aff04ccbdbd689ca150628e91dd3f5a49e.

Release version 1.7.2

---

.github/auto_assign.yml
.github/workflows/author.yml

So that @holzeis doesn't have to manually assign us all the time 😅
-----
-----
-----
-----
...

feat(ci): auto assigns PRs to the author

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7200774081.
I've bumped the versions in the manifest files in this commit: 6b37b4e175eb64bb1fdf6aca52d7f3a70f5592b4.

Release version 1.7.3

---

Cargo.lock
coordinator/Cargo.toml
coordinator/src/admin.rs
coordinator/src/bin/coordinator.rs
coordinator/src/node.rs
coordinator/src/orderbook/trading.rs
coordinator/src/routes.rs
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/invoice.rs
maker/Cargo.toml
maker/src/bin/maker.rs
maker/src/routes.rs

Remove `autometrics`

---

coordinator/src/collaborative_revert.rs
coordinator/src/node/rollover.rs
coordinator/src/orderbook/trading.rs
coordinator/src/position/models.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln/coordinator_event_handler.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/payout_curve/src/lib.rs
crates/trade/src/cfd.rs
crates/trade/src/lib.rs
mobile/native/src/db/custom_types.rs
mobile/native/src/db/models.rs
mobile/native/src/ln_dlc/node.rs

This is the more important one: 15963d97e2d18991f6b0f78fb9cdb71af3b9e0c5. I wasted some time debugging because of this yesterday.

Miscellaneous improvements

---

mobile/lib/features/wallet/send/send_onchain_screen.dart

This could cause issues and is unused in any case

chore: remove trade values in sending on chain

---

coordinator/src/node/resize.rs

If we do this we are less likely to have inconsistent state between the DB and the subchannel data.
We should do this in more places.

Roll back DB transaction if resize protocol start fails 

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7272469668.
I've bumped the versions in the manifest files in this commit: 7bf8682a44a5d1dccb47308a3c18d3f0f9ae5fdf.

Release version 1.7.4

---

CHANGELOG.md
mobile/lib/common/settings/app_info_screen.dart
mobile/lib/common/settings/open_telegram.dart
mobile/lib/common/settings/settings_screen.dart

chore: make it easier to find telegram link

---

CHANGELOG.md
mobile/lib/features/wallet/domain/wallet_history.dart
mobile/lib/features/wallet/wallet_history_item.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

resolves #1800
https://github.com/get10101/10101/assets/224613/ecc94f66-1254-4bda-bba3-87b60227811e

feat: show dlc-channel opening tx in tx history

---

CHANGELOG.md
coordinator/src/node/rollover.rs
coordinator/src/scheduler.rs
crates/ln-dlc-node/src/node/dlc_manager.rs
mobile/native/src/ln_dlc/mod.rs

feat: ensure that rollover works with dlc-channels

---

CHANGELOG.md
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
mobile/lib/features/wallet/application/wallet_service.dart
mobile/lib/features/wallet/domain/fee.dart
mobile/lib/features/wallet/send/confirm_payment_modal.dart
mobile/lib/features/wallet/send/fee_picker.dart
mobile/lib/features/wallet/send/send_onchain_screen.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

Resolves #1794 
This PR also changes the custom fee rate logic from a fixed sats amount to a custom sats/vbyte which I think makes more sense to have.

chore: fix reserved utxos

---

coordinator/src/dlc_handler.rs
mobile/native/src/dlc_handler.rs

Some cleanup on the recover from pending offer logic.

fix: Only consider a relevant dlc channels

---

CHANGELOG.md
Cargo.lock
coordinator/migrations/2023-12-04-152138_add_position_state_proposed/down.sql
coordinator/migrations/2023-12-04-162031_add_position_state_failed/down.sql
coordinator/migrations/2023-12-11-101131_add_position_resize_proposed/down.sql
coordinator/migrations/2024-01-16-135827_remove_unneeded_fields_from_collab_revert_table/down.sql
coordinator/migrations/2024-01-16-135827_remove_unneeded_fields_from_collab_revert_table/up.sql
coordinator/src/admin.rs
coordinator/src/collaborative_revert.rs
coordinator/src/db/collaborative_reverts.rs
coordinator/src/orderbook/collaborative_revert.rs
coordinator/src/position/models.rs
coordinator/src/routes.rs
coordinator/src/schema.rs
crates/commons/src/collab_revert.rs
crates/commons/src/message.rs
mobile/native/Cargo.toml
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/orderbook.rs
mobile/pubspec.lock

resolves #1809 
Tested manually. 
https://drive.google.com/file/d/1798JHsB6gIOfUsmmcBNE8cpCVdoBIPrP/view?usp=sharing
@luckysori : how far are you with https://github.com/get10101/10101/issues/1798? I thought I'd wait for your changes to add an e2e test for this feature.

feat: collaborative revert dlc channels

---

Cargo.lock
Cargo.toml
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/trade/trade_dialog.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/trade/order/handler.rs

Set required confirmations on DLC channel to 1

---

coordinator/src/routes.rs
crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/tests/rollover_position.rs
mobile/native/src/ln_dlc/node.rs
mobile/native/src/trade/position/handler.rs

Fix #1833.
Also fixing the way the app handles the rollover. The logic was not quite correct.
And it still isn't if we take into account resizing. Thus, I added a FIXME.

Reintroduce rollover protocol e2e test

---

mobile/native/src/ln_dlc/node.rs

I noticed that both parties can trigger a collaborative dlc channel close, but only the coordinator had the logic implemented to also accept it. This will allow the app also to accept a collab close offer from the coordinator.

fix: Accept collaborative close offer from coordinator

---

coordinator/src/node.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/src/setup.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/trade/order/handler.rs

This looks like a mistake. 
I noticed because `can_open_close_open_close_position` was failing locally. With this it works.

fix: error if the channel is not confirmed

---

mobile/native/src/backup.rs

It might be helpful to monitor if backups are growing out of control.

Log backup size

---

webapp/frontend/lib/common/scaffold_with_nav.dart
webapp/src/main.rs

Otherwise the app is not properly hosted when run in cargo

fix: Load assets from correct path

---

coordinator/src/node.rs

When debugging a recent problem, I was looking for an ERROR message in the coordinator logs. I saw these two ERROR messages and I was immediately confused, until I finally realised that they were the same error message, but duplicated.
```
ERROR Failed to execute trade. Error: Cannot trade with counterparty X with DLC channel in state "SettledConfirmed" trader_id=X order_id=Y
DEBUG back_up: coordinator::backup: Create user backup node_id=Z backup.key="10101/db"
ERROR error=InternalServerError("Could not handle trade request: Cannot trade with counterparty X with DLC channel in state \"SettledConfirmed\"")
```
That's not good developer experience. The reason why this was added was to really make sure that error messages are printed to the logs, but we should just fix the places where …

Remove duplicated error log

---

Cargo.lock
webapp/Cargo.toml
webapp/frontend/lib/common/scaffold_with_nav.dart
webapp/frontend/lib/common/version_service.dart
webapp/frontend/lib/main.dart
webapp/frontend/lib/routes.dart
webapp/frontend/pubspec.yaml
webapp/src/api.rs
webapp/src/main.rs

Demonstrates a simple cut through from the web ui to the backend.

feat: Add version endpoint

---

webapp/frontend/lib/common/amount_text.dart
webapp/frontend/lib/common/amount_text_input_form_field.dart
webapp/frontend/lib/common/balance.dart
webapp/frontend/lib/common/model.dart
webapp/frontend/lib/common/scaffold_with_nav.dart
webapp/frontend/lib/common/theme.dart
webapp/frontend/lib/routes.dart
webapp/frontend/lib/trade/trade_screen.dart
webapp/frontend/lib/trade/trade_screen_order_form.dart
webapp/frontend/lib/wallet/send_screen.dart
webapp/frontend/lib/wallet/wallet_screen.dart
webapp/frontend/lib/wallet/wallet_service.dart
webapp/frontend/pubspec.yaml

first part of trade screen
https://github.com/get10101/10101/assets/224613/1046df69-cb21-4992-be2b-8a9cb5113dbf

feat: tradescreen layout

---

webapp/frontend/lib/logger/logger.dart
webapp/frontend/lib/logger/simple_utc_printer.dart
webapp/frontend/lib/main.dart
webapp/frontend/pubspec.yaml

this will print in the console when run through `flutter run` - if hosted, it will only print in the browser console.

feat(web): add minimalistic frontend logger

---

webapp/build.rs
webapp/frontend/lib/common/scaffold_with_nav.dart
webapp/frontend/lib/common/version_service.dart
webapp/frontend/lib/main.dart
webapp/frontend/lib/settings/app_info_screen.dart
webapp/frontend/lib/settings/settings_screen.dart
webapp/frontend/lib/settings/settings_service.dart
webapp/src/api.rs
webapp/src/main.rs

feat: Add app info to settings

---

webapp/frontend/lib/settings/seed_screen.dart
webapp/frontend/lib/settings/seed_words.dart
webapp/frontend/lib/settings/settings_screen.dart
webapp/frontend/lib/settings/settings_service.dart
webapp/src/api.rs
webapp/src/main.rs

feat: Show seed phrase in settings

---

.github/workflows/docker.yml
justfile
webapp/Dockerfile

I hope it works.... (tested on my fork)
https://github.com/bonomat/10101/pkgs/container/10101%2Fwebapp

feat: add a simple docker image for the webapp

---

.github/workflows/docker.yml

I just want to trigger the CI build ... lease don't hit me 🙈

Very important change!

---

webapp/frontend/lib/trade/order_and_position_table.dart

feat: Indicate positions direction on quantity

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7665258817.
I've bumped the versions in the manifest files in this commit: bd570b97f3c3f43bbb778318d80febc3379042fc.

Release version 1.8.1

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7667871135.
I've bumped the versions in the manifest files in this commit: 0b711a47f3161aa26cf3a4b52c33d23382f12f15.

Release version 1.8.2

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7671679057.
I've bumped the versions in the manifest files in this commit: fdc0ee1573e0822cbf11172169b9aed34022e140.

Release version 1.8.3

---

coordinator/src/admin.rs
coordinator/src/routes.rs
crates/ln-dlc-storage/src/lib.rs

Otherwise only one broken dlc channel breaks the whole function.

fix: Log error for failed channels to deserialize

---

mobile/lib/features/wallet/application/wallet_service.dart
mobile/lib/features/wallet/domain/share_payment_request.dart
mobile/lib/features/wallet/receive_screen.dart
mobile/native/src/api.rs

fix: share address without BIP-21 query component

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7725686380.
I've bumped the versions in the manifest files in this commit: be44e54f0a260a614785b621e21979ed92e3c08d.

Release version 1.8.4

---

crates/ln-dlc-node/src/node/ln_channel.rs

We already have better tested logic in `rust-dlc` to handle any channel closures coming from `rust-lightning`.
This change is important because the logic to choose between closing via `rust-dlc` or `rust-lightning` was flawed, as some vanilla LN channels still had old subchannel state associated with them. Now we can just attempt to close via `rust-lightning` _first_ and then fall back to `rust-dlc` if the channel is currently split.

Alwasy force-close LN-DLC channel via `rust-lightning` first

---

mobile/native/src/storage.rs

This is producing quite a lot of unnecessary load.

chore: Stop creating lightning backups

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7782388195.
I've bumped the versions in the manifest files in this commit: d94f4869d52e276c0796e898cded0e98afc60ea3.

Release version 1.8.5

---

.github/workflows/android-fastlane.yml
.github/workflows/deliverables-push-main.yml

resolves [#1642](https://github.com/get10101/10101/issues/1642)

feat: release apk to github releases

---

webapp/frontend/lib/trade/trade_screen_order_form.dart
webapp/frontend/lib/trade/tradingview/tradingview.dart
webapp/frontend/pubspec.yaml

Resolves https://github.com/get10101/10101/issues/1979

fix: div by 0 and no trading view

---

webapp/src/logger.rs

chore: Set tower sessions core level to warn

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7829651333.
I've bumped the versions in the manifest files in this commit: 77f052037665172dfa6967a99b7fcfcae1f48d87.

Release version 1.8.6

---

mobile/lib/common/dlc_channel_change_notifier.dart
mobile/lib/common/settings/collab_close_screen.dart

Otherwise the channel state is not correctly considered.

fix: Refresh dlc channels when opening collab close screen

---

CHANGELOG.md
mobile/lib/features/welcome/welcome_screen.dart

this will allow us to display nicely on a smaller device as well.
Resolves https://github.com/get10101/10101/issues/1993

fix: don't use fix width but expand row

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7855897266.
I've bumped the versions in the manifest files in this commit: a15ec2b893751ec4d56a58500ced024d85a60bef.

Release version 1.8.7

---

.github/workflows/android-fastlane.yml
.github/workflows/ci.yml
.github/workflows/ios-fastlane.yml
crates/tests-e2e/src/setup.rs
crates/tests-e2e/tests/e2e_collaborative_close_channel.rs
crates/tests-e2e/tests/e2e_open_position_small_utxos.rs
crates/tests-e2e/tests/e2e_reject_offer.rs
docker-compose.yml

I might have caught one or the other flaky test with this. 
Might have fixed #1894

fix: e2e tests

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7902530033.
I've bumped the versions in the manifest files in this commit: 415d0a70a518a4adcc792e19c8095cf3420d3273.

Release version 1.8.8

---

.github/workflows/ci.yml

Should help with https://github.com/get10101/10101/issues/2033

chore(ci): print db logs in case of an e2e error

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7956235659.
I've bumped the versions in the manifest files in this commit: 85129ee4f08fd51328bd0bb735e975b005b0a992.

Release version 1.8.9

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7969422683.
I've bumped the versions in the manifest files in this commit: d738b45844e2ff4bfa8bd354efdb255f7ae8196d.

Release version 1.8.11

---

CHANGELOG.md
mobile/native/src/ln_dlc/node.rs

feat: pending balance is good balance

---

CHANGELOG.md
Cargo.lock
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8045317990.
I've bumped the versions in the manifest files in this commit: 2f3180443618bd7c864ba8a7d9b260ae6acc9520.

Release version 1.9.0

---

mobile/lib/common/settings/app_info_screen.dart

The current link points to telegram, this fixes this

fix: Github link in app info

---

.github/workflows/draft_new_release.yml

fixes https://github.com/get10101/meta/issues/356

chore(ci): Bump webapp version in Cargo.toml on draft release

---

mobile/lib/features/trade/position_list_item.dart

chore(app): Reduce position list item height

---

mobile/lib/features/trade/channel_configuration.dart

chore(app): Reduce channel config modal height to match order modal height

---

mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart

chore(app): Improve formatting on confirmation modal

---

mobile/lib/common/task_status_dialog.dart
mobile/lib/features/trade/trade_dialog.dart

chore(app): Reduce rounding on the status dialog

---

mobile/lib/common/scaffold_with_nav_bar.dart
mobile/lib/common/task_status_dialog.dart
mobile/lib/features/wallet/wallet_history_item.dart
mobile/lib/features/welcome/onboarding.dart
mobile/lib/features/welcome/welcome_screen.dart
mobile/lib/main.dart

|                                       |                                       |                                       |
|:-------------------------------------:|:-------------------------------------:|:-------------------------------------:|
| ![image](https://github.com/get10101/10101/assets/382048/bc8f7167-66f5-4374-b052-c1a945228d5a) | ![image](https://github.com/get10101/10101/assets/382048/481375fd-8a0f-40e3-9d4c-68ff1576808b) | ![image](https://github.com/get10101/10101/assets/382048/9c7dd53d-57d2-4014-8825-c6905036c87b)

chore(app): Rework some styling changes after the flutter upgrade

---

mobile/lib/features/wallet/receive_screen.dart
mobile/lib/features/wallet/send/confirm_payment_modal.dart

fixes https://github.com/get10101/meta/issues/362

chore(app): Remind about minimum channel collateral when receiving on chain funds

---

crates/ln-dlc-node/src/bitcoin_conversion.rs
mobile/lib/common/settings/emergency_kit_screen.dart
mobile/native/src/api.rs
mobile/native/src/emergency_kit.rs
mobile/native/src/lib.rs
mobile/native/src/trade/position/handler.rs

This will allow our users to recover from a very specific symptom, which resulted out of a bug.

feat(emergency kit): Add delete position and resend settle finalize message

---

mobile/lib/common/app_bar_wrapper.dart

This hopefully fixes an issue were I noticed that sometimes the app bar wrapper changed its background color.

chore(app): Set background color on app bar wrapper

---

webapp/frontend/lib/common/amount_text.dart
webapp/frontend/lib/common/currency_change_notifier.dart
webapp/frontend/lib/common/currency_selection_widget.dart
webapp/frontend/lib/common/model.dart
webapp/frontend/lib/common/scaffold_with_nav.dart
webapp/frontend/lib/main.dart
webapp/frontend/lib/trade/position_table.dart

This enables the user to display position values either in Sats/Btc or USD.
Values are a bit jumpy, but I guess it's good enough
Resolves #2155
https://github.com/get10101/10101/assets/224613/db986131-01f2-4daf-929e-36330463e0f3

feat(webapp): add currency toggle to navbar to display balances in Sats/Btc or USD

---

mobile/native/src/ln_dlc/mod.rs

fix(balance): Check sub details received from sent

---

mobile/native/src/ln_dlc/mod.rs

fix(wallet): Sync on chain wallet periodically

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8204563454.
I've bumped the versions in the manifest files in this commit: f62040b9e60e8dec18cf7582534a192c6e6a1734.

Release version 2.0.0

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8231921765.
I've bumped the versions in the manifest files in this commit: a19fd55c332759362ae71f1d06ec8a47bca59bd2.

Release version 2.0.1

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8232220450.
I've bumped the versions in the manifest files in this commit: 4b6ca950910fe3b16468df57d95c7e87026d01cc.

Release version 2.0.2

---

mobile/lib/common/settings/wallet_settings.dart

fix: Make wallet settings scrollable

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8238694095.
I've bumped the versions in the manifest files in this commit: c9f7d1332ac3608d5d2593f83ea7a3144b31c54f.

Release version 2.0.4

---

webapp/src/session.rs

Fixes https://github.com/get10101/10101/issues/1938.
There was definitely a deadlock here, so I'm closing optimistically closing #1938, as this may be the only deadlock.
Probably didn't need to bother with the repro, but it was a fun exercise.
Thanks for spotting it, @Restioson!

Prevent deadlock in `webapp`

---

coordinator/src/node.rs

chore: Set dlc protocol to failed if offer gets rejected

---

crates/ln-dlc-node/src/ln/contract_details.rs

chore: Add event id to contract details

---

mobile/lib/backend.dart
mobile/lib/common/application/clickable_help_text.dart
mobile/lib/common/application/share_logs_button.dart
mobile/lib/common/routes.dart
mobile/lib/common/settings/share_logs_screen.dart
mobile/lib/features/trade/trade_dialog.dart
mobile/lib/features/welcome/error_screen.dart
mobile/lib/features/welcome/loading_screen.dart

fixes #2120 
https://github.com/get10101/10101/assets/382048/5f5152c1-43b9-4540-921c-2760208ef072

feat(app): Show error page when app fails to start

---

mobile/lib/features/trade/order_list_item.dart

fix(app): format price in order view as USD

---

Cargo.lock
Cargo.toml
crates/fund/src/coordinator.rs
crates/ln-dlc-node/src/blockchain.rs
crates/ln-dlc-node/src/dlc_wallet.rs
crates/ln-dlc-node/src/ln/dlc_channel_details.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/dlc_manager.rs
crates/ln-dlc-node/src/tests/dlc_channel.rs
crates/ln-dlc-storage/src/lib.rs
crates/tests-e2e/src/bitcoind.rs
crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/tests/e2e_force_close_settled_channel.rs
mobile/lib/common/dlc_channel_change_notifier.dart
mobile/lib/common/domain/dlc_channel.dart
mobile/native/src/dlc_channel.rs
webapp/frontend/lib/common/channel_state_label.dart
webapp/frontend/lib/settings/channel_screen.dart
webapp/frontend/lib/settings/dlc_channel.dart
webapp/frontend/lib/settings/dlc_channel.g.dart
webapp/frontend/lib/trade/position_table.dart
webapp/src/api.rs

Matching `rust-dlc` PR: https://github.com/get10101/rust-dlc/pull/15.

Claim settle transaction funds after force-close

---

Cargo.toml

See https://github.com/p2pderivatives/rust-dlc/commit/a569d3e.
Resolves https://github.com/get10101/10101/pull/2198#discussion_r1518155731.

Trigger `sub_channel_manager` periodic check less often

---

webapp/frontend/web/index.html

I'm not sure what is exactly happening here but this fixes the issue :)
Recommended solution from https://github.com/flutter/flutter/issues/94924#issuecomment-990539514
Resolves #2234

fix: iFrameElement captures input from dialog

---

mobile/native/src/ln_dlc/mod.rs

fixes #2246
https://github.com/get10101/10101/assets/382048/4f863744-224d-453b-8c90-e4041fd67a53

fix: Refresh wallet balance and history on node startup 

---

mobile/pubspec.lock

after it has been pushed from the beta flutter version

chore: Downgrade flutter pub spec

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8299621764.
I've bumped the versions in the manifest files in this commit: 3d71505bd94a08c07f64f5b07b0b816d18dfb30d.

Release version 2.0.5

---

mobile/ios/Runner/Info.plist
mobile/macos/Runner/Info.plist

Should fix: https://github.com/get10101/meta/issues/400

fix: a warning we received from apple

---

Cargo.lock
Cargo.toml
crates/dev-maker/Cargo.toml
crates/dev-maker/bitmex_hourly_rates.json
crates/dev-maker/fetch_rates.sh
crates/dev-maker/src/historic_rates.rs
crates/dev-maker/src/logger.rs
crates/dev-maker/src/main.rs
crates/dev-maker/src/orderbook_client.rs
justfile

feat: introduce dev-maker

---

crates/ln-dlc-node/src/dlc_wallet.rs
mobile/lib/common/amount_text_input_form_field.dart
mobile/lib/common/domain/model.dart
mobile/lib/features/trade/channel_configuration.dart
mobile/lib/features/trade/collateral_slider.dart
mobile/lib/features/trade/leverage_slider.dart
mobile/pubspec.lock
mobile/pubspec.yaml
mobile/test/trade_test.dart

This PR introduces a new slider type which is now also being used for the leverage slider. 
Part I of #2139 next is to introduce `Margin Orders`
Resolves https://github.com/get10101/10101/issues/2240
https://github.com/get10101/10101/assets/224613/90744cff-f03f-44d0-93de-5ae65d0575b3

feat(mobile): Select max channel size

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8397248174.
I've bumped the versions in the manifest files in this commit: 4b436ecab6566757d54a82b8b8e509fa10a5c8c2.

Release version 2.0.6

---

mobile/native/src/trade/order/orderbook_client.rs

fix: Return error message on failed post order

---

mobile/lib/features/trade/trade_dialog.dart

chore: Remove share button on trade dialog

---

mobile/lib/common/settings/app_info_screen.dart

FAQ Link is outdated
related to https://github.com/get10101/10101.github.io/pull/74

fix: update FAQ link in app_info_screen.dart

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8430842781.
I've bumped the versions in the manifest files in this commit: ec0e2055298974a267033a8ad8ce69c397713beb.

Release version 2.0.7

---

coordinator/src/db/polls.rs

fix: Do not load inactive polls

---

mobile/lib/features/trade/trade_screen.dart

Resolves #2258 
I've implemented this while debugging our latest issues.

feat(app): show latest price in trading overview

---

coordinator/migrations/2024-03-28-112500_add_trader_realized_pnl_to_trade/down.sql
coordinator/migrations/2024-03-28-112500_add_trader_realized_pnl_to_trade/up.sql
coordinator/src/db/trades.rs
coordinator/src/dlc_protocol.rs
coordinator/src/schema.rs
coordinator/src/trade/models.rs

feat: Add trader realized pnl to trades

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8482844647.
I've bumped the versions in the manifest files in this commit: 7a0e4a0b5861d7bbf5d8bb944ac97c00bf2f1b22.

Release version 2.1.0

---

mobile/lib/common/amount_text_input_form_field.dart
mobile/lib/common/init_service.dart
mobile/lib/features/trade/application/trade_values_service.dart
mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_value_change_notifier.dart
mobile/native/src/api.rs
mobile/native/src/lib.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/max_quantity.rs
mobile/test/trade_test.dart

Clicking the max button next to the quantity input field will lock the quantity to stay on the max value.
https://github.com/get10101/10101/assets/382048/01131a53-175d-41c8-9240-30c75819e3bb

feat: Add max quantity button

---

mobile/native/src/trade/order/handler.rs

Not super optimistic that this will fix #2291 but its the best idea I have right now. I presume the issue happened due to some kind of race condition, where the coordinator thinks the dlc channel is in `Established` while the app is in `SettleAccepted`.
With https://github.com/get10101/10101/pull/2294 it shouldn't happen that the `SettleAccept` message gets lost. This patch will ensure that the app is also not possible if its channel state is in an intermediate state.
maybe fixes #2291

chore: Prevent order submission in intermediate dlc channel state

---

coordinator/src/bin/coordinator.rs
coordinator/src/db/dlc_channels.rs
coordinator/src/db/positions.rs
coordinator/src/dlc_protocol.rs
coordinator/src/node/channel.rs
coordinator/src/node/expired_positions.rs
coordinator/src/position/mod.rs
coordinator/src/trade/mod.rs
crates/ln-dlc-node/src/node/mod.rs
mobile/lib/common/settings/force_close_screen.dart
mobile/native/src/lib.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/position.rs

Fix: Close open position if dlc channel got force closed

---

coordinator/src/scheduler.rs

follow up to review remarks on https://github.com/get10101/10101/pull/2354

chore(jobs): Remove risky expects

---

mobile/native/src/ln_dlc/mod.rs
webapp/frontend/lib/services/wallet_service.dart
webapp/src/api.rs
webapp/src/cli.rs
webapp/src/main.rs

feat: Add ability to whitelist withdrawal addresses

---

coordinator/example-settings/prod-coordinator-settings.toml
coordinator/example-settings/test-coordinator-settings.toml
coordinator/src/settings.rs
mobile/lib/common/application/tentenone_config_change_notifier.dart
mobile/lib/common/domain/model.dart
mobile/lib/common/domain/referral_status.dart
mobile/lib/common/domain/tentenone_config.dart
mobile/lib/common/settings/user_screen.dart
mobile/lib/features/brag/brag.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/wallet/referral_widget.dart
mobile/native/src/api.rs
mobile/native/src/event/api.rs
mobile/test/trade_test.dart

fixes #2376 
|		|		|		|
|:---:|:---:|:---:|
|	![Simulator Screenshot - iPhone 15 Pro - 2024-04-11 at 16 12 20](https://github.com/get10101/10101/assets/382048/2bae41be-7274-4f88-93c0-bc74bc65f0aa)	|	![Simulator Screenshot - iPhone 15 Pro - 2024-04-11 at 16 12 29](https://github.com/get10101/10101/assets/382048/cde94053-6089-49bb-8473-553e0326ab73)	|	![Simulator Screenshot - iPhone 15 Pro - 2024-04-11 at 16 12 44](https://github.com/get10101/10101/assets/382048/6fa3129d-0087-4715-9698-74d845f9a633)	|	
| ![Simulator Screenshot - iPhone 15 Pro - 2024-04-11 at 16 12 50](https://github.com/get10101/10101/assets/382048/5e5d41ae-21b1-402b-81df-9f02695fbfe2)	|	![Simulator Screenshot - iPhone 15 Pro - 2024-04-11 at 16 00 33](https://github.com/get10101/10101/assets/382048/10dfa806-b71f-47a6-bef4-f3 …

feat: Show fee rebate on order matching fee

---

mobile/lib/common/settings/user_screen.dart
mobile/lib/features/wallet/referral_widget.dart

**Before**
Join me and trade without counter-party risk. Use this referral to get a fee discount: 2E4630
**After**
Join me and trade without counter-party risk. https://referral.10101.finance?referral=2E4630
---
I think the user will need the link to our website to download the app, otherwise the flow may be interrupted by where to get the app.
fixes #2390

chore: Add referral link to share text

---

coordinator/src/db/bonus_tiers.rs
coordinator/src/referrals.rs

we are filtering the users by their volume in code later
fixes [#2406](https://github.com/get10101/10101/issues/2406)

fix: return all referred users

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8699920875.
I've bumped the versions in the manifest files in this commit: 2d5dbac407b2e084f423cca0069b9ea417cafe32.

Release version 2.2.0

---

justfile
webapp/README.md

doc: update dlc connect documentation

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8724602229.
I've bumped the versions in the manifest files in this commit: 364445ad8fdafd5dfa8aa60add608d17fc9614e1.

Release version 2.2.1

---

mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs
webapp/src/api.rs

fix(ui): Calculate fee rebate from full order matching fee

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8755062749.
I've bumped the versions in the manifest files in this commit: 0fdc428499e2fbeb5df7088ea9b6a52080a5e7f8.

Release version 2.2.2

---

mobile/lib/common/amount_text.dart
mobile/lib/common/usd_text_field.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart

fix: Align price roundings

---

Cargo.lock
mobile/lib/features/trade/trade_dialog.dart

fix: Show fee rebate on trade dialog

---

.github/workflows/ios-fastlane.yml

This needed now and was missing

fix: missing input for workflow

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8846647177.
I've bumped the versions in the manifest files in this commit: cbf8ee9dcecd485530972d99e1b863f5c0baf2de.

Release version 2.2.3

---

crates/xxi-node/src/lib.rs
crates/xxi-node/src/node/mod.rs
crates/xxi-node/src/node/wallet.rs
crates/xxi-node/src/on_chain_wallet.rs
mobile/lib/common/fiat_text.dart
mobile/lib/features/wallet/application/wallet_service.dart
mobile/lib/features/wallet/domain/fee.dart
mobile/lib/features/wallet/domain/fee_estimate.dart
mobile/lib/features/wallet/send/confirm_payment_modal.dart
mobile/lib/features/wallet/send/fee_picker.dart
mobile/lib/features/wallet/send/fee_text.dart
mobile/lib/features/wallet/send/send_onchain_screen.dart
mobile/native/src/api.rs
mobile/native/src/dlc/mod.rs
webapp/frontend/lib/common/model.dart
webapp/frontend/lib/services/wallet_service.dart
webapp/frontend/lib/wallet/send_screen.dart
webapp/src/api.rs

Fixes #2451.
Fixes https://github.com/get10101/10101/issues/2196.
Tackles part of https://github.com/get10101/10101/issues/2452#issuecomment-2065768696.
https://github.com/get10101/10101/assets/9418575/a08eaccd-ad53-4c3b-8bc6-721298ab044a

Fix custom fee when sending on-chain

---

Cargo.lock
Cargo.toml
coordinator/Cargo.toml
coordinator/src/storage.rs
crates/xxi-node/Cargo.toml
crates/xxi-node/src/lib.rs
mobile/native/Cargo.toml
mobile/native/src/storage.rs

@bonomat @luckysori do we still need to point to our lightning fork?

chore: Remove left-over lightning dependencies

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8942296626.
I've bumped the versions in the manifest files in this commit: d886feef0c5ee1a32839b57ef04124a7fab697d7.

Release version 2.3.0

---

mobile/native/src/trade/order/handler.rs

Otherwise, a short delay could happen after submitting the order before the dialog is shown. This was more obvious on the test vm the other day, when the submit order request timed out.

fix: Show pending trade dialog immediately when submitting an order

---

mobile/android/app/build.gradle

This seems to be needed for `flutter_inappwebview`

chore: set android compile version to 34

---

webapp/frontend/lib/common/model.dart
webapp/frontend/lib/services/wallet_service.dart
webapp/frontend/lib/wallet/send_screen.dart

resolves https://github.com/get10101/10101/issues/2520

fix(webapp): send payments from frontend

---

.github/workflows/testflight-for-review.yml

fix: this needs to run on macos obviously

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/9051691320.
I've bumped the versions in the manifest files in this commit: 42892eef715e0d7711ba76667e831ec39deab01a.

Release version 2.4.0

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/9107373591.
I've bumped the versions in the manifest files in this commit: c867b2b2178c75e2fb09e756a390c7397368b2fd.

Release version 2.4.1

---

coordinator/src/routes.rs

see api here: https://github.com/get10101/10101/blob/31fb86ec1b4455d4ec839d80092aba90e8d168fd/coordinator/src/db/user.rs#L102-L110

fix: referral/os were switched

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/9111249876.
I've bumped the versions in the manifest files in this commit: f78a45b90212dbd75bdf62978111b325acfeae91.

Release version 2.4.3

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/9221595299.
I've bumped the versions in the manifest files in this commit: 5d437c38e8b11cde37a4bc7a994231f417d39152.

Release version 2.4.4

---

mobile/lib/features/trade/channel_creation_flow/channel_funding_screen.dart

That was killing me 🙈 
|	**before**	|	**after**	|
|:---:|:---:|
|	![wrong-rotation](https://github.com/get10101/10101/assets/382048/f2fd0b66-f533-4d53-9780-8c09abe77791)	|	![reversed-rotation](https://github.com/get10101/10101/assets/382048/f2f0a179-e243-4c85-b8e9-f089fc7bb07e)	|

chore: Make rotation direction of rotating icon configurable

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/9286193857.
I've bumped the versions in the manifest files in this commit: 98c9c83deff91d1405b8a8f6411dd3811aede62a.

Release version 2.4.5

---

mobile/lib/features/trade/leverage_slider.dart

feat: why you no go max bro?

---

mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart

Nice and small one :)
Fixes #2577

fix: Don't show margin when closing position

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml

Revert "chore(deps): bump openssl from 0.10.60 to 0.10.66"

---

mobile/ios/fastlane/Matchfile

let's see if this fixes the CI

fix: revert this change

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/10297911595.
I've bumped the versions in the manifest files in this commit: 2896b16276bf90e2a2813a048f11b173001f9b1d.

Release version 2.4.10

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/10331381604.
I've bumped the versions in the manifest files in this commit: 9b220994f916201057f577feb25e76f1a645b4b7.

Release version 5.0.0

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/10331418829.
I've bumped the versions in the manifest files in this commit: 15f70e92bdc7aea50ea3f88c6fb44ec1fb2a07c1.

Release version 3.0.0

---

Cargo.lock
Cargo.toml

Add more log context to try_finalize_settled_closing_channel

---

Cargo.lock
Cargo.toml

See https://github.com/p2pderivatives/rust-dlc/commit/41f34a33269153c4b05d623842b371fab47822a0.

Use correct input in settle claim transaction

---

.github/workflows/ci.yml
.github/workflows/create_release.yml

Update upload/download-artifact GH actions

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @luckysori!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/11548266287.
I've bumped the versions in the manifest files in this commit: c51cc94992283d19e40b42eb38cef33cd57769d6.

Release version 4.0.1
