docs/005-mobile-app-routing.adoc

I found it quite hard to take a decision on this, but after some back and forth I would still use `go_router` because it just has the most active dev activity. 
If we think that the feature of *conveniently* preserving state in nested routes is super important we should consider using `beamer` or `auto_route`. I think we can also work around it with `go_router` for now, but it might be a bit cumbersome.
[Showcase of the limitation and workaround](https://codewithandrea.com/articles/flutter-bottom-navigation-bar-nested-routes-gorouter-beamer/) (in comparison to `beamer` that makes it more convenient; [`auto_route` docs](https://pub.dev/packages/auto_route#tab-navigation) mention that one can preserve state there as well ).

docs: Add 005 mobile app routing ADR

---

mobile/macos/Podfile
mobile/macos/Runner.xcodeproj/project.pbxproj

With the latest flutter version `stable, 3.7.0, on macOS 13.1 22C65 darwin-x64, locale en-AU` and the latest Cocoapod version `1.11.3` I run into these changes.
--- 
@bonomat could you run `just deps` and `just run` from `main` and see if you get the same? 
I am not sure how relevant these changes are, but eventually it will happen that they slip into a PR.

update: podfile

---

justfile

it looks like due to the folder structure the target folder is one level up

fix: copy from the correct folder

---

Cargo.lock
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/logger.rs
crates/ln-dlc-node/src/on_chain_wallet.rs

Two commits here
- Create all data dirs for on chain walet: this will create all required parent directories (similar to `mkdir -p`)
- Log rust-lightning records to tracing: this logs records from rust-lightning crates to tracing through the tracing_log crate 
This is a small PR because I can't push to upstream currently. Fixes #103.

Fix rust-lightning log & create all data dirs for on chain wallet

---

crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/logger.rs
crates/ln-dlc-node/src/node.rs
crates/ln-dlc-node/src/tests.rs
crates/ln-dlc-node/src/tests/multi_hop_payment.rs
crates/ln-dlc-node/src/tests/single_hop_payment.rs

Global test subscriber was needed to capture traces from threads spawned by the rust-lightning libraries (e.g lightning-background-processor spawns its own threads, which we cannot install the local subscriber in).
I did leave some printlns  hat start with `EVENT` as they seemed to take control of stdout itself and do other things, which I did not understand and want to meddle with yet.

Use a global test subscriber and switch to traces for most printlns

---

mobile/android/app/build.gradle
mobile/android/app/src/debug/AndroidManifest.xml
mobile/android/app/src/main/AndroidManifest.xml
mobile/android/app/src/main/kotlin/com/example/flutter_rust_bridge_template/MainActivity.kt
mobile/android/app/src/profile/AndroidManifest.xml
mobile/ios/Runner.xcodeproj/project.pbxproj
mobile/linux/CMakeLists.txt
mobile/macos/Runner/Configs/AppInfo.xcconfig

Took my brain overnight that it might be better to align these - I only changed some of them yesterday :)
Tested deploy to my Android phone and iOS simulator after a `flutter clean`

fix: align all product identifier strings to `finance.get10101.app`

---

mobile/lib/features/trade/contract_symbol_icon.dart
mobile/lib/features/trade/domain/contract_symbol.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/trade/trade_screen.dart
mobile/test/contract_symbol_test.dart

Introduce `ContractSymbol` in the UI and harmonize the name.
---
Not sure we want to open that can of worms again: Terminology.
At first I thought about opening a discussion, but I am not sure it's worth it. In the end we just have to agree what we use - I think there is no golden path here.
I opted for using `contract symbol` because that's what we agreed upon in the past.
Personally, I find `trading pair` more intuitive - because it does not limit us to "contracts" - but I'm happy roll with `contract symbol` for now.

Refactor: contract symbol instead of trading pair

---

.github/workflows/publish_docker.yml

building the image was broken because of the introduction of a cargo workspace

fix: building docker image for coordinator

---

mobile/ios/Runner/bridge_generated.h
mobile/lib/features/trade/domain/direction.dart
mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/trade_bottom_sheet.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_screen.dart
mobile/lib/features/trade/trade_value_change_notifier.dart
mobile/native/src/api.rs
mobile/native/src/api_calculations/mod.rs
mobile/native/src/api_model/mod.rs
mobile/native/src/api_model/order.rs

Order with direction buy or sell; we can either buy or sell with an order - which adds or reduces a position. 
If a position is "negative" it is a short position, if a position is positive it is a long position.
note on the specific PR: It is disputable what the calculation API for the liquidation price should expose, but since we are only using it in the context of order value calculations I opted for exposing `Direction` and map to position in the API. This is a small implementation detail.
---
When introducing `Order` I had a hard time using `Position` in it - it just does not make sense. We have `buy` and `sell` orders. For me the order indicates the *action* of buying or selling something - to either add to or reduce the position. 
But once we have a position and we are "exposed to …

refactor: direction and position

---

.github/workflows/ci.yml
.gitignore
README.md
justfile
mobile/lib/features/trade/application/trade_values_service.dart
mobile/lib/features/trade/domain/direction.dart
mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/order_change_notifier.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/trade/trade_bottom_sheet.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_screen.dart
mobile/lib/features/trade/trade_tabs.dart
mobile/lib/features/trade/trade_value_change_notifier.dart
mobile/lib/main.dart
mobile/lib/util/constants.dart
mobile/pubspec.lock
mobile/pubspec.yaml
mobile/test/trade_test.dart
mobile/test/widget_test.dart

I am not sure how valuable the test itself is - I will likely do another iteration on that.
The test passes and I think all the other work is valuable to go in; so I thought I'll open a PR now and potentially iterate once merged, so we have a "template" :)
This PR shows how to:
- use keys to identify widgets for testing
- use mockito to mock services
- how proper encapsulation is important for testing - with moving the rust API calcs into a dedicated service we are able to mock it

Add test that clicks through the buy process until the order is submitted

---

.github/workflows/ci.yml
.github/workflows/tests-ln-dlc-node.yml

`Bors` treats skipped required jobs as _failed_. We want to be able to selectively skip certain tests in `ln-dlc-node` because they're slow.
We define a new job whose only purpose is to report a job success to `bors` whether the `run-tests-ln-dlc-node` job is skipped or succeeds.

Allow `ln-dlc-node` tests to be skipped on `bors`

---

mobile/lib/features/trade/domain/order.dart
mobile/native/src/api_model/order.rs
mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/order/mod.rs

Once we execute an order we know the execution price and have to keep it around.
- In rust business logic is makes sense to depict this as falue on the `Filled` enum variant.
- For the `Order` exposed on the API I opted for a nullable fields, because complex enum variants are not fun to be mapped into Dart.

Introduce missing order execution price into the model

---

mobile/lib/common/value_data_row.dart
mobile/lib/features/trade/application/position_service.dart
mobile/lib/features/trade/domain/position.dart
mobile/lib/features/trade/order_change_notifier.dart
mobile/lib/features/trade/position_change_notifier.dart
mobile/lib/features/trade/position_list_item.dart
mobile/lib/features/trade/trade_screen.dart
mobile/lib/features/trade/trade_theme.dart
mobile/lib/main.dart
mobile/native/src/api.rs
mobile/native/src/api_model/event/flutter_subscriber.rs
mobile/native/src/api_model/event/mod.rs
mobile/native/src/api_model/mod.rs
mobile/native/src/api_model/position.rs
mobile/native/src/event/mod.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/trade/mod.rs
mobile/native/src/trade/position/handler.rs
mobile/native/src/trade/position/mod.rs
mobile/native/src/trade/position/subscriber.rs
mobile/pubspec.lock
mobile/pubspec.yaml
mobile/test/trade_test.dart

Position user interface + wired into rust with rust simulating an update with dummies (upon an event from the orderbook).
This does not include closing the position yet.
---
This shows the change of the position after 10 seconds, simulating the lifecycle to some extent:
1. We fetch the position initially 
2. We subscribe to notifications for the position handler from the orderbook event in `run`
3. We subscribe to notifications for position updates for the flutter event subscriber
4. We simulate an orderbook event after 10 seconds
5. We "handle" the event in the position handler and send out a different dummy position
6. The position is updated in the UI :)
note: I don't know why the color green is broken in the gif 😅 
---
This is how the close button is currently implemented; we can …

Position user interface and simulation dummies in rust

---

justfile

So that the seed file checked in on root in the data directory is used. Otherwise a new data directory will be generated within the coordinator directory.

fix: Execute the coordinator from the root directory

---

crates/ln-dlc-node/src/node.rs
crates/ln-dlc-node/src/tests/mod.rs
mobile/lib/features/wallet/application/wallet_service.dart
mobile/lib/features/wallet/receive_screen.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

@da-kami: I've reverted the commit, removing the open channel button.
I had to change one additional configuration, being that the coordinator must not enforce his channel announcement preferences (public inbound channels only), since the app only accepts private channels.
This will now allow us again to open a private channel from the app - I hope we will only work with that temporarily, as this does not reflect the real flow.
This reverts commit 3e2fac2f

Revert "chore: Remove open channel from api"

---

faucet/faucet.html

lnd is returning a 200 status code even if the payment was not successfully. This will check if the `payment_error` field is set, and if so report the payment as error.

chore: Process payment error

---

crates/ln-dlc-node/src/node.rs

Upon creation of a just-in-time channel we use the max of either the `LIQUIDITY_ROUTING_FEE_MILLIONTHS` constant (10_000) or twice the amount of the in-flight payment to define the channel capacity.
In case we do not use the constant, the payment will fail with the current configuration on main, as the `max_inbound_htlc_value_in_flight_percent_of_channel` of the just-in-time-channel rejects pending HTLCs greater than 10% of the total channel capacity.
So, given our current calculation of the channel capacity, this value has to be at least 50%. However, we are setting it to 100% though - see reasoning in the comments.

chore: Increase max inbound htlc value of in flight payments

---

coordinator/src/bin/coordinator.rs
crates/ln-dlc-node/src/disk.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/node.rs
crates/ln-dlc-node/src/tests/mod.rs
mobile/native/src/ln_dlc/mod.rs

The ln_dlc node did save channel data to the disk, but never recovered any channel date from disk. This PR fixes that issues and will allow the node to restart without loosing its channel data.
More specifically this PR will fix the following error (which will be printed by the coordinator or app, if a channel was opened before a restart).
```
ERROR lightning::ln::channelmanager: Failed to find corresponding channel
```
Additionally, the network graph is also read from disk. Eventually, all this data should be stored into and read from the database.

chore: Read channel data from file system upon restart

---

crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/node.rs
crates/ln-dlc-node/src/tests/add_dlc.rs
crates/ln-dlc-node/src/tests/just_in_time_channel.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/ln-dlc-node/src/tests/multi_hop_payment.rs
crates/ln-dlc-node/src/tests/single_hop_payment.rs
dprint.json

This was some work that I've been collecting as I've been trying to verify that the LN channel is usable after a DLC channel has been opened beside it.

Make `ln-dlc-node` tests a bit more resilient

---

crates/ln-dlc-node/src/node.rs
crates/ln-dlc-node/src/tests/just_in_time_channel.rs
crates/ln-dlc-node/src/tests/onboard_from_lnd.rs
mobile/lib/features/wallet/application/wallet_service.dart
mobile/lib/features/wallet/balance_row.dart
mobile/lib/features/wallet/create_invoice_screen.dart
mobile/lib/features/wallet/receive_screen.dart
mobile/lib/features/wallet/share_invoice_screen.dart
mobile/lib/features/wallet/wallet_screen.dart
mobile/lib/main.dart
mobile/linux/flutter/generated_plugin_registrant.cc
mobile/linux/flutter/generated_plugins.cmake
mobile/macos/Flutter/GeneratedPluginRegistrant.swift
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs
mobile/pubspec.lock
mobile/pubspec.yaml
mobile/windows/flutter/generated_plugin_registrant.cc
mobile/windows/flutter/generated_plugins.cmake

This PR adds the invoice creation and sharing UI.
**Acceptance criteria progress (from #178):**
- Need to test this still but I believe it should work?
- I used the currently existing AmountInputField which does not yet do this - could be out of scope for this PR?
- I found a library to simply implement the share function so I just did it in this PR too
- I've made Done return to wherever the user was 2 steps ago in the stack (usually will be wallet overview)
- Wallet does not yet refresh
Closes #178.

Receive payment UI

---

crates/ln-dlc-node/src/node.rs
mobile/native/src/ln_dlc/mod.rs

I am unsure if this is intended to stay that way, but if the mobile app is proposing the dlc channel, the mobile app is offering and the coordinator is accepting. Correspondingly, these values are currently switched.
This change fixes that issue.

fix: Switch roles in dlc channel

---

.github/workflows/ci.yml
bors.toml
mobile/lib/features/trade/domain/order.dart
mobile/lib/features/trade/domain/position.dart
mobile/lib/features/wallet/domain/wallet_info.dart

`main` is currently red because `lint-flutter` does actually not pass.
Sidenote: I can actually not reproduce this locally 😅

chore: add `lint-flutter` job as bors dependency

---

README.md
coordinator/src/cli.rs
crates/ln-dlc-node/src/node.rs
crates/ln-dlc-node/src/util.rs
justfile
mobile/ios/Podfile.lock
mobile/lib/main.dart
mobile/lib/util/environment.dart
mobile/macos/Podfile.lock
mobile/native/src/api.rs
mobile/native/src/config/api.rs
mobile/native/src/config/mod.rs
mobile/native/src/lib.rs
mobile/native/src/ln_dlc/mod.rs
mobile/pubspec.lock

I added quite some descriptions to the commit message. Please refer to https://github.com/get10101/10101/pull/201/commits/c1c02ebb1b1e2674d7d84a41d6c2206a1ea2682d for more details on this PR.
**tl;dr**: This PR fixes an issue with the lnd node and the coordinator not being connected anymore after a restart and allows for configuring the mobile app.
The critical aspect here is that the address the `ln_dlc node` will be bound to is also the address that is used for the node announcement. So you need to start your coordinator with the ip address of your local network.
```
cargo run --bin coordinator -- --p2p-address=10.0.0.20:9045
```
or use the just file analogous.
In order to start the mobile app you need to specify the coordinator p2p-address as well, as the coordinator does not listen to …

feat: Configurable node announcement

---

README.md
docker-compose.yml

it took me a while to notice that we were using `nigiri`. 
I've realised that the easiest way to work around it is to not run 10101 and nigiri at the same time for the time being; I've described how to clear docker state.
Also, I'm using AirPlay and port `5000` blocked me from running the setup.

Fix issues when trying to run docker-compose

---

crates/trade/src/lib.rs
mobile/native/src/api.rs
mobile/native/src/common/api.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/trade/mod.rs
mobile/native/src/trade/order/api.rs
mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/order/mod.rs
mobile/native/src/trade/position/api.rs
mobile/native/src/trade/position/handler.rs
mobile/native/src/trade/position/mod.rs

By using flutter rust bridge - mirror, we can re-export foreign types. This allows us to remove various duplicated types, their conversions and extensions such as `*Trade`.
Read more here:
https://cjycode.com/flutter_rust_bridge/feature/lang_external.html#types-in-other-crates

chore: re-export external types in frb

---

Cargo.lock
mobile/native/Cargo.toml
mobile/pubspec.lock
mobile/pubspec.yaml

This is our critical dependency, so it's worth being up-to-date (we were on 1.63)
Notable improvements:
- support for Option, empty structs
- comments in the API are migrated to Dart
- parameter defaults, structs are const-constructible
- (and more, see: https://github.com/fzyzcjy/flutter_rust_bridge/releases)

Bump flutter_rust_bridge to 1.68

---

coordinator/src/bin/coordinator.rs
coordinator/src/cli.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/invoice.rs
mobile/lib/util/environment.dart
mobile/native/src/config/api.rs
mobile/native/src/config/mod.rs
mobile/native/src/ln_dlc/mod.rs
mobile/pubspec.lock

This will allow to pass the network as argument on the coordinator as well as on the mobile app. Both default to regtest.
Set on coordinator like this.
```
just coordinator signet
```
Set on mobile app like this.
```
just run --dart-define="NETWORK=signet"
```
resolves #202

feat: Configurable network

---

crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs
crates/ln-dlc-node/src/tests/dlc/create.rs

Actually finishes #50.
We should eventually also add assertions for the LN balances and DLC collateral values for all tests where the action results in creating a DLC.

Verify open-close-open DLC channel behaviour 

---

.cargo/config.toml
coordinator/src/logger.rs
coordinator/src/routes.rs
crates/bdk-ldk/src/lib.rs
crates/ln-dlc-node/src/dlc_custom_signer.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/trade/src/lib.rs
maker/src/logger.rs
maker/src/routes.rs
mobile/native/src/db/custom_types.rs
mobile/native/src/lib.rs
mobile/native/src/logger.rs

We've used a similar pattern in past projects.
One thing that has changed is that we use `[target.'cfg(feature = "cargo-clippy")']` instead of `[build]`. This allows us to enforce this lint configuration locally and not just on CI.
Using `rustflags` does mean that devs might encounter unexpected full rebuilds when switching between IDE and command line when using `cargo clippy`. This is a known [issue]. For emacs, I just solved this by setting a different Cargo `target-directory` to the one used by default. A similar approach should work for other IDEs.
[issue]: https://github.com/rust-lang/cargo/issues/8716.

Add Clippy lint workspace configuration

---

Cargo.lock
Cargo.toml
crates/ln-dlc-node/src/tests/dlc/create.rs

By updating a couple of dependencies.
The bug caused the LN wallet balance to appear to be doubled whilst a DLC channel was open.

Fix LN wallet double balance

---

crates/orderbook-commons/Cargo.toml
mobile/native/src/db/custom_types.rs
mobile/native/src/db/mod.rs
mobile/native/src/db/models.rs
mobile/native/src/trade/order/api.rs
mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/order/mod.rs

The previous flow was unnecessarily complicated. The lifecycle of an order should start once we got a reply from the orderbook.
If we succeed to submit the order we assign the `Uuid` returned from the orderbook to the order and safe it in the database. If the fail to submit the order we assign our own `Uuid` to the order and safe it in the database (in `Rejected` state, which is final and we won't query the orderbook with orders in this state). Given that the lifecycle now starts with the result of the submission to the orderbook we don't need an `Initial` state anymore.

refactor: Start the lifecycle of the order after submission to orderbook

---

Cargo.lock
coordinator/Cargo.toml
coordinator/src/node.rs
coordinator/src/routes.rs
crates/coordintator-commons/Cargo.toml
crates/coordintator-commons/src/lib.rs
crates/trade/Cargo.toml
crates/trade/src/lib.rs
mobile/native/Cargo.toml
mobile/native/src/event/mod.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/position/handler.rs

The `TradeParams` are specific to the coordinator, it makes sense to move them to a `coordinator-commons` crate. This has the advantage that we will avoid cyclic dependencies, because we can use `orderbook-commons` to reference the `FilledWith` in `coordinator-commons` and are able to use the global common types of `trade` in other crates.
---
This is in preparation of adapting the `TradeParams` to use `FilledWith` of the `orderbook-commons` crate.

refactor: Move trade params to `coordinator-commons`

---

Cargo.lock
coordinator/src/node.rs
crates/coordintator-commons/Cargo.toml
crates/coordintator-commons/src/lib.rs
mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/position/handler.rs

This brings the trade execution and the orderbook filling information closer together

refactor: We use the `FillWith` of the orderbook for the `TradeParams`

---

.cargo/config.toml

This reduces the chance of cache invalidation between the runs of rust-analyzer, cargo build/run and clippy.
On my machine (with no global Rust config atm), it made huge improvements, ie. no rebuilds from scratch anymore.
There might better ways, but I can't justify spending more time on this right now. Some possible further direction:
- add a separate build profile for rust-analyzer & clippy

Align clippy flags for all builds

---

crates/orderbook-client/examples/authenticated_api.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/orderbook.rs

Fixes https://github.com/get10101/10101/issues/263.

Reconnect to orderbook WebSocket if app stream ends

---

.cargo/config.toml
.github/workflows/publish_docker.yml
coordinator/Cargo.toml
maker/.dockerignore
maker/Cargo.toml

feat: add maker docker build

---

justfile

The only problem (perhaps shared with MacOS too) is that we cannot just delete the `regtest` directory, because the `trader.sqlite` DB file lives in a common place for all networks (see https://github.com/get10101/10101/issues/277).

feat(justfile): Delete app data directory for Linux

---

coordinator/src/node.rs
coordinator/src/routes.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/ln/dlc_channel_details.rs
crates/ln-dlc-node/src/ln/mod.rs
crates/ln-dlc-node/src/node/dlc_channel.rs

Can be useful for debugging, as it is sometimes hard to figure out the state of a DLC channel by looking at the logs (or the UI 😛).

Add endpoint to get `coordinator` DLC channels

---

faucet/default.conf
faucet/lnd.conf

Note, this communication is anyways only routed internally through the nginx proxy.
This is also in alignment to be useable for the testnet vm setup. The configuration is used there as well.

chore: Disable tls on test setup

---

mobile/lib/features/trade/domain/direction.dart
mobile/lib/features/trade/position_change_notifier.dart
mobile/lib/features/trade/position_list_item.dart
mobile/lib/features/trade/trade_screen.dart
mobile/lib/main.dart
mobile/native/migrations/2023-03-20-005447_positions/down.sql
mobile/native/migrations/2023-03-20-005447_positions/up.sql
mobile/native/src/db/custom_types.rs
mobile/native/src/db/mod.rs
mobile/native/src/db/models.rs
mobile/native/src/event/api.rs
mobile/native/src/event/mod.rs
mobile/native/src/ln_dlc/node.rs
mobile/native/src/schema.rs
mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/order/mod.rs
mobile/native/src/trade/position/handler.rs
mobile/test/trade_test.dart

This is in line with our current simplified flow:
When a position is created we store it in memory.
When the position is closed we remove it. Updating (i.e. extending / reducing) a position is not implemented. 
---
Note that for closing we remove the position in user interface for now; there is no particular trade history planned, but the opening and closing of the position will be visible in the transaction history of the wallet.
Note: The PnL will only be displayed (at the moment it's constantly loading) once we have the price feed #132

feat: in memory position that can be closed in UI

---

mobile/android/app/src/main/AndroidManifest.xml

This permission is required to be able to access the internet from the 10101 app.
Note, that this permission is already added on the debug `AndroidManifest.xml`. Also this permission was also set on PoC.

chore: Add internet permission for android

---

crates/orderbook-commons/src/lib.rs
crates/orderbook-commons/src/price.rs
crates/trade/src/lib.rs
mobile/native/src/event/api.rs
mobile/native/src/event/mod.rs
mobile/native/src/orderbook.rs
mobile/native/src/trade/position/handler.rs

The orderbook can query the orders to provide the "best" orders for a given contract symbol.
I had to deal with the situation when there's no price (either bid or ask).
For the simplicity of wiring things together, I'm only piping through the BTCUSD
best prices into Flutter for now.
PR for Flutter is incoming soon (excluded from this commit, as I'm still working on that part) - in the meantime it would be good to get some feedback on this backend code.
There was a bit of complexity that I had to tackle because:
- there might be no orders for particular direction (which means there's no bid or ask price from orderbook),
- initial misunderstandings on how orderbooks work (thanks @da-kami for clarification on that).

Amend model to provide the prices from the orderbook

---

mobile/ios/Runner/Info.plist

I guess that will resolve https://github.com/get10101/10101/issues/298 as we need to call the coordinator api to create an invoice.
Unfortunately this can only be tested on a release version on TestFlight, as I presume flutter is adding that permission for a test build automatically.
Note, we had the same permission set on our PoC.

fix: Add arbitrary loads permission

---

.github/workflows/create_release.yml
.github/workflows/draft_new_release.yml
CHANGELOG.md

Mostly copied from our poc workflow and adapted to the new folder structure, just and required versions.
Note, it seems the cache is not really working. Should be looked at in a follow up PR.
Tested on my fork: https://github.com/holzeis/10101/releases/tag/0.0.1

chore: Add release workflow for android apk

---

coordinator/src/node.rs
crates/coordintator-commons/src/lib.rs
crates/trade/src/cfd.rs
mobile/native/src/calculations/mod.rs
mobile/native/src/trade/position/handler.rs

resolves #301 
This uses the pnl calculation to derive the `accept_settlement_amount`. However, since we do not have the opening price at hand, the calculation will still not be correct. For this we need to load the position from the database (which should store the opening price).

chore: Use same price for pnl and collab settlement

---

coordinator/src/bin/coordinator.rs
crates/ln-dlc-node/src/dlc_custom_signer.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/tests/just_in_time_channel.rs
crates/ln-dlc-node/src/tests/mod.rs
maker/src/bin/maker.rs
mobile/native/src/api.rs

The change also includes error handling in case the payment could not be forwarded and sets the HTLC to failed.
resolves #330

fix: Failed to create just in time channel due to disconnected peer

---

Cargo.lock
Cargo.toml

Resolves #289. 
Resolves #306.
The `rust-dlc` [branch](https://github.com/p2pderivatives/rust-dlc/pull/97) that we depend on has already been rebased onto `master`, so we can fix the bug like this.

fix: Compute payout is greater than total collateral

---

mobile/native/src/ln_dlc/node.rs

The app is accepting the dlc hence the apps collateral can be found in the `accept_collateral` attribute.

fix: Switch offer to accept collateral

---

mobile/native/src/trade/order/api.rs
mobile/native/src/trade/order/handler.rs

Just some minor cleanup
Harmonize how the order state is updated.
Initially we opted for not exposing `Rejected` because we would exit with an error in the order submission dialog; however, it is not guaranteed that the user will see this error. To keep things simple we map the internal `Rejected` state to `Failed` in the user interface, and update the order accordingly. This guarantees that the user will know that the order failed.

Harmonize order state handling

---

mobile/native/src/orderbook.rs

This would have come if the websocket stream got broken & reestablished.
After we get this message we swap all orders we had previously with new list of initial orders - and then proceed to accumulate deltas.
Closes #323

Downgrade log message when receiving list of all orders

---

crates/bdk-ldk/src/lib.rs
crates/bdk-ldk/tests/electrum.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/mod.rs

At times, we need to query Electrum; having it exposed is much more convenient instead of exposing the API part by part.

Expose Electrum blockchain in LnDlcWallet

---

.github/workflows/tests-ln-dlc-node.yml

To see what's happening if they hang forever for some reason.

Print `ln-dlc-node` slow tests logs by default on CI

---

crates/ln-dlc-node/src/node/channel_manager.rs

Fixes #299.
Fixes #308.
With the introduction of `rust-dlc` LN-DLC channels, `rust-lightning` was forked to introduce some minor changes. Among those, `rust-lightning` must now be able to consider the `glue_transaction` as the actual funding transaction in certain scenarios, whilst still considering the _original_ `funding_transaction` as the funding transaction for other scenarios.
One scenario where `rust-lightning` still expects the original `funding_transaction` is when setting up the `ChainMonitor` to watch channels on startup.
Our code was partially ported from `10101-poc`, where we did not use LN-DLC channels provided by `rust-dlc`. As such, we kept a version of the `ChainMonitor` setup which still called `get_funding_txo`, even though we are now expected to call …

Watch LN channels using original funding TXO

---

coordinator/src/lib.rs
coordinator/src/orderbook/routes.rs

An order which cannot be matched right now should transition into a failed state for now. While in the future we want to be able to notify the trader later on once there is enough liquidity.
This will prevent us from having stale orders in the frontend.

chore: orderbook returns an error if no match

---

coordinator/src/orderbook/routes.rs

when posting limit orders we do not expect a match to happen. Hence, we can return early with an Ok.

fix: we don't match limit orders

---

faucet/faucet.html

lnd is keeping a heuristic for routing attempts based on past payment attempts. This information is kept in the mission control and seems to block any subsequent payment to a node that has previously failed. If it is the very first payment that fails I guess this heuristic is even heavier opinionated.
https://docs.lightning.engineering/lightning-network-tools/lnd/payments#mission-control
In order to bypass this mission control, this change simply resets the mission control on every payment. resolves #333 
----
Note, I also tried setting setting the maximum number of payment results held on disk by mission control (`routerrpc.maxmchistory`) to 0, but without success. Other than that I found no meaningful configuration to disable lnds mission control. see also …

fix: Reset lnd mission control on send payment

---

crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs
crates/ln-dlc-node/src/tests/dlc/create.rs

The bug mentioned in the diff was fixed a while ago. We are now on a version of `rust-dlc` where `get_offered_sub_channels` is safe to call.

Use `get_offered_sub_channels` after fix in `rust-dlc`

---

crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs
crates/ln-dlc-node/src/tests/dlc/mod.rs
crates/ln-dlc-node/src/tests/mod.rs

Reproduces the error described in https://github.com/get10101/10101/issues/352
TODO: This test will be executed on our slow running tests, but should not as it is not fixed yet. However, it's valuable to a test case already written to reproduce the error.
Suggestion from @luckysori 
- Not ignore any ln-dlc-node tests by default.
- Only run ln-dlc-node tests on the special job which runs with bors (not just the slow ones).
- Ignore tests which we actually want to ignore for the time being.
Latest suggestion from @luckysori reflected in https://github.com/get10101/10101/pull/353/commits/1472ad8cc7120a92df761e54adc7c45f5bd48175:
- Expect the failure case in the test assertion.
- Run the test like any other ignored test.
- If it ever fails it means the bug has been fixed!

test: Add test reproducing the invalid commitment tx signature error

---

.github/workflows/tests-ln-dlc-node.yml

We have seen these tests hang for hours, which is wasteful and annoying as we don't get feedback fast enough unless we actively check the Actions tab.
Choosing 30 minutes as a timeout seems sensible as no successful run has ever gone over 15 minutes and most of them are much faster than that.
---
Related to #355.

Time out `run-tests-ln-dlc-node` job after 30 minutes

---

.github/workflows/deliverables-push-main.yml

Let's try this to fix our testflight pipeline
Taken from: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

fix: the called workflow needs access to our secrets

---

Cargo.lock
coordinator/src/bin/coordinator.rs
coordinator/src/node.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/node/connection.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/node/ln_channel.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/oracle_client.rs
crates/ln-dlc-node/src/node/payment_persister.rs
crates/ln-dlc-node/src/node/wallet.rs
crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/lnd.rs
crates/ln-dlc-node/src/tests/mod.rs
maker/src/bin/maker.rs
maker/src/routes.rs
mobile/native/Cargo.toml
mobile/native/migrations/2023-04-11-131120_payments/down.sql
mobile/native/migrations/2023-04-11-131120_payments/up.sql
mobile/native/src/db/custom_types.rs
mobile/native/src/db/mod.rs
mobile/native/src/db/models.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs
mobile/native/src/schema.rs

The `PaymentPersister` trait is introduced so that different consumers of `ln-dlc-node` can bring their own implementations. Alternatively, we could start moving away from `ln-dlc-node` altogether, since most of the important code differs between consumers, but that's too much work at the moment.
The app brings an implementation based on its SQLite DB. The coordinator and the maker use `ln_dlc_node::PaymentMap`, so their behaviour shouldn't change w.r.t. the previous patch.
---
~Small caveat: doesn't quite work yet, as I can't see the payment history at all. But the code shouldn't change much after the fix~. This was fixed. The problem was that we were not updating the `amount_msat` correctly, so the payments were being ignored for display purposes.

Persist payments in app's DB

---

Cargo.lock
mobile/macos/Podfile.lock
mobile/native/Cargo.toml
mobile/native/src/config/api.rs
mobile/native/src/config/mod.rs

this allows us to use domains and not just IPs.
This way we can pass in `ELECTRS_ENDPOINT=tcp://blockstream.info:110"`

chore: electrum is a url and not a socket

---

.github/workflows/deliverables-push-main.yml

When triggering a release, we get a merge commit in main which will trigger the release to production and testnet. This can fail, because each build gets a unique number, and when building at the same time, they might get the same which makes one of the two fail. To overcome this we simply ignore certain commits with the message starting with

Ignore testnet testflight for releases

---

mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/position/handler.rs

in case we are closing a position but fail at matching, we need to set the position to open again so that we can try again later.
resolves #435

chore: reset a failed position to open

---

crates/ln-dlc-node/src/node/wallet.rs

this is to be preferred as otherwise we have gaps between unused addresses

fix: get unused and not new address

---

.github/workflows/deliverables-push-main.yml

The problem seems to have been that we mixed syntax: `{}` and without brackets.

fix: if condition release latest main

---

Cargo.lock
Cargo.toml
crates/ln-dlc-node/src/tests/dlc/create.rs

Fix https://github.com/get10101/10101/issues/461.
With the version of `rust-lightning` prior to [this patch](https://github.com/p2pderivatives/rust-lightning/commit/a33cc845bc05eb0bb3e9ba8f11789ba4ed44f5b1), after opening a DLC channel we could wrongly unconfirm the LN funding transaction if it had already been confirmed.
We would look for the glue transaction on-chain, not find it and then report back to the `ChannelManager` that the _funding_ transaction was unconfirmed. This led to force-closing the LN channel unnecessarily.

Do not wrongly unconfirm funding TX

---

maker/src/trading/mod.rs

this way we should always have an order in the orderbook and don't run into no-match found errors

chore: create new order then delete old

---

mobile/lib/common/settings_screen.dart

"*.logs" is non-standard, making it harder to open it in IDE.

chore: Export 10101 app logs with '*.log' extension

---

crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/ln/mod.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/mod.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/multiple_payments.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/offline_receiver.rs

In cases the user will onboard to 10101 using another mobile app. 10101 will be closed at the time the payment is sent. Without delaying payment processing before the user opens 10101 the payment will always fail.
This is a quick fix to solve that issue, by simply waiting for 10 seconds for the 10101 receiver to come online.
Eventually we should implement some logic that is keeping 10101 online in the background for some time to cater for that scenario more nicely.
Also note, that this fix assumes that the sending party will remain online while the payment is sent.
resolves #478

feat: Delay payment for the user to open 10101

---

Cargo.lock
Cargo.toml

Fixes #310.
Fixes #399.
There was a bug in `rust-dlc` where the `per_split_secret` key was not being computed consistently across the different message handlers.

Allow open-closing many DLC channels in a row

---

coordinator/src/admin.rs
coordinator/src/routes.rs

If the coordinator restarts it does not attempt to reconnect to previously connected peers. This is a quick fix to add an admin endpoint to connect to any given peer.
1. Open channel from taker to maker.
```
curl -v -X POST -H "Content-Type: application/json" -d '{"target": { "pubkey": "025c578b8e05cd203e2a486388ed4de4e480456923192a0f288ef96c863940ce6b", "address": "127.0.0.1:19045"}, "local_balance": 300000 }' http://localhost:8000/api/admin/channels
```
2. Check if peer is connected
```
curl -X GET http://localhost:8000/api/admin/peers
curl -X GET http://localhost:8000/api/admin/is_connected/025c578b8e05cd203e2a486388ed4de4e480456923192a0f288ef96c863940ce6b
```
3. Stop the maker
4. Verify that coordinator is not connected to maker
```
curl -X GET http://localhost:8000/api/admin/peers …
```

feat: Add connect and is connected endpoints

---

coordinator/src/bin/coordinator.rs
coordinator/src/node.rs
coordinator/src/node/connection.rs
crates/ln-dlc-node/src/node/mod.rs

Fixes #490.
Fixes #492.
We want to stay connected to our public channel peers so that our channels can be usable and payments can be routed through them at all times.
This approach should work for all public channel peers who are listening on clearnet. If we want to reconnect to any peers who use Tor, we will need to use a Tor proxy (see this [sample repo](https://github.com/TonyGiorgio/ldk-sample-tor)).
---
This work is untested. I propose to test this in production (!) and see if we can keep these connections alive. Alternatively we might be able to quickly set up something locally. But I think there is almost no risk in testing this in production anyway.

Keep coordinator connected to public channel peers

---

crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/ln/mod.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/lnd.rs

We noticed that the coordinator is very chatty, which might be a reason that counterparty do not respond as fast as possible on pings.
Worst, this only reducing the network noise.

fix: Announce node only on channel creation and startup

---

coordinator/src/bin/coordinator.rs
coordinator/src/cli.rs
maker/src/bin/maker.rs
maker/src/cli.rs

As usual, use `--json` to enable JSON output.
Turns out that we copied the functionality from ItchySats long time ago, we just
never exposed it.

feat: Add json logging option for coordinator and maker

---

coordinator/src/admin.rs
coordinator/src/routes.rs

We cannot query the endpoint at the moment. The server automatically reports a 404.

Re-enable list-DLC-channels endpoint on coordinator

---

crates/bdk-ldk/src/lib.rs
mobile/native/src/db/models.rs

Override Display trait of newly constructed `thiserror` errors to print out the
underlying error by default.

fix: Properly print out errors converted into `thiserror`

---

mobile/ios/Runner/Info.plist

This should allow us to browse the 10101 application files on the phone using the iOS Files app.
This is helpful to 1) create a backup of your phones data and 2) to copy the the app directory for local debugging.
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW20

chore: enable file sharing

---

Cargo.toml

We already kept in sync with `p2pderivatives` one, but kept pointing to the
wrong one.

Use our fork of `rust-lightning`

---

crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/ln/mod.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/peer_manager.rs
crates/ln-dlc-node/src/tests/lnd.rs
crates/ln-dlc-node/src/tests/onboard_from_lnd.rs

This reverts commit 53c0de1573c20067f147929e4f228fa2924919f6.
In an attempt to fix our connection issues, we reduced the node announcements to only when the `ChannelReady` event has been processed as a comment on the ldk-sample suggested that shouldn't be done in repeating task.
However, after asking the question on discord I got the answer that it should be fine to make node announcements in an interval. A more sensible delay of 600 instead of 60 seconds has been suggested, though. 
https://discord.com/channels/915026692102316113/978829624635195422/1100452596726116383
I am proposing to revert this change as it has not been properly tested and I am afraid we might run into regressions.

Revert "fix: Announce node only on channel creation and startup"

---

mobile/lib/main.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

This allows for more flexibility, e.g. store app data in a different location
from the app seed.
This PR does not immediately use this feature, defaulting to the same directory.

feat(mobile): Decouple application data and seed locations

---

mobile/lib/features/welcome/welcome_screen.dart

Don't store email address in preferences if we somehow could not register (e.g.
backend was not started properly).

fix(mobile): Only store email address in preferences after successful registration

---

.github/workflows/tests-ln-dlc-node.yml
crates/bdk-ldk/src/lib.rs
crates/ln-dlc-node/src/ln/config.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/channel_close.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/mod.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/multiple_payments.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/offline_receiver.rs

Turns out the relevant configuration is `our_to_self_delay` and not `their_to_self_delay`. The later only specifies the amount of blocks we are at max willing to wait for claim funds after a force closed channel. `our_to_self_delay` is eventually the configuration we are using in case we are opening the channel. We used the default value of 144 blocks which is about 24 hours. I think this value is reasonable, but could be decreased even more for our just in time channels.
This PR pulls this config to 10101 and sets it to the default value of 144. So nothing changes here. I also added a test to ensure that force closing is actually working. Additionally I added a collaborative channel closure tests, which shows that the user has to wait for 6 blocks to receive the …

chore: Add test for claiming funds of a closed channel

---

coordinator/src/logger.rs

This is so that we can debug the effect of future code changes on the frequency of lost connections due to ping timeout.

Log LDK pings

---

coordinator/src/bin/coordinator.rs
crates/ln-dlc-node/examples/fund.rs
crates/ln-dlc-node/src/node/mod.rs

Unblocks quick testing locally, which got broken recently when we changed values to solve production issues.

Change intervals for regtest

---

Cargo.lock
coordinator/Cargo.toml
crates/bdk-ldk/Cargo.toml
crates/coordinator-commons/Cargo.toml
crates/ln-dlc-node/Cargo.toml
crates/trade/Cargo.toml
maker/Cargo.toml
mobile/native/Cargo.toml

There's no blocking dependencies for bdk 0.28 either, but I would hold off with
that until we bump rust-lightning to 0.1.114 (e.g. to have matching
esplora-client versions).
a bit more context: this is done for the upcoming #545

Bump bdk to 0.27.1

---

mobile/ios/Podfile.lock
mobile/lib/main.dart
mobile/native/src/ln_dlc/mod.rs

On iOS the ApplicationSupportDirectory is never exposed to the user and can not be backed up. Contrary the ApplicationDocumentsDirectory is user generated data, that can be backed up. I think this still not perfect as we have both kinds of data, but being able to access the data dir on the phone has IMHO several benefits. Especially during the beta phase.
This however, will be a breaking change, as the data dir folder will change. If we want that, we should get this in before the first beta users get to test the app.

chore: Change data directory on phone

---

coordinator/src/bin/coordinator.rs
coordinator/src/cli.rs
coordinator/src/routes.rs
crates/bdk-ldk/src/lib.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/ln-dlc-node/src/tests/onboard_from_lnd.rs
crates/orderbook-commons/src/lib.rs
mobile/native/src/ln_dlc/mod.rs

So far we had it at 2% which was a hurdle for users. 
Pushing it down to 0.5% will be expensive for us in the long run, hence, this is just a temporarily solution until we go for point 2 in #577 .

Set JIT funding rate to 0.5% and make it configurable from the coordinator

---

.github/workflows/tests-ln-dlc-node.yml

I think we can remove the `-j 1` flag, because I introduced it to achieve the same thing and it clearly wasn't working.
We must go down to `--test-threads=1` if we want to ensure that no two tests are run in parallel. Running tests in parallel at all seems to pretty consistently cause either test failures or non-terminating tests. Perhaps this change might fix
https://github.com/get10101/10101/issues/355.
---
This change will obviously slow down CI, but I don't have any better ideas at this stage.

Run `ln-dlc-node` tests sequentially on CI

---

coordinator/src/routes.rs
mobile/native/src/ln_dlc/mod.rs

Rename `fake_scid` V2 endpoint

---

mobile/lib/main.dart
mobile/native/src/api.rs

Use a dedicated wrapper that instead of using a Result (that gets converted to
an exception), panics, triggering a crash report with a backtrace.

feat(mobile): Panic if backend cannot be initialised

---

mobile/lib/common/modal_bottom_sheet_info.dart
mobile/lib/common/settings_screen.dart
mobile/lib/features/trade/trade_screen.dart
mobile/lib/features/trade/trade_theme.dart
mobile/lib/features/welcome/welcome_screen.dart

Continue roll-out of our brand colours for added consistency.
Note: Info button uses a lighter shade of the same colour.

chore: Use brand colours on trading screen

---

mobile/lib/main.dart

This is a critical fix as we would otherwise break existing installations. 1.0.17 is broken and must not be release to the users.
We are using mainnet as argument and map it eventually to bitcoin to be used as subdir for the data dir. We need this mapping on the frontend as well to check if the data dir has already been initialised as we would otherwise break a previous installation.

fix: Map network mainnet to bitcoin

---

mobile/lib/util/preferences.dart

Feedback from a user, who confirmed the backup, but didn't create a backup. An easy quick fix that will help our users.
resolves #602

feat: Keep backup button always visible

---

crates/ln-dlc-node/src/dlc_custom_signer.rs
crates/ln-dlc-node/src/ln/config.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/wallet.rs
crates/ln-dlc-node/src/tests/bitcoind.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/channel_close.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/mod.rs
crates/ln-dlc-node/src/tests/mod.rs

Before, the collab close transaction paid to an address owned by LDK, which had to be confirmed and then spent to the on-chain wallet.
After overriding `get_shutdown_scriptpubkey`, the close transaction pays directly to the on-chain wallet. This means that there is no risk of losing funds as soon as the close transaction is on-chain if we remember the seed, whereas before we could lose funds whilst waiting for the "claim transaction".
The effect of overriding `get_destination_script` to point to an on-chain wallet address is less clear to me, because the commitment transaction must still be processed by LDK to produce a `SpendableOutputs` event with a `SpendableOutputDescriptor::DelayedPaymentOutput` which can then be spent to an on-chain wallet address (after waiting for the …

Use on-chain address for shutdown and destination

---

justfile
mobile/lib/features/wallet/share_invoice_screen.dart

- The button is not visible outside regtest.
- The button by default points to our remote faucet, and `just run` overrides it with local faucet.
- The request is done in Dart, I didn't want to pollute our library with non-production code.
https://github.com/get10101/10101/assets/8319440/bdec0603-ea9d-44a7-a93d-94839ca6f543

Add funding button on regtest

---

Cargo.lock
Cargo.toml

This ensures that we are on latest[^1] `rust-dlc#ln-dlc-channels` (and consequently latest `rust-lightning#split-tx-experiment`).
[^1]: Plus two patches that haven't been upstreamed yet.

Update `rust-dlc` dependency

---

mobile/lib/common/snack_bar.dart
mobile/lib/features/wallet/share_invoice_screen.dart

- Add a Snackbar that displays an error if the invoice could not be paid.
- Interface only goes back to the main screen if the payment worked.
- Prevent any possibility of calling the request twice by disabling the button
during a call.
This changeset also showcases how to disable a button from being able to invoke an action
repeatedly (useful when we want to prohibit this), bu using a simple boolean
flag that overwrites the `onPressed` handler.
This PR addresses the issues spotted by @holzeis and @luckysori during the previous review.

feat: Improve UX over funding with remote faucet

---

Cargo.lock
Cargo.toml

See https://github.com/p2pderivatives/rust-lightning/commit/15d48d8243e05fbd198215c6a3a762d2bdc9f38b.

Prevent panic by updating `rust-dlc` and `rust-lightning`

---

crates/ln-dlc-node/examples/fund.rs

It would be more correct to parse the error string to identify which errors can be ignored (such as the already-connected error), but at least this change makes `just fund` and `just fund-regtest` more usable.

Allow `just fund` to continue even if LND and coordinator are already connected

---

mobile/lib/features/wallet/share_invoice_screen.dart

Faucet payment can fail in more ways than just faucet being unreachable.
Parse the response for `payment_error` phrase and count it as an error.
For simplicity, print the whole response in such cases.

fix: Improve faucet invoice payment error handling

---

coordinator/src/admin.rs
coordinator/src/routes.rs
crates/ln-dlc-node/src/node/mod.rs
mobile/lib/features/wallet/share_invoice_screen.dart
mobile/native/src/api.rs

Fixes #633.
This is to ensure that we have a more reliable way to open a channel between coordinator and app on regtest.
The user still clicks on the newly introduced `Pay the invoice with 10101 faucet` button, but under the hood we just open a channel directly and push 100k sats to the app. We could try to read what the user asked for when creating the invoice, but that's more involved and we just wanted a simple fix.

More reliable `pay-invoice-with-10101-faucet` button

---

justfile

Now that we open the channel directly to the coordinator, we started relying on
this variable to be set correctly at startup.

fix: Add coordinator host to `just run-regtest`

---

mobile/lib/features/wallet/share_invoice_screen.dart
mobile/native/src/api.rs

Because:
- The app is already keeping a connection with the coordinator alive.
- Establishing a connection from the coordinator to the app is really hard.

Do not establish connection to app when opening channel

---

justfile
mobile/lib/features/wallet/share_invoice_screen.dart

The host can be correctly fetched from the config. It implies the host either from the `coordinator_p2p_endpoint` or if not set the `coordinator_host`.
This fix is only needed as the `build-ipa` target was incorrect. We could have alternatively also only added the `coordinator_host` argument, but I think its cleaner to not touch the environment variables outside of the environment file and fetch the configs only from the config service.

fix: fetch coordinator host from config

---

.github/workflows/ios.yml
justfile

Just specifying `--release` for cargo-lipo is not enough, we still need to
copy the library from the correct path 🙈

fix: Copy rust library for iOS from the correct path

---

mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_screen.dart

Allow spreading the message of self-custodial message when order got submitted.
msg: (for closed we substitute with "closed):
>        Just opened a #selfcustodial position using #DLC with @get10101 🚀. The future of decentralised finance starts now! #TenTenOne #10101 #BTC
screenshot of button:
resolves #599

feat: Share on Twitter

---

Cargo.lock
Cargo.toml
coordinator/src/admin.rs
coordinator/src/routes.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/ln_channel.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/dlc/non_collaborative_settlement.rs
crates/ln-dlc-node/src/tests/mod.rs

Fixes part of https://github.com/get10101/10101/issues/591.
This patch finally adds a `force_close_ln_dlc_channel` test, which verifies that the party effecting the force-close of the LN-DLC
channel can get their coins back if they:
- Manually call `force_close_channel`, publishing the split transaction.
- Wait for 288 confirmations on the split transaction.
- Manually call `finalize_force_close_ln_dlc_channel`, publishing the buffer, glue and commitment transactions.
- Wait for 144 confirmations on the commitment transaction, so that the delayed output on it becomes spendable.
- Wait for a further 144 confirmations, so that the CET can spend from the buffer transaction.
For the time being only the coordinator is able to force-close a channel by first using the DELETE …

Implement force-close of LN-DLC channel

---

mobile/lib/features/wallet/create_invoice_screen.dart

This way we can prevent errors like:
"Cannot accept value that would put our exposure to dust HTLCs"
We plan to revert this commit when we support anchor outputs.

chore: Set the minimum invoice size to 50k sats.

---

coordinator/src/bin/coordinator.rs
coordinator/src/node.rs
coordinator/src/routes.rs
coordinator/src/settings.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/mod.rs
mobile/native/src/ln_dlc/mod.rs

Add more settings to our coordinator settings API, which is changeable at
runtime via a REST endpoint, and also stored in `coordinator-settings.toml`
file.
This also decouples the app and coordinator sync settings (although they remain
the same by default).

Dynamically adjust esplora-related intervals in the coordinator

---

mobile/pubspec.lock
mobile/pubspec.yaml

Somehow `just lint` was failing locally on my machine due to uuid problem.
Specifying it explicitly.

chore: Fix flutter dependency

---

mobile/native/src/db/custom_types.rs
mobile/native/src/db/mod.rs
mobile/native/src/db/models.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/order/mod.rs

fixes https://github.com/get10101/10101/issues/670 (likely, unless there is some other problem that I don't understand yet...)
If an order remains `Open` for more than `5` minutes we don't expect it to ever get matched. We have a task that runs one per minute to load the orders that are `Open` and determine if the order's creation timestamp is older than `5`minutes; if so we fail the order.

Fail outdated orders

---

crates/ln-dlc-node/src/node/mod.rs

This should substantially reduce the wait time for initial and subsequent sync, improving the app experience.
We had 8 previously, but 4 is the default value in esplora client, so should be
safe to use.
Note: our coordinator can be configured independently now, without neededing to
release a new version.

fix: Change the default concurrency in BDK wallet

---

Cargo.lock
Cargo.toml

We have to ensure that users that have an position that is currently `Open` delete this position.
The only way to achieve this is to reset the app, i.e. uninstall and reinstall. 
Otherwise, when a user triggers the position close, the coordinator will not know that it is a close (because the position is not loaded on the coordinator) - and it will result in the coordinator opening a new position with the app which results in weird state discrepancy between the two.

Patch to version where we skip unreadable contracts / sub-channels

---

docker-compose.yml

I noticed that we didn't configure electrs proper whilst fixing cloud-conf
electrs container.
Inspired by:
https://github.com/romanz/electrs/blob/master/doc/install.md#docker-based-installation-from-source
and the CLI help (`electrs --help`):
```
--daemon-dir <daemon_dir>                    Data directory of Bitcoind (default: ~/.bitcoin/)
--db-dir <db_dir>                            Directory to store index database (default: ./db/)
```
Note: We shouldn't need to write to bitcoin data, it's just for reading, so it's
mounted read-only.

chore: Configure electrs containers

---

crates/ln-dlc-node/src/ldk_node_wallet.rs

In case using `tracing` inside `block_in_place` closures does not work.

Move failed-to-broadcast error outside of block-in-place

---

Cargo.lock
Cargo.toml
coordinator/src/logger.rs
mobile/native/src/logger.rs

We update our `rust-lightning` dependencies to be able to keep seeing peer disconnects (which have been promoted to debug).

Do not log LN `peer_handler` ping and pong messages

---

Cargo.lock
Cargo.toml

There was a regression in our dependencies that effectively reverted https://github.com/get10101/10101/pull/626.
We encounter this panic sometimes at the moment, so this should help.

Update `rust-dlc` and `rust-lightning` to prevent a panic

---

coordinator/src/node.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/ln_channel.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs
mobile/native/src/ln_dlc/mod.rs

This is done to mitigate risks such as starving other async tasks and even deadlocks.

Spawn expensive blocking `rust-dlc` code on blocking threads

---

Cargo.lock
Cargo.toml
crates/ln-dlc-node/src/node/sub_channel_manager.rs

The update reverts a couple of patches in `rust-dlc` and `rust-lightning` which may have introduced a deadlock.
---
After this patch we will be building on top of `get10101/rust-dlc#fix/deadlock` and `get10101/rust-lightning#split-tx-experiment-114-without-lock`.

Attempt to fix deadlock by updating dependencies

---

.gitignore
Cargo.lock
coordinator/Cargo.toml
coordinator/src/admin.rs
coordinator/src/bin/coordinator.rs
coordinator/src/routes.rs
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/ldk_node_wallet.rs
justfile
services/prometheus/prometheus.yml

Add support for easily collecting prometheus metrics and sprinkle some
`#[autometrics]` into a few functions, e.g. routes, and wallet sync.
For more information, see: https://github.com/autometrics-dev/autometrics-rs
Prometheus metrics are exposed at `/metrics` endpoint.
Add a `just prometheus` command, which starts prometheus configured to gather
the metrics for local debugging
(prometheus needs to be installed locally, e.g. with `brew install prometheus`).
Note: Local debugging works best with `rust-analyzer`, as docstrings are
automatically decorated with links to prometheus queries related to the function.
Production config can pull these metrics into Grafana dashboards provided by autometrics.

Add support for autometrics in coordinator

---

crates/ln-dlc-node/src/node/mod.rs

We copied the code that uses `new_current_thread` from LDK wallet. In my understanding we need this because `SledTree` does not implement `Send`, so we need a non-send thread.
However, the tokio documentation states that one should use `LocalSet` when using `new_current_thread` - which is not done in the code copied over from `ldk-node`.
The tokio docs further state that one can use `new_multi_thread` when having the `rt-multi-thread` feature activated - which we have.
See docs: https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.new_current_thread
Note: I am not 100% sure this will change any assumptions; this code is generally weird - we copied it without questioning it too much.

Change `sync` to use a multi-threaded runtime builder

---

coordinator/build.rs

build.rs allows us to specify which prometheus server we're using when analysing
functions in IDEs.

chore: Allow querying regtest metrics directly from IDE

---

.cargo/config.toml

This ensures that we don't have to recompile from scratch every time we switch between `cargo build` and `cargo clippy`.

Add `--cfg tokio_unstable` to Clippy target

---

justfile
mobile/android/app/build.gradle

A simple way to run the app on the phone but connect to a local (any) coordinator via IP.
---
This command makes it easy to quickly change to another machine that runs the setup, assuming the default ports and the checked in coordinator seed.
I am not sure if we want to do anything with this, but it made me think about our configuration in general.
At least for the (local) regtest setup the only thing that usually changes is the host machine's IP, maybe we can simplify the configuration to extract the IP and only set that instead of all the other parameters.
---
Note: I only configured the `local` flavor for Android - if we want to keep this command we could consider adding a flavor iOS as well.

Run command with local flavor and configurable IP addr

---

Cargo.lock
coordinator/src/node.rs
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/fee_rate_estimator.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/channel_manager.rs
crates/ln-dlc-node/src/node/dlc_manager.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/sub_channel_manager.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs

It is sufficient to use an asynchronous task, as the work we're doing here is primarily IO-bound: requesting the latest fee rate from using the `esplora` client.

Do not spawn new OS thread just for updating fee estimates

---

Cargo.lock
Cargo.toml

Whilst an important quickfix at the time (it allowed us to resume testing on
mainnet), our fork introduced more side-effects than it fixed.
Some of the side-effects observed:
- bdk wallet sync would take ~15s (instead of ~1-2s)
- ln_collab_close` test was failing
- lightning wallet sync took only 3ms to complete (instead ~1000ms normally)
Fixes #717

fix: Stop using bdk fork that introduced 250ms delay

---

Cargo.lock
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/ldk_node_wallet.rs

Only added for testing, drop this commit once done with debugging.

chore: Add backtrace logging to debug tasks trying to acquire the bdk lock

---

Cargo.lock
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/ldk_node_wallet.rs

This reverts commit 3e826edb8bbf860e41baa5a0d678e1594b8070f7.

Revert "chore: Added backtrace logging to debug tasks trying to acquire the bdk lock"

---

rust-toolchain.toml

Ensure all builds for contributors and releases are done with the same rustc
version.
This also allows us to better reuse rust-cache on CI (only change the compiler
version when we want/need, not immediately when it's released).

chore: Pin rust version to latest stable

---

Cargo.lock
Cargo.toml
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/node/mod.rs

I had to backport a few fixes that are only in version 0.0.115 of `rust-lightning`, hence the upgraded `rust-lightning` dependency.

Process lightning events asynchronously

---

Cargo.lock
Cargo.toml

Very stupid logs that apply to the coordinator side of closing a DLC channel.
See https://github.com/get10101/rust-dlc/commit/37a9265.

Update `rust-dlc` to add even more logs

---

Cargo.lock
coordinator/Cargo.toml
coordinator/src/bin/coordinator.rs
coordinator/src/cli.rs

An opt-in flag that shows the current tokio metrics, printed every 1s.
Can be helpful be used when debugging issues with the runtime.
I didn't bother integrating it with Prometheus exporter for now.

chore: Add crude tokio metrics support

---

Cargo.lock
Cargo.toml
crates/ln-dlc-node/src/node/sub_channel_manager.rs

This update should only remove the functionality related to https://github.com/get10101/rust-dlc/commit/d7c1ec5 and https://github.com/get10101/rust-lightning/commit/cb1c096e.
This should ideally be a temporary revert. We at least want to verify that this helps with https://github.com/get10101/10101/issues/692.

Revert channel lock patch on `rust-dlc` again

---

coordinator/src/bin/coordinator.rs
coordinator/src/cli.rs

Instead of a boolean flag, turn the feature on when specifying print interval.
This prevents log spam and is more flexible.

chore: Allow specifying interval for tokio metrics

---

crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs

We somehow forgot to assert on the value returned by the `matches!` macro :facepalm:

Actually assert on DLC channel state in tests

---

crates/ln-dlc-node/src/node/mod.rs

From the `parking_lot` documentation it looks like we need to add something like this to know what deadlocks have been detected.

Add background task to report deadlocks

---

.cargo/config.toml
crates/ln-dlc-node/src/node/payment_persister.rs
rust-toolchain.toml

We are temporarily activating this by default to investigate a deadlock.
We have to use a `nightly` toolchain to be able to use this flag.

Build `rust-lightning` with `backtrace` flag

---

Cargo.lock
Cargo.toml
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/examples/fund.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/load.rs
crates/ln-dlc-node/src/tests/load/coordinator.rs
crates/ln-dlc-node/src/tests/mod.rs

The motivation to add this test is to check that a hosted coordinator is able to trade repeatedly with an app. In this case we simply
simulate the app rather than using the `mobile/native` crate.
Notably, we have to interact with the coordinator's HTTP API. To do so we have to pretend like we got a match from the orderbook. We could involve the orderbook too, but it isn't strictly necessary at this stage.
The test in its current state is much slower than it needs to be. We should work towards replacing the hard-coded sleeps with calls to `wait_until`, wherever possible.
We've added a `load_tests` flag because we probably should refrain from running this type of test as frequently as the rest of the
`ln-dlc-node` tests. Currently it relies on the public regtest `coordinator` being up an …

Add coordinator load test via `ln-dlc-node`

---

CHANGELOG.md
mobile/pubspec.yaml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/5242436099.
I've bumped the versions in the manifest files in this commit: d983a8af8076410cc3b366329c3e2c7ae731e114.

Release version 1.0.19

---

Cargo.lock
Cargo.toml
coordinator/src/admin.rs
coordinator/src/routes.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/ln_channel.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/sub_channel_manager.rs
crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs
crates/ln-dlc-node/src/tests/dlc/non_collaborative_settlement.rs
crates/ln-dlc-node/src/tests/load.rs
crates/ln-dlc-node/src/tests/mod.rs

Fixes https://github.com/get10101/10101/issues/766 (they pass locally :D).
Fixes https://github.com/get10101/10101/issues/768.
Fixes https://github.com/get10101/10101/issues/664.
Fixes https://github.com/get10101/10101/issues/663 (we don't run into it and the app gets their money back [^1]).
The main motivation is to stay on top of the latest changes to `rust-lightning` and `rust-dlc`, whilst also definitively removing some of the things that we temporarily added during our latest bug hunt.
Some patches were also removed which might cause some controversy:
- https://github.com/get10101/rust-dlc/commit/ce78c25.
- https://github.com/get10101/rust-dlc/commit/cf3d1eb.
- https://github.com/get10101/rust-dlc/commit/304e85d.
In general reviewers are encouraged to take a look at the differences …

Stabilise key dependencies

---

crates/ln-dlc-node/src/fee_rate_estimator.rs

Fixes #778.
As opposed to 12 blocks.
This is an attempt to reduce the likelihood that LDK force-closes one of our channels because it deems that the counterparty's updated fee rate is too low. By using 24 blocks as the confirmation target we indicate that very low fees should be acceptable.

Set background transaction priority to 24 blocks

---

coordinator/src/routes.rs
crates/ln-dlc-node/src/dlc_custom_signer.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/wallet.rs
crates/ln-dlc-node/src/tests/mod.rs
maker/src/routes.rs
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

Fixes #776.
By caching these addresses we are preventing situations where getting an address from the wallet takes a long time because the on-chain sync is ongoing (and therefore has the mutex write lock).
The downside is that we can end up reusing addresses if these caches are accessed more than once during a sync.

Use address caches in `LnDlcWallet`

---

coordinator/src/routes.rs
crates/ln-dlc-node/src/dlc_custom_signer.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/wallet.rs
crates/ln-dlc-node/src/tests/mod.rs
maker/src/routes.rs
mobile/lib/features/wallet/application/wallet_service.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

AFAIK generating a new address means that the on-chain wallet must look for that address on the blockchain. Thus, we must only generate a new address if we are sure that we are about to use it.
As such, it is a bad idea to generate new addresses periodically. This would quickly become untenable, as the on-chain sync would grow more and more expensive and slow without good reason.
At the same time, it is best to use new addresses as it ensures that we don't run into address reuse, which is a bad practice as it leads to much worse privacy on-chain. Unfortunately, due to current limitations of `bdk::Wallet` it is not possible to ask the wallet for a new  (or even an unused) address during the on-chain sync. For this reasons we decided to introduce an address cache.
Given all this, it's bad …

Prefer unused addresses to new ones (temporarily)

---

Cargo.toml

This reverts commit d2202fb469233bc585b5a0c7a8a8bc1eb1a0419b.
The fix was causing certain tests to fail, so it's probably not safe to use.

Revert "fix: Fix error-prone periodic checks"

---

.gitignore
data/maker/.gitkeep

When setting up the project for the first time in a while, the only issue I came across was that the `run-maker-detached` recipe would try to redirect its logs to `data/maker/regtest.log`, but `data/maker` did not exist. This PR adds a placeholder file .gitkeep to that directory to keep it around, as directories cannot be checked in to git empty.
cc @holzeis since we discussed this on element

Add .gitkeep to data/maker so that run-detached-maker works properly

---

crates/ln-dlc-node/src/ln/event_handler.rs

Otherwise we return an error that is subsequently logged.

Return early if there are no spendable outputs when handling `SpendableOutputs` event

---

maker/src/bin/maker.rs
maker/src/cli.rs
maker/src/trading/bitmex_client.rs
maker/src/trading/mod.rs
maker/src/trading/orderbook_client.rs

Maker creates multiple *same* orders based on the latest BitMEX quote.
Their amount is configurable.
When a new quote is received, all orders are updated.

Allow concurrent orders in maker

---

coordinator/src/logger.rs
mobile/native/src/logger.rs

Logging with trace on the app might impact mobile storage; we hope to be able to
revert this change before the next TestFlight release.

chore: Log LDK logs on TRACE

---

mobile/lib/features/wallet/share_invoice_screen.dart

We used this to circumvent the random channel closures / no route errors on
regtest during 10101-test app testing.
Now that the testing is back on mainnet and we focus on stability of the app,
the underlying issues should be tackled properly and this workaround removed.

chore: Remove direct channel open workaround for public regtest

---

.github/workflows/close-stale-issues.yml

Issues and PRs without activity will be marked as stale after 30 days, and
closed if the label has not been removed (or any other action happened, such as
comment etc.) after 5 more days.

chore: Close stale issues after defined period of inactivity

---

mobile/lib/features/welcome/welcome_screen.dart

Previously, this text was right aligned, which looks weird.
Before this change:
After this change:
Left alignment could also make sense though.

Center email request prompt

---

mobile/lib/features/trade/application/order_service.dart
mobile/lib/features/trade/order_submission_status_dialog.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/trade/trade_screen.dart
mobile/lib/main.dart
mobile/native/src/api.rs
mobile/native/src/trade/order/handler.rs

Share is shown after it is filled, fixing #714.
While order is filling (hard to see but that's a loading spinner on top):
Once order has been filled successfully:

Encourage user not to close the app while order is being processed

---

crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/dlc/non_collaborative_settlement.rs

It's probably not super important since we're moving away from these hopefully soon, but I arrived at this when working on trying to reproduce #792.
The main motivation is to ensure that `create_dlc_channel` and `dlc_collaborative_settlement` can be called without setting up nodes every time. This means that they are more easily composable.
The only downside is that we introduce a bit of repetition when setting up nodes plus the channel between them, but that could be mitigated by introducing another helper function.

Refactor DLC tests

---

coordinator/src/routes.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs
crates/ln-dlc-node/src/tests/dlc/non_collaborative_settlement.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/channel_close.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/multiple_payments.rs
crates/ln-dlc-node/src/tests/lnd.rs
crates/ln-dlc-node/src/tests/load.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/ln-dlc-node/src/tests/multi_hop_payment.rs
crates/ln-dlc-node/src/tests/onboard_from_lnd.rs
crates/ln-dlc-node/src/tests/single_hop_payment.rs
mobile/native/src/ln_dlc/mod.rs

One patch addresses production and the other addresses the tests.
~This could help with #807, but I'm not convinced. [edit]: Indeed it did not help, the same test still hangs on this very PR~.

Do not block `tokio` runtime when syncing on-chain

---

crates/ln-dlc-node/src/fee_rate_estimator.rs

We recently saw another one in production after increasing the background confirmation target from 12 to 24.

Do more to prevent fee-rate-disagreement force-closures

---

Cargo.lock
Cargo.toml

This bumps our `rust-dlc` dependency to include https://github.com/get10101/rust-dlc/commit/11c746fc55d6a7a95f17bce61d4989a48454d581
Although it does not fix #792, it does recover incomplete dlc state on the coordinator upon restart. Allowing the user to continue trading.
This will at least mitigate the impact of bug #792.

chore: Bump rust-dlc dependency

---

Cargo.lock
coordinator/src/bin/coordinator.rs
coordinator/src/node.rs
coordinator/src/node/connection.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/storage.rs
crates/ln-dlc-node/src/node/wallet.rs
crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/lnd.rs
crates/ln-dlc-node/src/tests/load.rs
crates/ln-dlc-node/src/tests/load/coordinator.rs
crates/ln-dlc-node/src/tests/mod.rs
maker/src/routes.rs
mobile/native/Cargo.toml
mobile/native/migrations/2023-06-27-031253_spendable_outputs/down.sql
mobile/native/migrations/2023-06-27-031253_spendable_outputs/up.sql
mobile/native/src/db/mod.rs
mobile/native/src/db/models.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs
mobile/native/src/schema.rs

Fixes #844.
This ensures that claiming funds from LN commitment transactions can be retried as much as we need to.
Currently, only the app persists this across restarts. The coordinator still uses an in-memory map, like it does for payments. We still need to fix this.
---
Related to https://github.com/get10101/10101/issues/798.
Next steps captured in #845 and #846.

Persist spendable output descriptors generated by LDK in app

---

.github/workflows/ci.yml
justfile

First run will probably take ages because of lack of cache.
Will closely monitor and optimise onwards.
I'm trying to remove the flutter dependency.

Enable end-to-end tests on CI

---

Cargo.lock
Cargo.toml

Fixes #837.
We are still pretty far away from replacing these git dependencies.
Currently we point to our own branches in the `p2pderivatives` repos: `feature/ln-dlc-channels-10101` and `split-tx-experiment-10101`. These are based on `feature/ln-dlc-channels` and `split-tx-experiment` respectively.
They diverge slightly at the moment for convenience and they will inevitably diverge slightly once in a while in the future. This is because we cannot expect a library such as `rust-dlc` to accept changes at the same rate as a product such as 10101 might need.

Move our `rust-{dlc, lightning}` branches to `p2pderivatives`

---

Cargo.lock
Cargo.toml
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs

Fixes a bug very similar to #792. But happening during processing an outdated `Confirm` and `CloseConfirm` message. However, the bug reported with #792 fails on processing `CloseFinalize` message.
By using the dlc message handler as onion message handler we can hook into the `peer_disconnected event` and clear and pending unprocessed received `Confirm` and `CloseConfirm` messages from the disconnected peer.
See also fix in `rust-dlc` https://github.com/p2pderivatives/rust-dlc/commit/51c3c3fc4c9f468a0aa31f51a73f87149697be50

Fix: failed to close position got revoke commitment secret not matching their current pubkey

---

CHANGELOG.md
mobile/lib/features/wallet/create_invoice_screen.dart

- **Remove stop-gap on receiving payment with open position**: It seems a change in the past fixed that issue implicitly. Probably upgrading to ldk 114. Anyhow, I tested receiving a payment from the faucet and it worked just fine.
- **Remove constraint on min amount**: Receiving min 50k sats was an arbitrary amount and did at most only mitigate the chances of preventing https://github.com/get10101/10101/issues/580. Given that the current mempool situation does not ask for this constraint anymore, we returning to the original min amount.
fixes #498

fix: app cannot receive payment with open position

---

coordinator/src/node.rs
coordinator/src/settings.rs
crates/ln-dlc-node/src/fee_rate_estimator.rs
crates/ln-dlc-node/src/lib.rs

The fallbacks were only ever used if we could never get an answer from the fee rate server. As such, it didn't make sense for them to be configurable at runtime.
We move them to reduce complexity and because there is minimal benefit in being able to configure values that will very rarely be used.

Replace fee rate fallbacks in settings with constant

---

mobile/lib/common/app_bar_wrapper.dart
mobile/lib/features/wallet/seed_screen.dart
mobile/lib/features/wallet/wallet_screen.dart
mobile/lib/util/preferences.dart
mobile/pubspec.lock
mobile/pubspec.yaml

Fix #404.
This was caused by calling `isUserSeedBackupConfirmed` (the future passed to `FutureBuilder`) in `State<WalletScreen>.build`, something that the docs explicitly say we must not do.
As recommended, we call it in `State<WalletScreen>.initState`. This means that the `WalletScreen` is no longer informed about the updated value after confirming that the seed has been backed up.
The simplest way to know is to return a value after `pop`ping (returning from) the `SeedScreen`. This functionality is
only available in a later version of `go_router` so we update the dependency to the latest version. With the returned value we can
update the dependency of `isUserSeedBackupConfirmed`.
Finally, we move the responsibility of keeping the button always visible to the place where we actually …

Fix constant flickering on app's wallet screen

---

CHANGELOG.md
mobile/lib/features/wallet/create_invoice_screen.dart

Fixes https://github.com/get10101/10101/issues/688
The `GestureDetector` records taps within the `SafeArea` of the screen. Setting the `FocusScope` to an unused `FocusNode` removes the focus from the `TextField`. `behavior: HitTestBehavior.opaque,` allows clicking in "empty" parts of the screen; otherwise the focus would only be take away from the `TextField` when e.g. clicking on other text.
This method should work no matter what - in case the screen becomes so full that the text pushes the button out even without the keyboard we would have to make it scrollable. For now I think this is the better solution.
Note that I was not able to reproduce this issue by "just" using larger and bold font through Accessibility settings, so I simulated it by adding dummy text.

Defocus textfield upon clicking anywhere on screen

---

mobile/lib/common/dummy_values.dart
mobile/lib/features/trade/application/position_service.dart
mobile/lib/features/trade/application/trade_values_service.dart
mobile/lib/features/trade/domain/price.dart
mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/position_change_notifier.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_value_change_notifier.dart

Once introduced for expedience, they started confusing the beta users.
TradeValues allows nullable values for parameters that are taken from the coordinator.
Checks are inserted in place before each `!` defererence (Dart 2 unfortunately
does not detect all not-nullable values properly.).
when coordinator is off at startup - the order cannot be placed because we don't have the counterparty margin:
(note: it would be great if we had a higher-level API check from the backend + a notifier in Dart about coordinator status).

fix(ui): Remove dummy initial price values from the GUI

---

.github/workflows/build-release-binaries.yml
.github/workflows/ci.yml
crates/tests-e2e/Cargo.toml
justfile
mobile/ios/Podfile.lock
mobile/ios/Runner.xcodeproj/project.pbxproj
mobile/lib/features/trade/order_list_item.dart
mobile/lib/features/trade/position_list_item.dart
mobile/lib/features/trade/trade_bottom_sheet.dart
mobile/lib/features/wallet/share_invoice_screen.dart
mobile/lib/features/wallet/wallet_screen.dart
mobile/lib/features/welcome/welcome_screen.dart
mobile/macos/Podfile.lock
mobile/native/Cargo.toml
mobile/pubspec.lock
mobile/pubspec.yaml

Dart 3 is a big release, that introduces many Rust-like features.
Thankfully, all our code was compatible with it, so it was trivial to bump at
this stage.
Some highlights of Dart 3:
- sound null-safety,
- destructuring,
- patterns (better switch and if statements)
- records
- sealed classes (and other class modifiers)
More info:
- https://medium.com/dartlang/announcing-dart-3-53f065a10635
- https://codewithandrea.com/articles/whats-new-dart-3-introduction/

chore: Bump to Dart 3 and latest Flutter 3.10.5

---

mobile/lib/features/wallet/send_screen.dart

Same change as for the create invoice screen, see #862 - just making sure we don't run into the same problem with the send screen,
The changeset is not displayed nicely on GitHub; I only added the `GestureDetector` wrapping the `SafeArea`.

Defocus textfield upon clicking anywhere on send screen

---

crates/ln-dlc-node/src/ln/channel_details.rs

The funding txo will be different depending on whether a dlc channel is open or closed.
Adding the original funding txo so we can see the actual funding transaction that has been broadcasted on-chain.

chore: Add original funding txo to list channels response

---

mobile/lib/features/trade/order_submission_status_dialog.dart
mobile/pubspec.lock
mobile/pubspec.yaml

This is on top of #820 and should wait for that to be merged first. This is intended to add a little hype to the new position and encourage the user to celebrate by sharing on Twitter :)
Right now it is just a little puff of confetti from the tick.
This needs flutter >3.7.2 to work, otherwise it will crash.
Fixes #822.

Confetti after order confirmed

---

CHANGELOG.md
coordinator/src/routes.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/tests-e2e/src/bitcoind.rs
crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/src/lib.rs
crates/tests-e2e/src/test_subscriber.rs
crates/tests-e2e/tests/basic.rs
mobile/native/Cargo.toml
mobile/native/src/api.rs
mobile/native/src/channel_fee.rs
mobile/native/src/event/api.rs
mobile/native/src/event/mod.rs
mobile/native/src/lib.rs
mobile/native/src/ln_dlc/lightning_subscriber.rs
mobile/native/src/ln_dlc/mod.rs

fixes #577 
- The payment of the fee is not yet depicted as a special payment. This will be covered in a follow up PR after aligning with https://github.com/get10101/10101/pull/863
- The funding transaction is only cached in memory
TODOs that will be covered in follow up tickets.

feat: charge fee when opening a jit channel

---

bors.toml

New end to end tests are not supposed to be flaky; check whether they pass
before merging.

chore(bors): Check for e2e-tests passing before merging

---

justfile

Open by default with `less` in follow mode (so that it refreshes the contents).
It's like vim, one can search using `/` or by highlighting a word with `*`.
In order to stop following and start browsing historical entries
(with pagination!), hit Ctrl+C.

chore(justfile): Improve log browsing experience

---

.github/workflows/build-release-binaries.yml

With 1.0.21 we've released the configurable oracle, that was pointing to the new one hosted on our prod environment.
As we have open positions, we should stick with the old one until all old positions are closed and switch afterwards.

fix: Set oracle endpoint to the same as the coordinator

---

Cargo.lock
coordinator/src/node.rs
coordinator/src/node/order_matching_fee.rs
coordinator/src/routes.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/node/storage.rs
crates/ln-dlc-node/src/node/wallet.rs
crates/orderbook-commons/Cargo.toml
crates/orderbook-commons/src/lib.rs
crates/orderbook-commons/src/order_matching_fee.rs
crates/tests-e2e/tests/open_position.rs
mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_screen.dart
mobile/lib/features/trade/trade_value_change_notifier.dart
mobile/lib/features/wallet/domain/wallet_history.dart
mobile/lib/features/wallet/wallet_history_item.dart
mobile/native/migrations/2023-06-29-060753_add_description_to_payments/down.sql
mobile/native/migrations/2023-06-29-060753_add_description_to_payments/up.sql
mobile/native/src/api.rs
mobile/native/src/db/models.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs
mobile/native/src/schema.rs

Fixes #838[^1].
Fixes https://github.com/get10101/meta/issues/170.
Fixes https://github.com/get10101/meta/issues/171.
Fixes #884.
We keep it simple for now: the coordinator returns an invoice and we trust the app to pay for it.
Invoice generation rationale
----------------------------
We choose to let the coordinator generate
an invoice rather than send an spontaneous payment from the app so that we can more easily update the coordinator fees without having to release a new version of the app.
Payment timing rationale
------------------------
In patch 7c6a4bbb808267a8e56633ba471487838e74f414 the app was paying the invoice as soon as possible, but this had two downsides:
1. The app could end up paying for a trade that didn't come to fruition.
2. Updating the LN-DLC channel from the …

Pay order-matching fee on the app

---

mobile/lib/features/trade/trade_bottom_sheet_tab.dart

This is important as otherwise it's unclear why we are not able to trade with a margin smaller than the usable balance.
On the other hand, I have a hard time making this look nice because my UI design skills are severely lacking. As such, suggestions and even force-pushes to the branch are welcome.
This is how it looks now:

Display estimated order-matching fee when trading

---

justfile

Wait for coordinator to actually start before stating that it started successfully.
Note: We can't do this with maker for now, as there's no HTTP API there yet.

chore(justfile): Improve `just coordinator-detached`

---

justfile

The `$` was misplaced.
Additionally, fetching the internet address using `ifconfig.co` does not always work - a more resilient solution is to grep ifconfig output to fetch the local network address.
Thanks to stackoverflow https://stackoverflow.com/questions/13322485/how-to-get-the-primary-ip-address-of-the-local-machine-on-linux-and-os-x

Fix just command to run app on android device against locally running services

---

Cargo.lock
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/fee_rate_estimator.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/wallet.rs
crates/ln-dlc-node/src/tests/bitcoind.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/tests-e2e/Cargo.toml
crates/tests-e2e/src/bitcoind.rs
crates/tests-e2e/src/fund.rs
crates/tests-e2e/src/setup.rs
crates/tests-e2e/tests/basic.rs
mobile/ios/Podfile.lock

Lock used utxos

---

crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/ln/mod.rs
mobile/lib/common/application/channel_info_service.dart
mobile/lib/common/modal_bottom_sheet_info.dart
mobile/lib/features/trade/trade_bottom_sheet.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/wallet/create_invoice_screen.dart
mobile/lib/features/wallet/domain/share_invoice.dart
mobile/lib/features/wallet/share_invoice_screen.dart
mobile/lib/main.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

fixes https://github.com/get10101/meta/issues/172
Please note: The screen font may look a bit odd for you because my default test setup is iPhone SE (3rd gen) with **Accessibility Large, Bold Text** activated to ensure that the screen does not break (unless users somehow increase the font even more, not sure if that is possible):

Calculate and display open-channel fee estimate

---

crates/ln-dlc-node/src/tests/dlc/non_collaborative_settlement.rs

This test can hang on CI. From the logs we do see a message corresponding to line 93 (where we mine one block), so it should be sufficient to log everything after that in order to identify where we are hanging.
---
Related to #807.
We don't need to merge this. I just want to keep re-triggering the relevant job to reproduce the hang with extra context.

Add logs to flaky `force_close_ln_dlc_channel` test

---

.github/workflows/ci.yml
Cargo.lock
coordinator/src/orderbook/mod.rs
coordinator/src/orderbook/routes.rs
coordinator/src/orderbook/websocket.rs
crates/tests-e2e/Cargo.toml
crates/tests-e2e/src/fund.rs
crates/tests-e2e/src/test_subscriber.rs
justfile
mobile/lib/features/trade/position_change_notifier.dart
mobile/lib/features/trade/position_list_item.dart
mobile/lib/features/trade/trade_screen.dart
mobile/lib/features/trade/trade_theme.dart
mobile/macos/Podfile.lock
mobile/native/src/orderbook.rs
mobile/native/src/trade/position/handler.rs
mobile/test/trade_test.dart

- prune expired orders in the app when maker or coordinator is offline
- add a test that ensures we detect lack of orders
TODO:

Handle expired orders in the app

---

crates/ln-dlc-node/src/disk.rs

With this patch we don't read a historically stored scrorer from disk. It's not ideal, but at least users running into panics when loading the scorer will be able to run the app again
Workaround for #797 
fix #797

fix: read scorer

---

coordinator/migrations/2023-07-14-043111_routing_fees/down.sql
coordinator/migrations/2023-07-14-043111_routing_fees/up.sql
coordinator/src/bin/coordinator.rs
coordinator/src/db/mod.rs
coordinator/src/db/routing_fees.rs
coordinator/src/lib.rs
coordinator/src/node.rs
coordinator/src/node/routing_fees.rs
coordinator/src/routing_fee/mod.rs
coordinator/src/routing_fee/models.rs
coordinator/src/schema.rs
crates/ln-dlc-node/src/node/mod.rs

fixes https://github.com/get10101/meta/issues/177
Notes:
- I have not added the prometheus counter yet because I am waiting for the result of discussion here: https://github.com/get10101/10101/pull/946#discussion_r1263175979
- Opted for a separate table in the databse instead of adding a table that abstracts over multiple "fees". I think it's better to created views / reports on top

Save routing fees in database

---

crates/ln-dlc-node/src/disk.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/mod.rs

Reading the scorer from disk on iOS seems to panic sometimes, hence, we use an in-memory scorer for the app and a persistant scorer for the coordinator.
fix: #797

fix: use in-memory scorer for app and persistent for coordinator

---

coordinator/src/routes.rs
crates/tests-e2e/src/app.rs
crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/src/test_subscriber.rs
crates/tests-e2e/tests/open_position.rs
justfile
mobile/lib/util/environment.dart
mobile/native/src/api.rs
mobile/native/src/config/api.rs
mobile/native/src/config/mod.rs
mobile/native/src/event/api.rs
mobile/native/src/event/mod.rs
mobile/native/src/health.rs
mobile/native/src/lib.rs
mobile/native/src/orderbook.rs

- Introduce a mechanism for communicating service status to the frontend.
- Communicate about the orderbook status (websocket stream connection) and
coordinator status (responsive on HTTP API).
- Verify in e2e test that the status is updated correctly.
Note: The frontend part is well underway, it will come in a separate PR.

Check coordinator status from 10101 wallet (backend)

---

coordinator/migrations/2023-07-10-060138_payments/down.sql
coordinator/readme.md

Can be tested with:
```
diesel migration redo --all --database-url=postgres://postgres:mysecretpassword@localhost:5432/orderbook --migration-dir ./migrations
```

Remove created payment types in `down` migration

---

coordinator/migrations/2023-07-18-045732_open_channel_transaction_fee_payment/down.sql
coordinator/migrations/2023-07-18-045732_open_channel_transaction_fee_payment/up.sql
coordinator/src/db/channels.rs
coordinator/src/node.rs
coordinator/src/node/channel_opening_fee.rs
coordinator/src/routes.rs
coordinator/src/schema.rs
mobile/native/src/channel_fee.rs

fixes https://github.com/get10101/meta/issues/175
Upon requesting the invoice the user provides the amount to be paid and the funding transaction id that the fee was extracted from. The coordinator creates the invoice, records the payment in the database and then associates the `payment_hash` with with the `channels` in the database.
This PR is is stacked on top of https://github.com/get10101/10101/pull/950
Notes:
- After a chat with @luckysori we came to the conclusion that the funding transaction fee costs (that the app currently reimburses in a payment) should be the only missing piece for  https://github.com/get10101/meta/issues/175 because any other fees (charged for channel opening) should be covered by the routing fees already. If we want to somehow associate them with the channel …

Track channel opening transaction fee payments

---

coordinator/src/db/positions.rs
coordinator/src/node/closed_positions.rs
coordinator/src/position/models.rs
coordinator/src/schema.rs

Unfortunately https://github.com/get10101/10101/pull/966 merged with an outdated `schema.rs` version in the coordinator. 
This PR fixes this!

Fix outdated schema and correctly handle temporary contract id

---

mobile/native/src/channel_fee.rs

The parameters were out of sync resulting in an error which was tried to be parsed as invoice. Which obviously failed.
The `basic.rs` was unfortunately not able to catch that due to a workaround for https://github.com/get10101/10101/issues/883

fix: Align funding tx fee invoice parameters with endpoint

---

services/faucet/lnd.conf

Internally the faucet is listening to the port 80. This is fixing the following error messages in lnd.
```
2023-07-22 05:18:04.923 [ERR] LNWL: unable to query web api for fee response: Get "http://10.5.0.7:8080/fee/btc-fee-estimates.json": dial tcp 10.5.0.7:8080: connect: connection refused
2023-07-22 05:18:04.923 [ERR] LNWL: unable to query estimator: web API error: fee rate cache is empty
``

fix: Query fee estimates from internal port 80

---

coordinator/migrations/2023-07-19-055143_closed_positions/down.sql
coordinator/migrations/2023-07-19-055143_closed_positions/up.sql
coordinator/migrations/2023-07-20-055142_unrealized_pnl_positions/down.sql
coordinator/migrations/2023-07-20-055142_unrealized_pnl_positions/up.sql
coordinator/migrations/2023-07-21-050135_closing_price_positions/down.sql
coordinator/migrations/2023-07-21-050135_closing_price_positions/up.sql
coordinator/src/bin/coordinator.rs
coordinator/src/db/positions.rs
coordinator/src/node.rs
coordinator/src/node/expired_positions.rs
coordinator/src/node/unrealized_pnl.rs
coordinator/src/position/models.rs
coordinator/src/schema.rs
crates/trade/src/bitmex_client.rs
crates/trade/src/cfd.rs
mobile/native/src/trade/position/handler.rs

stacked on top of https://github.com/get10101/10101/pull/966
Note: I did not bother setting the `unrealized_pnl` to null when we close the position. Not sure that's actually necessary.
fixes: #932

Periodically update unrealized pnl for position in database

---

crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs
crates/ln-dlc-node/src/tests/dlc/non_collaborative_settlement.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/fail_intercepted_htlc.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/mod.rs
crates/ln-dlc-node/src/tests/load.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/ln-dlc-node/src/tests/multi_hop_payment.rs
crates/ln-dlc-node/src/tests/single_hop_payment.rs

Fixes #943.
Fixes #944.
---
This is yet another instance where we have to consider the fact that the same event handler code runs for both app and coordinator even though certain parts need to be specific to each role. I've increased the implicit annoyance counter of https://github.com/get10101/10101/issues/885.

Fail intercepted HTLC backwards when we should

---

crates/tests-e2e/src/test_subscriber.rs
mobile/lib/common/app_bar_wrapper.dart
mobile/lib/common/domain/service_status.dart
mobile/lib/common/service_status_notifier.dart
mobile/lib/common/service_status_notifier_test.dart
mobile/lib/common/status_screen.dart
mobile/lib/features/trade/status_screen.dart
mobile/lib/features/wallet/status_screen.dart
mobile/lib/main.dart
mobile/native/src/event/api.rs
mobile/native/src/health.rs
mobile/pubspec.lock
mobile/pubspec.yaml

- Add the status to the AppBar, next to Settings screen
- display service status as well as overall status
TODO:
Posting as-is as I suspect that this will spark the conversation whether we'd
like to have a hamburger menu or not instead of row of icons.
https://github.com/get10101/10101/assets/8319440/459362cb-a2ba-4572-8f17-23f13ad5b3a6
only difference since the video: "overall" -> "App Health"

feat: Display service status in the app

---

justfile

This is for use in x86_64 android emulators. Fixes #990.
This only compiles for x86_64 on the `android` recipe and not `android-release` to avoid building and distributing x86_64 libraries if 10101 is ever published to the Play Store or similar.

Build android for x86_64 except on android-release

---

mobile/lib/main.dart

If this is not awaited, then something tries to access the database before it is ready.
@klochowicz I think you just left this out by mistake?  Trivial fix in the end!
Fixes #1002.

Add `await` to fix app initialisation

---

crates/bitmex-stream/src/lib.rs

Adds a timeout to the websocket to bitmex in order to provoke a reconnect if the websocket becomes unresponsive. Fixes #919.

Reconnect to BitMex if the websocket disconnects

---

crates/tests-e2e/src/setup.rs
crates/tests-e2e/tests/basic.rs
crates/tests-e2e/tests/receive_payment_when_open_position.rs
mobile/native/src/api.rs
mobile/native/src/channel_fee.rs
mobile/native/src/ln_dlc/mod.rs

fix: Wait for outbound capacity before paying jit channel open fee

---

coordinator/src/bin/coordinator.rs
coordinator/src/routes.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/peer_manager.rs
crates/tests-e2e/examples/fund.rs
crates/tests-e2e/src/coordinator.rs

We need to wait until the node announcement was processed correctly by lnd. This can be checked if lnd is aware of the coordinator's `node_alias`.
In the below patches we change the node announcement to 1/hour and allow triggering it manually using a http enpoint. With this I was so to always get into a working setup :)
fixes https://github.com/get10101/10101/issues/764

fix: no_route found in local dev setup

---

.github/workflows/ci.yml

Bors is dead, long live merge queues. 
Given we don't have any special things to run on `staging` anymore, we can start using github merge queues.
Resolves https://github.com/get10101/10101/issues/571
everyone is a reviewer so that you are aware. For the time being, we have both enabled: bors and merge queues. 
If we are happy with merge queues, we can retire bors :)

feat: build ci in merge queue

---

README.md
justfile
mobile/android/build.gradle

Very basic android dev setup in case things need to be tested in a mobile environment.
For me, usually desktop is sufficient, but since I am on Linux/Windows and have no access to an iOS device or Mac with XCode, Android is the easiest option for mobile debugging.

Update android project setup with new all-android recipe

---

coordinator/src/node/expired_positions.rs
coordinator/src/node/unrealized_pnl.rs
crates/trade/src/bitmex_client.rs
mobile/ios/Podfile.lock
mobile/lib/features/trade/application/candlestick_service.dart
mobile/lib/features/trade/candlestick_change_notifier.dart
mobile/lib/main.dart
mobile/native/src/trade/position/handler.rs
mobile/test/trade_test.dart

Use the correct quotes consistently on the coordinator and app depending on the network.
// edit: updated description due to a changed solution approach.

chore: Use network specific quotes everywhere

---

justfile

This speeds up development a little bit. The balance is retrieved by `curl`ing the channel balance.
I left this out of  the `fund-regtest` recipe since it seems to be a manually invoked recipe and not an automated prerequiste, hence it is not really needed.

Only fund when faucet balance drops below 10 000 000 sats

---

mobile/lib/features/wallet/send_payment_change_notifier.dart
mobile/lib/features/wallet/send_screen.dart
mobile/lib/features/wallet/wallet_screen.dart

This is still a work-in-progress, because if a valid but already paid invoice is pasted, then the "Send Payment" button still exhibits the weird behaviour described in #1024. Fixes #1024.

Enable "Send Payment" button only when the invoice is validated

---

.github/workflows/ci.yml

There are breaking changes in version 0.40 which we need to handle before we can upgrade.

Pin `dprint` to version 0.39.1 temporarily

---

CHANGELOG.md
Cargo.lock
Cargo.toml
coordinator/src/db/custom_types.rs
crates/ln-dlc-node/src/ln/dlc_channel_details.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/tests-e2e/tests/close_position.rs
mobile/native/src/ln_dlc/node.rs

Fixes #842.
Fixes https://github.com/get10101/meta/issues/198.
The notable changes are:
- Add new `Revoke` message to the subchannel-opening protocol. This has forced us to adapt the tests. More importantly we now update the position and order of the _app_ when receiving this message, rather than when sending the `Finalize` message. This is because the `Revoke` message is what actually marks the end of the subchannel-opening protocol now[^1].
- Require consumers to notify the `SubChannelManager` about the closure of a channel according to LDK. This is necessary so that the subchannel manager can react to the counterparty force-closing the channel using an untracked transaction.
Finally, by now depending on latest `rust-dlc#feature/ln-dlc-channels` we have replaced …

Allow force-closing LN-DLC channel in all intermediate states

---

.github/workflows/draft_new_release.yml
Cargo.lock
coordinator/Cargo.toml
coordinator/src/routes.rs
mobile/lib/main.dart
mobile/pubspec.lock
mobile/pubspec.yaml

This PR is based on the advice from @klochowicz in #916. It introduces a new `/api/version` endpoint to the coordinator, which returns its version as recorded in `coordinator/Cargo.toml`. This, in turn, is kept in sync by the `draft_new_release` action (I am not quite sure how to test it locally). Then, on startup, the mobile client will perform a GET request to `/api/version`, compare it to its own version, and if it is out of date it will create a snackbar notification.
I'm not sure if we want to add an action to direct the user to an update page, or to add something else to the snackbar.
There might also be considerations for local/regtest development where we might want to handle this differently.
In line with what was discussed, this PR does not disable anything, merely informing the …

Check if client outdated

---

.github/workflows/ci.yml
dprint.json
rustfmt.toml

Old Rust plugin got archived and awaits a rewrite in wasm sandbox.
In the meantime, the recommended way is to directly call `rustfmt.
See: https://github.com/dprint/dprint-plugin-rustfmt
Add `rustfmt.toml` to preserve our custom formatting.

chore: Update dprint to latest version

---

justfile

Some older API versions use x86 by default in the emulator. Also deletes the old libs in `jniLibs` in `clean` task.

Compile android for x86 too

---

justfile

While investigating #1004 I discovered that you can't run `RUST_LOG=warn just all` since that makes FRB codegen panic. I just overrode RUST_LOG to either debug or info depending on its actual value for the FRB codegen calls.

Allow setting RUST_LOG to any value in `just all`

---

mobile/native/src/channel_fee.rs

Fixes https://github.com/get10101/10101/issues/1030.
Waiting for 5 seconds proved insufficient in some cases. In theory we could wait for as long as we want to as this work will happen in the background.
It might still help to redesign this flow so that we just keep retrying if we owe the coordinator for opening the JIT channel, rather
than only trying once after claiming the interceptable payment.

Wait longer to pay for channel-opening fee

---

.github/workflows/ci.yml
coordinator/src/db/user.rs
coordinator/src/orderbook/tests/registration_test.rs
crates/bitmex-stream/src/lib.rs
crates/ln-dlc-node/src/node/peer_manager.rs
crates/ln-dlc-node/src/seed.rs
crates/orderbook-client/src/lib.rs
crates/tests-e2e/src/setup.rs
dprint.json
mobile/native/src/event/mod.rs
mobile/native/src/trade/order/orderbook_client.rs

We must do this if we want `dprint` to respect some of the unstable options we have configured in our `rustfmt.toml`. This is what we get if we run `cargo fmt` (as opposed to `cargo +nightly fmt`):
```
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `comment_width = 100`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Item`, unstable features are only available in nightly channel.
Warning: can't set `group_imports = One`, unstable features are only available in nightly channel.
```
After running `dprint fmt` with the new configuration we can see that the autoformatter consistently applies `group_imports = One` to our codebase.

Run `rustfmt` with nightly

---

crates/ln-dlc-node/src/ln/manage_spendable_outputs.rs

Otherwise we see errors in the logs, because transactions spending no UTXOs are obviously invalid!

Do not attempt to publish transaction spending no LDK spendable outputs

---

mobile/lib/common/scrollable_safe_area.dart
mobile/lib/common/settings_screen.dart
mobile/lib/common/status_screen.dart
mobile/lib/features/trade/trade_bottom_sheet.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/wallet/create_invoice_screen.dart
mobile/lib/features/wallet/send_screen.dart
mobile/lib/features/welcome/welcome_screen.dart

Fixes #1026. This just makes the content scroll vertically if it would be too small to fit on the screen (due to its size or due to the on-screen keyboard being opened).

Add ScrollableSafeArea to scroll widgets if keyboard would squish them

---

Cargo.lock
Cargo.toml

Fixes #1058.
Fixes #1056.
See https://github.com/p2pderivatives/rust-dlc/commit/8dfff94 for context.
---
I've been able to confirm that we don't run into #1058 or #1056 when upgrading to this patch instead of latest `main`.

Avoid specific serialisation errors in `rust-dlc`

---

bors.toml

R.I.P. Bors [']
Prevent accidentally calling bors, when we should be using merge queue instead.

chore: Remove bors.toml

---

coordinator/src/bin/coordinator.rs
coordinator/src/node.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/ln/mod.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/dlc/collaborative_settlement.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs
crates/ln-dlc-node/src/tests/dlc/non_collaborative_settlement.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/channel_close.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/fail_intercepted_htlc.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/payments.rs
crates/ln-dlc-node/src/tests/load.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/ln-dlc-node/src/tests/multi_hop_payment.rs
crates/ln-dlc-node/src/tests/single_hop_payment.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs

The main motivation was as such:
Separate the boring things (e.g. initialisation of bajilion pieces of LDK) from the customisation points, which might be different.
As such, `ln_dlc_node::Node` is only a collection of entities needed to be used to run a LDK node with DLC capable.
For now, there's a single 'start' method into which different EventHandlers can be passed in.
It's easy to imagine that if we ever need/want to just have separate free functions in various node implementations for starting the node. They can be composed quite easily with the aid of the functions extracted from Node in a PR made recently.
As such, this is not the scope of the ticket, and I had to stop the refactor somewhere 😀

Allow using different event handlers

---

mobile/lib/common/application/event_service.dart
mobile/lib/features/trade/order_change_notifier.dart
mobile/lib/features/trade/position_change_notifier.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/wallet/share_invoice_screen.dart
mobile/lib/features/wallet/wallet_change_notifier.dart

We are using a dedicated logging framework.

chore: Remove Dart developer logs

---

mobile/native/migrations/2023-08-07-232900_add_order_expiry_to_order/up.sql

If the orders table was not empty,
the migration would never succeed as sqlite does not allow setting
non-const default values unfortunately.
Given that all the historical orders in the DB would have been
outdated in 60 seconds anyway, set the default expiry to 0 instead.

fix: Fix recent db migration in the app

---

justfile

It was a major slowdown to wait for the project to recompile as cache was being invalidated.
By specifying a different target directory we ensure build artefacts will be
preserved when switching between `just ios` and `just native`.
Note: Only the debug build has been adjusted, as this should not matter for the releases.

chore(justfile): Don't invalidate the cache between iOS and native builds

---

CHANGELOG.md
Cargo.lock
coordinator/src/bin/coordinator.rs
coordinator/src/routes.rs
crates/coordinator-commons/src/lib.rs
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/config.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/ln/app_event_handler.rs
crates/ln-dlc-node/src/ln/common_handlers.rs
crates/ln-dlc-node/src/ln/coordinator_event_handler.rs
crates/ln-dlc-node/src/ln/event_handler.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/mod.rs
mobile/lib/common/amount_text_input_form_field.dart
mobile/lib/common/application/channel_info_service.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/wallet/create_invoice_screen.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs
mobile/test/trade_test.dart

With this change we can configure the max channel size aka, we can enable wumbo trades.
I've also made a small frontend change: the info text is gone and replaced with an info icon. This solved the problem that the `maxChannelSize` is not immediately available .
https://github.com/get10101/10101/assets/224613/293eaa2b-dd3c-44a5-bdaa-3cd476d599a0
This will help us with running the increased-channel-size experiment.
resolves https://github.com/get10101/10101/issues/983

Wumbo trade: aka configurable channel size

---

coordinator/src/db/transactions.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/storage.rs
crates/ln-dlc-node/src/shadow.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/transaction.rs
mobile/native/src/db/models.rs

Fixes #1101.
We needed to align the implementations of the two traits where we broadcast transactions. There were several places where we were not storing broadcast transactions because of this.

Ensure that broadcast TXs are always stored

---

CHANGELOG.md
Cargo.lock
Cargo.toml
coordinator/src/bin/coordinator.rs
coordinator/src/node.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs

Fixes #1107.
I think this could be very, very helpful in preventing disconnection-related issues in production. In theory this could improve the speed of the worst-case scenario for the current version of the subchannel open/close protocol by ~25 seconds!

Check for new DLC-related messages 25 times more often

---

crates/ln-dlc-node/src/config.rs

A fix fee rate of 4 is not safe anymore as the mempool has been congested since a long time purging transactions with a low fee. We clearly need anchor outputs, but this is an attempt to at least be able to force close positions

chore: bump DLC fee rate

---

mobile/ios/Runner.xcodeproj/project.pbxproj

Release [1.2.1 failed](https://github.com/get10101/10101/actions/runs/5928785922/job/16075130621)
Did not test it on the fork but locally. The problem was that when I've provided the [last fix ](https://github.com/get10101/10101/pull/1112/commits/005fd65f29d8375e61722069fceb301f147272b7) for fastlane I forgot to change the provisioning profile in the xcode config.
Uploading version 1.2.1 from local setup as this is being created

fix: wrong provisioning profile

---

.github/workflows/ci.yml
justfile
mobile/native/src/api.rs

It still shows some warnings in Firebase (they will be fixed by #1104 ), but at least it unblocks rapid Flutter development.

Fix Flutter hot restart

---

coordinator/src/node/channel_opening_fee.rs
coordinator/src/routes.rs
crates/ln-dlc-node/src/channel.rs
mobile/lib/features/wallet/domain/wallet_history.dart
mobile/lib/features/wallet/wallet_history_item.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

Show JIT channel fee in wallet history

---

CHANGELOG.md
coordinator/src/orderbook/trading.rs
coordinator/src/rollover.rs
crates/tests-e2e/tests/rollover_position.rs
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/native/src/trade/position/handler.rs

This is also a good reference for implementing #1029. The expiry is currently scattered through the code and would be ideally only configured at one place.
resolves #1154

chore: change contract duration to 7 days

---

justfile

Seems like an accidental omission

fix: actually run native tests with `just native-test`

---

mobile/lib/main.dart

Configuring this should allow us to deliver messages and push notifications even if the app is terminated.

feat: Allow delivering messages in the background handler

---

coordinator/migrations/2023-08-28-082948_add_raw_tx_field/down.sql
coordinator/migrations/2023-08-28-082948_add_raw_tx_field/up.sql
coordinator/src/db/transactions.rs
coordinator/src/schema.rs
crates/ln-dlc-node/src/shadow.rs
crates/ln-dlc-node/src/transaction.rs
mobile/native/migrations/2023-08-28-083813_add_raw_field_to_transactions/down.sql
mobile/native/migrations/2023-08-28-083813_add_raw_field_to_transactions/up.sql
mobile/native/src/db/models.rs
mobile/native/src/schema.rs

for transactions we are broadcasting we should store the raw transaction so that we can re-broadcast it in the future if needed.
Manually extracting it is a [a lot of work](https://www.notion.so/get10101/Extracted-raw-transactions-b913770b883b4f10a7f1071a09c3ca1f) and only doable for the past 30 days. 
Resolves https://github.com/get10101/10101/issues/1139 by storing the raw tx in the database

feat: store raw transaction in db

---

Cargo.lock
Cargo.toml
crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs

Error happens when the pending `Accept` or `CloseAccept` message is processed after connection has lost and the channel is re-established again.
The first commit e9bdf053689b9fc533633796a2fa362701e3e257 reproduces the errors reported in #1074 and #1141.
The second commit 5ec59d271ed640b94ded9a5c8126e0427991eb43 points to the fix in `rust-dlc` https://github.com/p2pderivatives/rust-dlc/pull/142. Note, this is still pointing to the PR as it is waiting a review. We may want to want for the merge there before merging this PR.
fixes #1074 
fixes #1141 
Note, already broken channels will not get recovered with that fix and have to be force-closed.

fix: Invalid commitment tx signature from peer after processing pending Accept or CloseAccept message

---

CHANGELOG.md
mobile/lib/features/stable/stable_screen.dart
mobile/lib/features/trade/position_change_notifier.dart
mobile/lib/features/wallet/balance_row.dart
mobile/lib/features/wallet/domain/wallet_history.dart
mobile/lib/features/wallet/wallet_history_item.dart
mobile/lib/features/wallet/wallet_screen.dart
mobile/macos/Podfile.lock
mobile/native/src/event/api.rs

https://github.com/get10101/10101/assets/8319440/9fb836cd-cf47-4048-b210-615826f91e28

Add Synthetic USD balance into account overview

---

justfile
mobile/lib/main.dart
mobile/native/src/event/event_hub.rs
mobile/native/src/ln_dlc/channel_status.rs
mobile/native/src/orderbook.rs

A bunch of commits aimed at making it easier to parse the logs.
See commits for details
below screenshot of [lnav](https://lnav.org) finally parsing the app logs correctly:

Improve app debugging experience

---

mobile/lib/features/trade/application/order_service.dart

The problem here is that we have a concurrency issue when sending a payment and trying to open/close a position. This does not fix the underlying issue though: we should block in the protocol that a payment cannot be sent or received at the same time as a subchannel is being added or removed.
does not really resolve https://github.com/get10101/10101/issues/1194 but it will make it less likely to happen. 
not 👉 @holzeis 🙈

fix: invalid commitment signed

---

mobile/lib/features/trade/domain/leverage.dart
mobile/test/leverage_test.dart

in `hasStableUSD()` we are comparing the leverage of the position to be equal the Leverage(0), i.e. `positionUsd.leverage == Leverage(1);`. For this to work we need to implement equal on `Leverage`.
Resolves https://github.com/get10101/10101/issues/1193

fix: show balance of synth usd 

---

Cargo.lock

https://github.com/advisories/GHSA-8qv2-5vq6-g2g7
Turned out to be really simple to fix it, by bumping one of our dependencies (`webpki` was only a transitive one of ours)

chore(deps): Bump ureq package to solve security advisory

---

crates/ln-dlc-node/src/ldk_node_wallet.rs

If broadcasting the transaction fails we would not keep a record of the transaction. By attempting to upsert the transaction beforehand we make sure to update our database before.

fix: upsert transaction before broadcast

---

mobile/lib/features/stable/stable_screen.dart

Fix the check to hide the details on all positions that are not stable.
Previously, we would display details here even on any short position

fix: Hide position details on stable screen on non-stable positions

---

Cargo.lock
coordinator/migrations/2023-08-23-152802_add_invoice_to_payments/down.sql
coordinator/migrations/2023-08-23-152802_add_invoice_to_payments/up.sql
coordinator/src/db/payments.rs
coordinator/src/node/storage.rs
coordinator/src/schema.rs
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/ln/common_handlers.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/node/storage.rs
crates/ln-dlc-node/src/node/wallet.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/fail_intercepted_htlc.rs
crates/tests-e2e/tests/open_position.rs
mobile/lib/features/trade/order_list_item.dart
mobile/lib/features/wallet/balance_row.dart
mobile/lib/features/wallet/domain/wallet_history.dart
mobile/lib/features/wallet/domain/wallet_type.dart
mobile/lib/features/wallet/wallet_history_item.dart
mobile/lib/features/wallet/wallet_screen.dart
mobile/native/migrations/2023-08-23-152633_add_invoice_to_payments/down.sql
mobile/native/migrations/2023-08-23-152633_add_invoice_to_payments/up.sql
mobile/native/src/api.rs
mobile/native/src/db/models.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs
mobile/native/src/schema.rs
mobile/pubspec.lock

Addresses #872 by modelling more history details for different kinds of events (transactions, trades, fees, etc).
I don't think this PR should address the Figma mock beyond adding all the info that it has to the display and that should rather be done in a followup, but happy to change this if desired.
- ~~[ ] From node~~ I do not believe this to be possible without an explicit proof-of-payment protocol: https://bitcoin.stackexchange.com/a/85555
Questions:
Related: #1103

Model more transaction history details 

---

mobile/lib/common/fiat_text.dart

The dollar sign should go in front of the amount (e.g `$10`, not `10$`, see [here](https://english.stackexchange.com/a/11327))

feat: swap side of dollar sign in fiat text (val$ -> $val)

---

mobile/lib/common/snack_bar.dart
mobile/lib/features/wallet/share_invoice_screen.dart
mobile/lib/main.dart

When I updated my flutter, I started getting a lint failure for using BuildContext across an async gap. This PR fixes that as well as refactoring showSnackbar so it can be used more widely

Refactor showSnackbar to fix lint on latest flutter

---

.github/workflows/build-release-binaries.yml
CHANGELOG.md

Resolves [#710](https://github.com/get10101/10101/issues/710)

fix: improving wallet sync by 100x

---

Cargo.lock
mobile/native/Cargo.toml
mobile/native/src/channel_fee.rs
mobile/native/src/config/api.rs
mobile/native/src/config/mod.rs
mobile/native/src/ln_dlc/mod.rs

The reason for that is that URL is putting a trailing / at the file which becomes an issue in downstream libraries such as esplora-client. This is a temp fix, a proper fix will follow.
Note: make sure to pass in ESPLORA_ENDPOINT always without a trailing `/`, i.e. `ESPLORA_ENDPOINT=http://46.17.98.29:3000`

fix: use string for url instead of URL

---

Cargo.lock
coordinator/src/admin.rs

Often times we get multiple entries with the same (or similar) `user_email`s as users reopen their channels.
Adding the context of when the user was registered to this HTTP response helps identify the relevant channel quickly when debugging.

Add user registration timestamp to `dlc_channels` endpoint

---

Cargo.lock
Cargo.toml
crates/ln-dlc-node/src/node/dlc_channel.rs

See https://github.com/p2pderivatives/rust-dlc/commit/962265b.
The version dependency on `rust-bitcoin-coin-selection` no longer works, so we have to temporarily depend on a revision instead.

Fix `rust-bitcoin-coin-selection` dependency

---

docs/007-funding-rate.adoc
docs/readme.adoc

I decided to write an ADR because I came to the conclusion that the original solution reflected in #1069 does not work.
Because none of the solutions discussed in the document are ideal, I want to use this PR as an opportunity to reach consensus before actually implementing a solution to #1069.

Propose a solution for the funding rate

---

crates/tests-e2e/src/maker.rs
crates/tests-e2e/tests/maker.rs
maker/src/bin/maker.rs
maker/src/health.rs
maker/src/lib.rs
maker/src/metrics.rs
maker/src/routes.rs
maker/src/trading/mod.rs

Monitor the following services:
- coordinator
- orderbook (we don't subscribe to orderbook feed yet)
in order to derive health status of the maker.
Health status is exposed via the HTTP API as well as reported as
dedicated prometheus metrics.
the TODO listed above will be wired only when bitmex and orderbook streams will be integrated into maker, and as such are *not* a dependency of this PR - we can wire them in the corresponding PRs or in a follow-up.

feat(maker): Monitor and expose status of services connected

---

mobile/lib/features/wallet/wallet_screen.dart

Fix pull-down refresh

---

crates/ln-dlc-node/src/node/mod.rs

Adding logs around the periodic check to debug whether the periodic check interferes with the processing of DLC messages.

chore: Add logs around periodic check

---

CHANGELOG.md
Cargo.lock
crates/ln-dlc-node/src/fee_rate_estimator.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/storage.rs
crates/ln-dlc-node/src/node/wallet.rs
crates/tests-e2e/Cargo.toml
crates/tests-e2e/src/test_subscriber.rs
maker/src/trading/orderbook_client.rs
mobile/ios/Podfile.lock
mobile/lib/common/service_status_notifier.dart
mobile/lib/common/service_status_notifier_test.dart
mobile/lib/common/settings_screen.dart
mobile/lib/main.dart
mobile/native/src/channel_fee.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs
mobile/pubspec.lock

- ensure the app doesn't crash even if the backend cannot be started (e.g. no Internet, coordinator/esplora is down)
- clearly communicate limited functionality by a alert dialog
- show red 'Offline' status in the corner of the screen (thermostat)
Even if the backend cannot be started, the user can:
- export seed (!)
- share logs
- see most of the UI (although most of the functionality is disabled)
I also cleaned some unnecessary `expect` calls whilst investigating this issue.

Avoid panics at startup

---

.github/workflows/ci.yml

It's hard to determine the cause of test flakiness without all the auxiliary
logs from other services.
Print the logs of maker, coordinator and docker containers in case e2e tests fail.

chore(ci): Print services logs upon e2e test suite error

---

coordinator/src/bin/coordinator.rs
coordinator/src/node/rollover.rs
coordinator/src/orderbook/async_match.rs
coordinator/src/orderbook/trading.rs
coordinator/src/routes.rs
crates/coordinator-commons/src/lib.rs
crates/tests-e2e/tests/rollover_position.rs
mobile/lib/features/trade/application/trade_values_service.dart
mobile/lib/features/trade/domain/trade_values.dart
mobile/native/src/api.rs
mobile/native/src/config/api.rs

Adds a shorter expiry and rollover cycle for regtest.
Expiry at midnight the same day unless the position is opened during the rollover window. In that case the expiry is calculated to the next day midnight.
Rollover window: 8 hours before expiry.
resolves #1324

chore: Shorten expiry and rollover cycles for regtest

---

CHANGELOG.md
coordinator/build.rs
coordinator/src/routes.rs
mobile/lib/main.dart
mobile/lib/util/coordinator_version.dart

Useful to figure out what exact version the coordinator is running. 
Note: breaking change for old clients but I guess we can live with that. It will show a warning that the coordinator is not reachable until they upgrade

feat: also return commit hash and number in version api

---

Cargo.toml

We've run into `unimplemented!` block in rust-dlc in our regtest setup.
In order to unblock the regtest environment, this quickfix logs an error and
continues instead of panicking.
See: https://github.com/p2pderivatives/rust-dlc/pull/151

fix: Log error instead of panicking in rust-dlc upon subchannel force-closure attempt

---

mobile/lib/features/wallet/wallet_screen.dart

Note, this is just a quick patch for that scenario. We need to rework that dialog to wait for the payment to be successful or not, and not just depend whether we were able to submit the payment.
fixes #1121

fix: Add dedicated message if payment failed

---

coordinator/src/orderbook/db/orders.rs
coordinator/src/orderbook/routes.rs
coordinator/src/orderbook/tests/sample_test.rs
coordinator/src/orderbook/trading.rs
coordinator/src/routes.rs
maker/src/trading/mod.rs
maker/src/trading/orderbook_http_client.rs

Instead of deleting orders, I propose to keep them in state `Failed`. That might blow up our database, but we could at any time delete `Failed` orders if we want to.
To be consistent with the existing implementation I am also sending a `DeleteOrder` event to update the prices for the apps.
fixes #1347

fix: Do not delete orders

---

coordinator/migrations/2023-09-22-145256_unique_pubkey/down.sql
coordinator/migrations/2023-09-22-145256_unique_pubkey/up.sql
coordinator/src/db/user.rs
coordinator/src/orderbook/tests/registration_test.rs
coordinator/src/orderbook/websocket.rs
coordinator/src/routes.rs
crates/coordinator-commons/src/lib.rs
crates/orderbook-client/examples/authenticated.rs
crates/orderbook-client/src/lib.rs
crates/orderbook-commons/src/lib.rs
crates/tests-e2e/src/app.rs
maker/src/orderbook_ws.rs
mobile/lib/main.dart
mobile/lib/util/notifications.dart
mobile/native/src/api.rs
mobile/native/src/orderbook.rs
mobile/native/src/trade/users/mod.rs

This change addresses a couple of things
1. The fcm token update required the node to be up, but did not wait for the backend to start. Thus it was very likely that we were running into a race condition with the node not yet being initialized and the fcm token not being updated to the database.
2. Upon initial registration we call the register endpoint to create the user. In the background the fcm token update api was called. It was very likely that the user was not faster than the fcm token update, thus the user record did not exist at the time the fcm token is being updated. (this would have been fixed at the second start of the app)
I opted to remove the fcm token update api alltogether and rather send the `fcm token` with our initial `OrderbookMsg::Authenticate`. This ensures firstly, …

fix: Ensure the fcm token is stored to the users table

---

mobile/native/src/orderbook.rs

If we are reconnecting too eagerly we run into an issue during rollover windows.
If the user has the app open while "moving" into the rollover window and the coordinator restarts. The coordinator will identify that the users position needs to be rolled over upon a reconnect on the websocket, but the coordinator might not yet be ready to do that yet.
I guess this issue is not happening on the app side, as the app is connecting to the coordinator before it is subscribing to the websocket.
By increasing the websocket reconnect timeout to 5 seconds the `keep_connected` tasks should have enough time (every second) to reconnect to the coordinator.

chore: Increase websocket reconnect timeout

---

coordinator/src/bin/coordinator.rs
coordinator/src/message.rs
coordinator/src/node/rollover.rs
coordinator/src/orderbook/async_match.rs
coordinator/src/orderbook/trading.rs

Before we were only sending a push notification if the message was not successfully send via the channel. Which is basically never the case.

fix: Send push notification for expired position if user is not online

---

crates/tests-e2e/examples/fund.rs
justfile
maker/src/routes.rs
mobile/lib/features/wallet/share_invoice_screen.dart

This comes handy if LND doesn't work as expected.
You can then use `curl -X POST http://localhost:18000/api/pay-invoice/putinvoicehere` to pay any invoices and fund the app. 
Or you can use the new `fund with maker button` :)

Fund maker and open channel

---

mobile/lib/main.dart

It can happen that we run into a race condition where we are trying to get a firebase token but firebase is not yet initialised. Awaiting the firebase initialisation should fix the issue.

fix: Wait for firebase to initialise before geting the fcm token

---

CHANGELOG.md
mobile/lib/features/wallet/wallet_change_notifier.dart
mobile/lib/features/wallet/wallet_screen.dart

We made the wallet sync async and hence, the frontend did not wait for it to complete. To overcome this we busy check if the wallet change notifier was called and updated.
resolves #1346
syncing against regtest machine which takes ~4 seconds.
https://github.com/get10101/10101/assets/224613/d5fb6bd9-9be7-4a6a-8dd8-750d87682d28

fix: wait for wallet sync in refresh indicator

---

docker-compose.yml

Sometimes we have a ridiculous high fee estimate. This is due to the fallback fee being in **BTC/kvB**. Setting it to 0.00001 should be 1000sat/kvb or 1sat/vbyte
😅

fix: fallback fee too high

---

.github/workflows/ci.yml

Provide more information amidst elusive occasional ln-dlc tests failures on CI.

chore(ci): Print container logs upon ln-dlc test failure

---

crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/peer_manager.rs
maker/src/bin/maker.rs
maker/src/routes.rs

This change includes two changes
1. We now only broadcast node announcements if we have at least one public channel.
2. We only open the channel with the maker after we have opened the lnd channel. This produces more reliably results when running `just fund`.
It also looks like there is an issue with node announcements in rust-lightning in general. In the tests we've seen multiple occasions where the coordinator refused to broadcast node announcements to lnd. Including gossiping known nodes and channels.
e.g. even though the coordinator and the maker shared a `usable` and `public` channel, the coordinator refused the makers node announcement.
`lightning::ln::peer_handler: Error handling message from 038ad93a14076c86eec6c8d390315e742601d9634baf2755d88c987139ab62e16d; ignoring: No existing …

chore: Only broadcast node if at least one channel

---

.github/workflows/ci.yml
justfile

New job `generate-ffi` is triggered straight away, when it finishes it uploads
both generated files for Rust and Dart.
Upload its result once and utilise it in other jobs, instead of wasting minutes
achieving the same result and introducing unneeded dependencies, e.g. flutter
into jobs that can get away without having it. This should in turn limit our
disk usage in these jobs, causing less errors on CI.

chore(ci): Generate FFI bindings only once in the CI

---

justfile
mobile/lib/common/settings_screen.dart

- always show close channel button
- catch exceptions and show errors if any
- prevent accidental abuse of the API by repeated clicks

Improve Close channel buttons

---

crates/ln-dlc-node/src/node/storage.rs
mobile/lib/features/welcome/welcome_screen.dart

Catch a hole in the registration process, where the app would only store the email locally if the coordinator was unreachable during app registration.

Catch possible exception during registration

---

mobile/lib/features/wallet/onboarding/fund_wallet_modal.dart
mobile/lib/features/wallet/payment_claimed_change_notifier.dart

It's weird but if you pop only once you don't get back to the wallet screen and if you pop twice you get back to the wallet screen but also get the exception.
fixes: #1435

fix: Use go to wallet screen instead of pop

---

mobile/lib/common/application/event_service.dart
mobile/lib/common/channel_status_notifier.dart
mobile/lib/common/recover_dlc_change_notifier.dart
mobile/lib/common/service_status_notifier.dart
mobile/lib/common/settings_screen.dart
mobile/lib/features/trade/async_order_change_notifier.dart
mobile/lib/features/trade/order_change_notifier.dart
mobile/lib/features/trade/position_change_notifier.dart
mobile/lib/features/trade/rollover_change_notifier.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/wallet/application/faucet_service.dart
mobile/lib/features/wallet/application/wallet_service.dart
mobile/lib/features/wallet/onboarding/liquidity_card.dart
mobile/lib/features/wallet/send_payment_change_notifier.dart
mobile/lib/features/wallet/send_payment_screen.dart
mobile/lib/features/wallet/share_invoice_screen.dart
mobile/lib/features/wallet/wallet_change_notifier.dart
mobile/lib/features/welcome/welcome_screen.dart
mobile/lib/hybrid_logger.dart
mobile/lib/logger.dart
mobile/lib/main.dart
mobile/lib/simple_utc_printer.dart
mobile/lib/util/notifications.dart
mobile/pubspec.lock
mobile/pubspec.yaml

With this new logger we can easily log into a file and into the console.
Second commit is optional, let me know if you want to keep it or drop it. 
Initial few log files look like this: 
```
flutter: [I] TIME: 2023-10-06T15:41:17.320986 r: Initialized logger
flutter: [I] TIME: 2023-10-06T15:41:17.656526 Coordinator version: 1.3.0
flutter: [I] TIME: 2023-10-06T15:41:17.657005 Client is up to date: 1.3.0
flutter: [I] TIME: 2023-10-06T15:41:19.653350 App data will be stored in: /Users/bonomat/Library/Developer/CoreSimulator/Devices/BBD86D27-7B1E-4237-BBDB-34FF9F250C78/data/Containers/Data/Application/E8A20B9D-0E4D-4568-A60C-5FD5FA6337D4/Documents
flutter: [I] TIME: 2023-10-06T15:41:19.653961 Seed data will be stored in: /Users/bonomat/Library/Developer/CoreSimulator/Devices/BBD86D27-7B1E-4237 …
```

chore: replace logger framework

---

mobile/lib/features/wallet/onboarding/fund_wallet_modal.dart

Fixes an exception thrown at navigating after receiving a payment during funding the app.
```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for GoRouterDelegate:
setState() or markNeedsBuild() called during build.
This Router<Object> widget cannot be marked as needing to build because the framework is already in
the process of building widgets. A widget can be marked as needing to be built during the build
phase only if one of its ancestors is currently building. This exception is allowed because the
framework builds parent widgets before children, which means a dirty descendant will always be
built. Otherwise, the framework might not visit this widget during this …
```

fix: Do not navigate during widget build

---

CHANGELOG.md
mobile/lib/common/loading_screen.dart
mobile/lib/features/trade/domain/position.dart
mobile/lib/features/trade/position_change_notifier.dart
mobile/lib/features/trade/trade_screen.dart
mobile/lib/main.dart
mobile/lib/util/preferences.dart

Stores if a position is open in the preferences and reads from it at startup in a loading screen. Once loaded you will be transferred to the correct page.
I had to default the trade screen to the positions, as otherwise you would have always defaulted to the orders, since at load time the position is not there yet.
https://github.com/get10101/10101/assets/382048/58fef395-df8f-4f2d-b413-5d8531bead1d
resolves #1318

feat: Make trade / stable screen default if user has a position

---

justfile

Without this, I get
```
+ echo 'Wiping native 10101 app'
Wiping native 10101 app
+ '[' -d /home/restioson/Library/Containers/ ']'
/tmp/justV3YWUx/wipe-app: line 201: MACOS_PATH: unbound variable
```

fix(justfile): make `wipe` work on linux

---

mobile/lib/features/wallet/domain/destination.dart
mobile/lib/features/wallet/send/confirm_payment_modal.dart
mobile/lib/features/wallet/send/send_screen.dart

The amount was not editable when entering a plain on-chain address, because no amount was set. Requiring an amount to be set in all cases (zero if unknown) allows the ui validation to behave properly.

fix: Pay to on-chain address

---

Cargo.lock
coordinator/Cargo.toml
crates/bitmex-stream/Cargo.toml
crates/orderbook-client/Cargo.toml
crates/orderbook-commons/Cargo.toml
maker/Cargo.toml

Fixes potential security vulnerability; reported by dependabot:
https://github.com/get10101/10101/security/dependabot/18

chore(deps): Bump tungstenite crate to 0.20.1

---

mobile/lib/common/value_data_row.dart

A more robust fix for #1491 ; it ensures that we don't need to be cautious whenever we use ValueDataRow; the safe fallback is an empty spot in the value column.

fix(ui): Prevent exceptions on null values in ValueDataRow

---

coordinator/src/collaborative_revert.rs
mobile/native/src/ln_dlc/mod.rs

Apparently it can be that `original_funding_outpoint` is not set. In this case, we can fall back to `funding_txo`.
Also added two more log messages to see what is happening on the coordinator.

fix: funding tx not found

---

.github/workflows/build-release-binaries.yml

Would have needed this just now when our release randomly failed. 
Instead, I had to delete the release tag, the release itself and recreate everything.

feat: allow manual trigger of release flow

---

mobile/lib/features/trade/order_list_item.dart
mobile/lib/features/wallet/wallet_history_item.dart

This reverts commit 7c7d331cb327bb1bb1207ca2c6bf780c1bbc609a.
Lets maybe digest this a bit, but after looking at the app this evening, I kind of feel like the color green looks better than everything in purple. Happy to close that PR if you are convinced of how it currently looks :)

Revert "chore: Use 10101 purple instead of green"

---

coordinator/src/routes.rs
crates/ln-dlc-node/src/ln/channel_details.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/mod.rs
mobile/native/src/ln_dlc/mod.rs

Gets the current SCID which should be used to identify this channel for outbound payments. This should be used in Routes to describe the first hop or in other contexts where we're sending or forwarding a payment outbound over this channel.
This is either the ChannelDetails::short_channel_id, if set, or the ChannelDetails::outbound_scid_alias. See those for more information.
Obviously, the `inbound_scid_alias` was wrong since it is outbound from the coordinator point of view.

fix: Create route hint on the app side

---

crates/ln-dlc-node/src/seed.rs
mobile/lib/backend.dart
mobile/lib/common/init_service.dart
mobile/lib/common/loading_screen.dart
mobile/lib/common/routes.dart
mobile/lib/features/wallet/seed_screen.dart
mobile/lib/features/wallet/seed_words.dart
mobile/lib/features/welcome/new_wallet_screen.dart
mobile/lib/features/welcome/seed_import_screen.dart
mobile/lib/main.dart
mobile/lib/util/compare_coordinator_version.dart
mobile/lib/util/file.dart
mobile/native/migrations/2023-10-23-141646_remove_last_login/down.sql
mobile/native/migrations/2023-10-23-141646_remove_last_login/up.sql
mobile/native/src/api.rs
mobile/native/src/db/mod.rs
mobile/native/src/db/models.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/schema.rs
mobile/pubspec.lock
mobile/pubspec.yaml
mobile/test/util_test.dart

- Allow choice between new and imported wallet on first startup
- add screens where user can input the seed (with confirmation step)
- add backend support for seed recovery
- add unit test to doublecheck whether recovered seed is the same as exported

feat(app): Support on-chain wallet recovery

---

CHANGELOG.md
coordinator/src/admin.rs
coordinator/src/collaborative_revert.rs
coordinator/src/db/collaborative_reverts.rs
coordinator/src/message.rs
coordinator/src/orderbook/collaborative_revert.rs
crates/orderbook-commons/src/lib.rs
mobile/lib/common/collab_revert_change_notifier.dart
mobile/lib/common/domain/background_task.dart
mobile/lib/common/init_service.dart
mobile/native/src/event/api.rs
mobile/native/src/event/mod.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/orderbook.rs

- Collaborative revert is not retried once confirmed.
- The dlc channel and order state is cleaned up after a collab revert, allowing the user to continue using the app without having to re-install the app.
- Fixed calculation issue where the amounts were wrong if the dlc got stuck in a state where the ln channel balances have already been updated.
- Considered `unspendable_punishment_reserve` when calculating the trader and coordinators amount.
- Add dialog showing the user that the collab revert was (not) successful
- Fixed minor typos
- Removed dedicated collaborative revert message as it was redundant to the trader message

chore: Improving collaborative revert

---

Cargo.lock
Cargo.toml
coordinator/migrations/2023-10-26-060205_add_funding_details_to_collab_revert/down.sql
coordinator/migrations/2023-10-26-060205_add_funding_details_to_collab_revert/up.sql
coordinator/src/collaborative_revert.rs
coordinator/src/db/channels.rs
coordinator/src/db/collaborative_reverts.rs
coordinator/src/position/models.rs
coordinator/src/schema.rs
crates/coordinator-commons/src/lib.rs
crates/ln-dlc-node/src/node/mod.rs
crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/tests/collaborative_revert_position.rs
mobile/native/src/db/models.rs

By retrieving the channel signer through the channel monitor we are able to access the fund key of the original ln channel even though ldk closed and removed this channel.
Note: this patch includes a temporary dependency on rust-lightning. This will not be needed anymore once we upgrade to rust-lightning 116 because we can then access the channel keys directly.
Differently said, we might be able to drop this commit completely once we upgrade to rust-lightning 116
Note 2: the api to collab revert has changed: it now needs the funding tx id and vout, e.g. 
```bash
curl -d '{"channel_id":"1be2ef992aaae712cfb74a70da3f5295eb7fcfa711b13483d3c48a3767c446bd", "price":"28394", "fee_rate_sats_vb": 4, "txid": "bc46c467378ac4d38334b111a7cf7feb95523fda704ab7cf12e7aa2a99efe21b", "vout": 1}' -H …
```

fix: allow collab revert even if ln channel is closed

---

mobile/lib/features/welcome/new_wallet_screen.dart

- set background of scaffold to white to match the rest of the screen
- use dark status bar, needs to be done here again since it is not in the shell route.
- reduced the button border radius from 18 to 10.

chore: Set background of scaffold on new wallet

---

CHANGELOG.md
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
crates/tests-e2e/tests/collaborative_revert_position.rs
mobile/lib/features/wallet/send/send_screen.dart

Resolves https://github.com/get10101/10101/issues/1538

feat: drain on-chain wallet

---

mobile/lib/common/settings/settings_screen.dart

It's weird but adding an invisible box decoration makes the white space clickable.
fixes #1534

fix: Add invisible box decorator to settings clickable

---

CHANGELOG.md
Cargo.lock
crates/ln-dlc-node/src/node/dlc_manager.rs

Fixes #1547.
If we cannot load it because the deserialisation fails, we introduce a workaround that ensures that we can overwrite it and move on with the `DlcManager` initialisation.
This is generally not safe, but it unblocks us for the time being. We should nevertheless remove the workaround as soon as most users have updated to this patch.

Load persisted `rust-dlc` `ChainMonitor` whenever possible 

---

Cargo.lock

Building locally updates the `Cargo.lock` automatically. I think this should have happened when we updated the coordinator's `Cargo.toml`.

Update coordinator version in `Cargo.lock`

---

mobile/lib/common/application/switch.dart
mobile/lib/common/routes.dart
mobile/lib/features/welcome/loading_screen.dart
mobile/lib/features/welcome/onboarding.dart
mobile/lib/features/welcome/welcome_screen.dart
mobile/lib/util/preferences.dart

- The wallet is initialized once the toggles are confirmed on the welcome screen. (Preventing the user to skip over the disclaimer by restarting the app and uses the loading screen to show that the app is doing something)
- Add a custom switch component. Primarily copied from https://stackoverflow.com/a/60090216/8643355
- The email is now optional.
<details><summary>iPhone SE Screenshot</summary>
<p>
</p>
</details> 
https://github.com/get10101/10101/assets/382048/e80469f5-f614-40b1-8ab5-0b6b6adafb70

feat: Add beta disclaimer

---

crates/payout_curve/src/lib.rs

Afaik it should not happen as it is ensured in the pnl calculation. However, there might be some rounding errors happening at times. To ensure this is not happening we simply check that it's always greater 0 in a proptest.
Attempt to proof https://github.com/get10101/10101/issues/1563 but it didn't fail.

chore: ensure that payout curve cannot be negative

---

mobile/native/src/storage.rs

Apparently the backup and the delete key were different, but without any impact on the apps behaviour after restore.
Nevertheless, let's align it to be on the safe side.

fix: Align backup keys

---

mobile/lib/features/welcome/welcome_screen.dart

Otherwise, `_email` is not update and we will never register a given email.

fix: Save form on continue

---

.github/workflows/build-release-binaries.yml
coordinator/src/bin/coordinator.rs
coordinator/src/cli.rs
coordinator/src/node.rs
coordinator/src/node/resize.rs
coordinator/src/orderbook/async_match.rs
coordinator/src/orderbook/trading.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/dlc_manager.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/oracle.rs
crates/ln-dlc-node/src/tests/dlc/create.rs
crates/ln-dlc-node/src/tests/dlc/dlc_setup_with_reconnects.rs
crates/ln-dlc-node/src/tests/load/coordinator.rs
crates/ln-dlc-node/src/tests/mod.rs
maker/src/bin/maker.rs
mobile/native/src/ln_dlc/mod.rs

This is a preparation step allowing the coordinator to accept multiple oracles as argument, to be able to force-close outdated positions, that have not been migrated to the new oracle.
The oracle_pubkey defines what oracle to be used for proposing new dlc channels
related to https://github.com/get10101/cloud-conf/issues/233
----
The oracle data is passed to the coordinator arguments like that
```
--oracle [pubkey1]@[host1] --oracle [pubkey2]@[host2] --oracle_pubkey [pubkey2]
```
This will tell the coordinator to build 2 oracle clients and use the second to for dlc channel proposals.

feat: Support multiple oracles

---

coordinator/src/node/rollover.rs

The message also included the payout function which spammed the logs.

fix: Only print counterparty pubkey from rollover

---

crates/ln-dlc-node/src/node/mod.rs

The periodic check is already called in a loop by the `sub_channel_manager_periodic_check`. I don't see a reason to do it multiple times.
Also finalizing a force-closure with the `period_check` called from the manager lead to a panic, when trying to get the attestations from the oracle.
fixes #1586

fix: Do not call periodic check twice

---

coordinator/src/admin.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/fail_intercepted_htlc.rs
crates/ln-dlc-node/src/tests/multi_hop_payment.rs
crates/ln-dlc-node/src/tests/single_hop_payment.rs
maker/src/routes.rs
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

With the introduction of the backup we are spawning a tokio task on write. If this is called from a non tokio runtime we run into the following panic.
`Aborting after panic in task info: panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'`

fix: Spawn blocking on send payment

---

coordinator/src/admin.rs
crates/ln-dlc-node/src/node/invoice.rs
crates/ln-dlc-node/src/node/ln_channel.rs
crates/ln-dlc-node/src/tests/dlc/non_collaborative_settlement.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/fail_intercepted_htlc.rs
crates/ln-dlc-node/src/tests/multi_hop_payment.rs
crates/ln-dlc-node/src/tests/single_hop_payment.rs
maker/src/routes.rs
mobile/native/src/api.rs
mobile/native/src/backup.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/state.rs

Reverts the changes from https://github.com/get10101/10101/pull/1599 and https://github.com/get10101/10101/pull/1602 and uses the static tokio runtime to spawn the backup tasks.

fix: Spawn backup tasks from static tokio runtime

---

coordinator/src/orderbook/db/orders.rs
coordinator/src/orderbook/routes.rs
coordinator/src/orderbook/tests/sample_test.rs
coordinator/src/orderbook/websocket.rs
coordinator/src/routes.rs

I am surprised this didn't had a bigger impact, but apparently we where fetching also market orders.

fix: Fetch only limit orders

---

crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/tests/force_close_position.rs

I couldn't reproduce it locally, but it looks like the test sometimes fails as the counterparty was faster to broadcast the force-close transaction. That would result into a different sub channel state `SubChannelState::CounterOnChainClosed` which is never satisfied in our tests.
Logs from a failed test
`
2023-11-20T08:58:38.762568Z DEBUG ln_dlc_node::ln::event_handler: Received event event=ChannelClosed { channel_id: [128, 51, 43, 129, 47, 105, 245, 153, 151, 161, 145, 195, 201, 127, 71, 17, 80, 225, 87, 102, 210, 250, 85, 157, 98, 146, 203, 176, 165, 124, 246, 25], user_channel_id: 227848002640833202195941678669145496055, reason: HolderForceClosed }
`
Logs from a successful test
`
2023-11-20T09:40:36.121962Z DEBUG ln_dlc_node::ln::event_handler: Received event event=ChannelClosed { …

fix: Check for channel closed by counterparty

---

mobile/lib/backend.dart

This is already done at startup. Also, this additional await apparently impacts the startup performance. I assume its because a bdk lock is required somewhere which has to wait for the on-chain sync.

fix: Skip refreshing the lightning wallet on startup

---

CHANGELOG.md
mobile/lib/util/compare_coordinator_version.dart

This fixes an null error in case the shell is not yet loaded when the dialog should be shown. (also shows the dialog then)

fix: Use rootNavigatorKey context for alert dialog

---

crates/tests-e2e/src/test_flow.rs

The sub_channel_manager_periodic_check is only running every 30 seconds. Waiting for only 60 seconds has some chances that the force closure was not finalized in time, leaving the sub channel state still in `Closing` when the test fails.
Doubling the timeout should hopefully increase the chances of this test to succeed. Tested here https://github.com/get10101/10101/actions/runs/6944655389/job/18892309832?pr=1619

chore: Increase next wait time

---

crates/trade/Cargo.toml

Otherwise running the cfd test run into the following error
```
error: at least one of the `std` or `no-std` features must be enabled
--> /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitcoin-0.29.2/src/lib.rs:47:1
|
47 | compile_error!("at least one of the `std` or `no-std` features must be enabled");
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

chore: Add default features to bitcoin dependency

---

coordinator/src/admin.rs
coordinator/src/collaborative_revert.rs
coordinator/src/db/collaborative_reverts.rs
coordinator/src/lib.rs
coordinator/src/node.rs
coordinator/src/orderbook/collaborative_revert.rs
coordinator/src/position/models.rs
coordinator/src/routes.rs
crates/coordinator-commons/src/lib.rs
crates/orderbook-commons/Cargo.toml
crates/orderbook-commons/src/lib.rs
crates/payout_curve/tests/integration_proptests.rs
crates/tests-e2e/src/app.rs
crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/src/fund.rs
crates/tests-e2e/src/http.rs
crates/tests-e2e/src/lib.rs
crates/tests-e2e/src/setup.rs
crates/tests-e2e/tests/collaborative_revert_position_without_channel_details.rs
crates/tests-e2e/tests/force_close_position.rs
crates/tests-e2e/tests/open_position.rs
crates/tests-e2e/tests/restore_from_backup.rs
crates/tests-e2e/tests/rollover_position.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/orderbook.rs

Fixes #1546.
In situations where the collaborative revert protocol might be useful, it is likely that the channel will have been erased from the `ChannelManager`.
Before this patch we had unavoidable dependencies on the `ChannelManager`, but with this patch we are able to perform the protocol without looking for the relevant `ChannelDetails` via the `ChannelManager`.
---
Currently untested beyond the automatic test! Maybe @bonomat wants to give this a go since he created the original issue and implemented the feature.
---
A large chunk of the diff is formatting and style fixes. I should have split it up, but too late now 😞

Reduce collaborative revert reliance on `ChannelManager`

---

coordinator/src/lib.rs
coordinator/src/node.rs
coordinator/src/node/resize.rs
coordinator/src/position/models.rs
crates/tests-e2e/tests/collaborative_revert_position.rs
mobile/native/src/trade/position/mod.rs

We must not change the average entry price if the position is reduced as the user is not buying/selling more of the contract, but selling/buying it.
This resulted into the incorrect pnl calculation in case the position was reduced.

Fix position resize calculations: average execution price and closed DLC channel settlement amount

---

coordinator/src/message.rs
coordinator/src/node/rollover.rs
coordinator/src/orderbook/async_match.rs
coordinator/src/orderbook/collaborative_revert.rs
coordinator/src/orderbook/websocket.rs

Without that fixed we would have simply broke out of the loop and the task completed.
Note, the capacity of a 100 should have been enough, and it doesn't look like the channel got closed. Hopefully we learn more by logging errors when receiving a message from the channel.
fixes #1646

fix: Handle error on channel receive

---

CHANGELOG.md
mobile/lib/common/settings/app_info_screen.dart
mobile/lib/common/settings/settings_screen.dart

- Adds a link to our social media profiles on telegram, twitter, github and blog.
- Adds dividers between setting rows
- Makes the settings scrollable without hiding the back button.

chore: Add social media links to app info

---

CHANGELOG.md
coordinator/src/orderbook/websocket.rs
crates/commons/src/message.rs
mobile/native/src/logger.rs
mobile/native/src/orderbook.rs
mobile/native/src/state.rs

This was originally increased to ensure that a rollover is not failing if the app is open and the coordinator restarts while moving into the rollover window, as the rollover will fail.
However, this is a very edge case, that shouldn't happen very often and even if it's happening. The rollover will simply timeout and finish on the next restart of the app without any errors.
Reducing this timeout to 200ms gives the app a more ready feeling as the app will not wait 5s before reconnect and thus fetching the latest limit orders to get a price.

chore: Reduce websocket reconnect timeout to 200ms

---

mobile/lib/features/wallet/wallet_screen.dart

Fixes #1529. All I had to do was allow the scroll to be activated with all pointer devices, not just touch.

fix: allow pulldown refresh on desktop with mouse

---

mobile/lib/features/wallet/balance.dart

This was shifting the total balance annoyingly to the left, which made it not centered on the screen.
left: before, right: after (the lines are the same length)

fix: Remove unneeded fixed width from total balance

---

Cargo.lock

By bumping our two miniscript versions to later patch releases which include the fix backported from `miniscript:10`.
We were only hitting this when [building for Android and iOS](https://github.com/get10101/10101/actions/runs/7086216992), since this merge commit: 3615e5bd.
---
Related issue: https://github.com/rust-bitcoin/rust-miniscript/issues/549.

Fix overflow in `rust-miniscript` for iOS and Android builds

---

Cargo.lock
Cargo.toml
crates/ln-dlc-node/src/node/dlc_channel.rs
mobile/native/src/logger.rs

This _may_ be a fix for https://github.com/get10101/10101/issues/1697.
This is the reverting patch: https://github.com/lightningdevkit/rust-lightning/commit/121bc324.

Revert a `rust-lightning` patch

---

mobile/lib/features/wallet/send/send_lightning_screen.dart

With pre-defined amount:
Zero-value invoice:

Display pay-invoice amount title dynamically

---

coordinator/src/bin/coordinator.rs
coordinator/src/orderbook/trading.rs

Fix #1672.
---
Fixing this has made me realise that this is an antipattern that we have (very likely) been running into for a long time. That is,
using a `?` when setting up a spawned task and assuming that it will be handled somewhere.
Here it caused two problems:
1. It stopped a task that we did not want to stop.
2. It failed silently.
In some cases it might be acceptable to stop a task, but we don't want this to happen silently.
I will keep an eye out for this from now on. And I will audit the code base for instances where we use `?` when calling `pool.get()`.

Prevent `coordinator::orderbook::trading` task from stopping if getting DB connection times out

---

CHANGELOG.md
mobile/lib/common/routes.dart
mobile/lib/common/settings/delete_network_graph.dart
mobile/lib/common/settings/settings_screen.dart
mobile/native/src/api.rs

My mainnet app was not able to send any payments. After deleting and recreating the network graph it was working again. This is certainly not a fix for the payment issues, but it may help as a quick fix for others as well to unblock payments.

feat: Add delete network graph in settings

---

CHANGELOG.md
mobile/lib/features/wallet/receive_screen.dart

Resolves https://github.com/get10101/10101/issues/1736
I've simply left the icon on both buttons at all times

fix: make buttons in receive screen not jumpy

---

mobile/lib/features/swap/swap_amount_text_input_form_field.dart
mobile/lib/features/swap/swap_bottom_sheet.dart

Fixes #1711.
I did notice while doing this work the following:
1. Every time we update the margin or quantity, the channel details are fetched again - how often do we actually want this to happen?
2. There are some prices for which the minimum margin given by the validation is 1 sat less than what's actually needed to get a quantity of 1. This is hard to reproduce. Maybe worth opening a ticket for?

fix: fix errors in swap screen

---

crates/ln-dlc-node/src/tests/dlc/non_collaborative_settlement.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/channel_close.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/mod.rs
crates/ln-dlc-node/src/tests/multi_hop_payment.rs
crates/ln-dlc-node/src/tests/probe.rs
crates/ln-dlc-node/src/tests/single_hop_payment.rs
crates/tests-e2e/examples/fund.rs
crates/tests-e2e/src/maker.rs
crates/tests-e2e/tests/maker.rs
maker/src/routes.rs

Motivated by this [error](https://github.com/get10101/10101/actions/runs/7196185313/job/19600541210#step:12:2970) spotted on CI (thanks, @Restioson).
---
I think we actually need to do the same for production code. You want BDK and LDK to agree on the state of the blockchain at all times. Obviously this problem is more obvious in tests because we were explicitly mining a block and then triggering 1 out of 2 syncs. But we could get unlucky and things could blow up on mainnet too.

Trigger on/off-chain syncs back to back in tests

---

crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/ln/probes.rs
crates/ln-dlc-node/src/node/mod.rs
maker/src/bin/maker.rs
maker/src/lib.rs
maker/src/ln/event_handler.rs
maker/src/probing.rs

Fix #1632.
As the maker sends random probes through the coordinator and collects the results, the maker's scorer will get updated over time.
We can then share the scorer file with other peers connected to the coordinator (10101 apps), which should improve their payment experience.
This last part is not included in this PR because I want to see how this works in production before we actually support the app pulling the maker's scorer file.
---
Based on this [patch](https://git.bitcoin.ninja/index.cgi?p=ldk-sample;a=blobdiff;f=src/main.rs;h=1d6edb45006a70d53e8a3d466dd9968c3c8d1dfb;hp=6480805d92759eed4d90407ada06a3f6eb7f202f;hb=f47b6f50b85ef3770173cc8e4bcddd3662cb5d5e;hpb=37da86a8a1a3294f991657ecca49c19e7c2b043d) shared by Matt from LDK.

Instruct maker to send random probes every minute

---

CHANGELOG.md
coordinator/src/admin.rs
crates/ln-dlc-node/src/node/ln_channel.rs

With this we see if there are any pending/stuck HTLCs on an channels.
E.g. response looks like this for a channel with a pending HTLC
```
{
"channel_id": "cecff04ded3279da7638d82b5abeac2e4a878ed775f60525f9e21e910c6ca7e2",
"counterparty": "02ab77e8a40feef78116c4f6afbe5586e7e5954cf9d9425514fe757955c2c8537a",
"funding_txo": "e2a76c0c911ee2f92505f675d78e874a2eacbe5a2bd83876da7932ed4df0cfce:0",
"original_funding_txo": null,
"channel_type": "StaticRemoteKey: required, AnchorsNonzeroFeeHtlcTx: not supported, AnchorsZeroFeeHtlcTx: not supported, Taproot: not supported, SCIDPrivacy: not supported, ZeroConf: not supported, unknown flags: none",
"channel_value_satoshis": 200000,
"unspendable_punishment_reserve": 2000,
"user_channel_id": 1.2457119903510981e+38,
"feerate_sat_per_1000_weight": 253, …
```

feat: show pending balance on channels api

---

mobile/native/src/db/custom_types.rs
mobile/native/src/db/mod.rs
mobile/native/src/db/models.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs
mobile/native/src/ln_dlc/sync_position_to_subchannel.rs
mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/order/mod.rs

I was able to reject an old unacceptable sub channel offer with this, however, I was then in a broken state. See here: #1761

fix: reject pending offers

---

crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
mobile/lib/common/amount_and_fiat_text.dart
mobile/lib/common/amount_input_modalised.dart
mobile/lib/common/amount_text_input_form_field.dart
mobile/lib/common/edit_modal.dart
mobile/lib/common/intersperse.dart
mobile/lib/features/swap/swap_bottom_sheet.dart
mobile/lib/features/wallet/application/wallet_service.dart
mobile/lib/features/wallet/domain/confirmation_target.dart
mobile/lib/features/wallet/domain/fee.dart
mobile/lib/features/wallet/domain/fee_estimate.dart
mobile/lib/features/wallet/send/confirm_payment_modal.dart
mobile/lib/features/wallet/send/fee_picker.dart
mobile/lib/features/wallet/send/fee_text.dart
mobile/lib/features/wallet/send/send_onchain_screen.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

Fixes #1290, fixes #1177. Additionally, fees will be shown on the confirmation screen for lightning payments, too (though this would be easy to disable). This also includes a fix to setting the amount on the on-chain screen.
Before this is merged, I'd appreciate if someone can check if opening the keyboard correctly pushes up the drawer - I am not sure if this is the case as I can't compile for android anymore.
Some screenshots of the current UI - not at all the final state, just what I'm using for testing. Presented simply for an indicator of functional progress.
When selecting
On summary page
To do:

feat: configurable fee for sending on chain

---

mobile/lib/features/trade/async_order_change_notifier.dart
mobile/lib/features/trade/domain/order.dart
mobile/lib/features/trade/order_list_item.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/native/src/db/mod.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/orderbook.rs
mobile/native/src/trade/order/api.rs
mobile/native/src/trade/order/handler.rs

Fixes #1762.
Ultimately, it's still bad that we have no way of linking an order that is in `Filling` to a particular subchannel update. With such information we would be able to more confidently discard irrelevant orders and continue with the only relevant one.
I considered other approaches, but I think this is the simplest.

Move past multiple orders in `Filling` state

---

coordinator/src/bin/coordinator.rs
coordinator/src/node.rs
coordinator/src/settings.rs
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln/coordinator_event_handler.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/just_in_time_channel/create.rs
crates/ln-dlc-node/src/tests/mod.rs
maker/src/bin/maker.rs
mobile/native/src/ln_dlc/mod.rs

This is needed to actually prevent opening new jit channels.

fix: Parse wallet settings from actual settings

---

CHANGELOG.md
coordinator/src/admin.rs
crates/fund/src/coordinator.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/tests-e2e/tests/maker.rs
mobile/lib/features/swap/swap_bottom_sheet.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/wallet/balance_row.dart
mobile/lib/features/wallet/domain/wallet_balances.dart
mobile/lib/features/wallet/domain/wallet_info.dart
mobile/lib/features/wallet/send/send_lightning_screen.dart
mobile/lib/features/wallet/wallet_change_notifier.dart
mobile/lib/features/wallet/wallet_screen.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/node.rs
mobile/test/trade_test.dart

resolves https://github.com/get10101/10101/issues/1780
Off-chain balance only shows the `available` balance, i.e. after opening a position, the off-chain balance will be `0` because all the amounts are locked in the position.
See video
https://github.com/get10101/10101/assets/224613/e2e0f8da-1009-468d-98e4-5ade94b54f4e
In this video the price has been fixed so that the user does not make any profit nor loss which showed this bug: https://github.com/get10101/10101/issues/1799 and this one https://github.com/get10101/10101/issues/1800

feat: show dlc-channel balance

---

CHANGELOG.md
crates/ln-dlc-node/src/node/dlc_channel.rs

resolves #1783
If a user tries to open a new position he will just get an error. 
The error message is misleading as it just says `sorry, we couldn't match your order`. 
So I think we should really tackle https://github.com/get10101/10101/issues/1621 soon.

chore: don't allow more than one dlc-channel per user

---

crates/payout_curve/.gitignore
crates/payout_curve/examples/payout_curve.gp
crates/payout_curve/examples/payout_curve_csv.rs
crates/payout_curve/src/lib.rs

The example now produces a csv file which contains `<price>,<offerer>,<acceptor>`. This is useful to plot the payout for the coordinator(offerer) and trader (acceptor) in a single diagram.
I've also changed the gnuplot file which now produces an SVG so that one can zoom in and see more details.
Note: diagrams below where generated with a fee of 30%

chore: refactor payout curve example

---

CHANGELOG.md
coordinator/src/admin.rs
coordinator/src/lib.rs
coordinator/src/node.rs
crates/fund/examples/fund.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/tests/dlc_channel.rs
mobile/lib/common/channel_status_notifier.dart
mobile/lib/common/settings/channel_screen.dart
mobile/lib/common/settings/collab_close_screen.dart
mobile/lib/common/settings/force_close_screen.dart
mobile/lib/features/wallet/wallet_screen.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/channel_status.rs
mobile/native/src/ln_dlc/mod.rs

resolves #1785 
resolves #1786

feat: allow collab and force close DLC channel

---

CHANGELOG.md
coordinator/src/dlc_handler.rs
coordinator/src/node.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/tests/dlc_channel.rs
mobile/native/src/dlc_handler.rs
mobile/native/src/ln_dlc/node.rs

Checks on `on_connect` if the current dlc channel status is in offered.
- `OfferedChannel`: Automatically tries to accept the offer, if that fails the offer is attempted to be rejected. I think we do not need to check the maturity date outside of accepting the offer as the offer will fail anyways if the maturity date is in the past. If so we are continuing with rejecting the dlc channel offer.
- `SignedChannel(state: SettledReceived)`: Automatically accept the offer to close the position (settle the dlc channel)
- `SignedChannel(state: CollaborativeCloseOffered)`: Automatically accept the offer to collab close the dlc channel.
- `SignedChannel(state: RenewOffered)`: To be addressed with #1791 .
- Add plausibility checks before automatically accepting any offer.

feat: Recover from pending offer

---

webapp/frontend/lib/common/balance.dart
webapp/frontend/lib/wallet/send_screen.dart
webapp/frontend/lib/wallet/wallet_service.dart
webapp/src/api.rs
webapp/src/main.rs
webapp/src/subscribers.rs

feat: Send and receive on-chain funds

---

coordinator/src/node.rs
coordinator/src/position/models.rs

All the tests I ran locally where with a fixed price, so of course this only showed up in an environment where the price can actually change.
This also highlighted the fact that we were missing some tests, so I added them.
Fixes https://github.com/get10101/10101/issues/1840.

Use correct direction when computing settlement

---

Cargo.lock

To get rid of a transitive dependency on `time:0.1.45`, which contains a [vulnerability](https://github.com/get10101/10101/security/dependabot/4).

Update `chrono` to version 0.4.31

---

mobile/native/src/backup.rs

Without that fix the open and close position protocol was affected by the db backup to finish. That could lead to the trade dialog not showing a success message.
fixes #1847

fix: Run all of the db backup in a dedicated thread

---

CHANGELOG.md
webapp/Cargo.toml
webapp/src/main.rs

This allows us to send request from the webapp while in dev mode

chore: configure cors for webapp

---

CHANGELOG.md
Cargo.lock
mobile/native/src/trade/position/mod.rs
webapp/.gitignore
webapp/Cargo.toml
webapp/frontend/lib/common/http_client.dart
webapp/frontend/lib/common/model.dart
webapp/frontend/lib/common/version_service.dart
webapp/frontend/lib/trade/new_order_service.dart
webapp/frontend/lib/trade/open_position_service.dart
webapp/frontend/lib/trade/order_and_position_table.dart
webapp/frontend/lib/trade/trade_screen.dart
webapp/frontend/lib/trade/trade_screen_order_form.dart
webapp/frontend/lib/wallet/wallet_service.dart
webapp/src/api.rs
webapp/src/main.rs

This was a bit of a PITA 🙈
resolves #1863

feat (webapp): show open position

---

Cargo.lock
webapp/Cargo.toml
webapp/frontend/lib/common/scaffold_with_nav.dart
webapp/frontend/lib/main.dart
webapp/frontend/lib/trade/open_position_service.dart
webapp/frontend/lib/trade/order_and_position_table.dart
webapp/frontend/lib/trade/orderbook_service.dart
webapp/frontend/lib/trade/trade_screen_order_form.dart
webapp/frontend/lib/wallet/wallet_service.dart
webapp/src/api.rs
webapp/src/main.rs
webapp/src/subscribers.rs

resolves https://github.com/get10101/10101/issues/1872

Make use of latest quote

---

webapp/src/main.rs

It's cumbersome to deal with providing a valid cert path if we don't even want to start securely.

chore: Only depend on the certs directory if secure flag is set

---

webapp/Dockerfile

Also generates the certs on the default path so that the certs directory doesn't have to be set if the default certs should be used.
tested locally with the following
```
mkdir data
docker run \
--name webapp \
--rm \
-v ./data:/data \
-p 3001:3001 -it \
ghcr.io/holzeis/webapp:0.1.2  \
--coordinator-endpoint=021025118ede915d626f7da184d75af7281dca965dd91a06993cf9d21fe4ca54e5@34.89.166.156:9045 \
--data-dir=/data \
--esplora=http://api.10101.finance:3000 \
mainnet
```

fix: Create certs as 1000 user

---

coordinator/src/collaborative_revert.rs
coordinator/src/message.rs
crates/tests-e2e/src/app.rs
crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/src/setup.rs
crates/tests-e2e/tests/collaborative_revert.rs
mobile/native/src/api.rs

Reintroduce collaborative revert e2e test

---

coordinator/src/admin.rs
coordinator/src/node.rs
coordinator/src/routes.rs
crates/ln-dlc-node/src/fee_rate_estimator.rs

The fee rate was taken from our setting, which was too low. That was most likely a left over from the sub channel implementation where the funding transaction was not dependent on the fee rate set on the offered contract.

fix: Use fee estimator for dlc transaction fees

---

mobile/lib/common/amount_and_fiat_text.dart
mobile/lib/features/trade/trade_value_change_notifier.dart
mobile/lib/features/wallet/send/fee_text.dart

This was constantly throwing errors in the logs whenever we got a new price as it is not allowed to update a late field multiple times.
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_price@1021144427' has already been initialized.
#0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:192:5)
#1      TradeValuesChangeNotifier._price= (package:get_10101/features/trade/trade_value_change_notifier.dart:20:20)
#2      TradeValuesChangeNotifier.updatePrice (package:get_10101/features/trade/trade_value_change_notifier.dart:102:5)
#3      TradeValuesChangeNotifier.notify (package:get_10101/features/trade/trade_value_change_notifier.dart:119:7)
#4      new EventService.create.<anonymous closure> …
```

fix(mobile): Make price nullable

---

coordinator/migrations/2024-01-25-005650_add_legacy_collaborative_reverts_table/down.sql
coordinator/migrations/2024-01-25-005650_add_legacy_collaborative_reverts_table/up.sql
coordinator/src/admin.rs
coordinator/src/collaborative_revert.rs
coordinator/src/db/legacy_collaborative_reverts.rs
coordinator/src/db/mod.rs
coordinator/src/orderbook/collaborative_revert.rs
coordinator/src/position/models.rs
coordinator/src/routes.rs
coordinator/src/schema.rs
crates/commons/src/collab_revert.rs
crates/commons/src/message.rs
crates/tests-e2e/tests/collaborative_revert.rs
maker/src/orderbook_ws.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/orderbook.rs

This can be removed once all LN-DLC channels in production have been closed.
---
I can't easily add an e2e test for this because some of the code to even establish an LN-DLC channel was already removed. So I ran manual tests instead.
1. Build app and coordinator on version `1.7.4`.
2. Start environment and open channel and position with app.
3. Shut down coordinator.
4. Re-start coordinator on this branch.
5. Trigger collab revert.
```
curl -X POST localhost:8000/api/admin/channels/legacy-revert -d '{"channel_id":"9d8b2495465de9cf7173a1304aaaa5f27ec9035e762386863e0403becaacc797", "txid": "96c7accabe03043e868623765e03c97ef2a5aa4a30a17371cfe95d4695248b9d", "vout": 1, "coordinator_amount": 110000, "fee_rate_sats_vb": 5, "price":"40000"}' -H "Content-Type: application/json"
```
6. Verify logs …

Reintroduce support for legacy collaborative revert of LN-DLC channels

---

CHANGELOG.md
mobile/lib/common/init_service.dart
mobile/lib/features/trade/trade_value_change_notifier.dart
mobile/native/src/channel_trade_constraints.rs
mobile/native/src/ln_dlc/mod.rs
mobile/test/trade_test.dart

fixes https://github.com/get10101/meta/issues/295

chore: Enforce minimum quantity to 500 on dlc channel open

---

mobile/lib/features/wallet/application/wallet_service.dart
mobile/lib/features/wallet/receive_screen.dart
mobile/lib/features/wallet/send/confirm_payment_modal.dart
mobile/lib/features/wallet/send/execute_payment_modal.dart
mobile/lib/features/wallet/send/fee_picker.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

Tested on phone and simulator. Let's see if this was really the issue :/
resolves https://github.com/get10101/10101/issues/1892
Note: I made a small UI change: Allow users to copy the address only (without `bitcoin:`) in front of it.

Fix: send on-chain 

---

coordinator/src/admin.rs
coordinator/src/routes.rs

We may need this until all LN-DLC channels are closed. This serves as a less efficient alternative to collaborative revert, as it doesn't require cooperation with the counterparty and it _may_ work when either party lacks all the data needed to perform the collaborative revert protocol.
---
I manually tested this by opening an LN-DLC channel (with a position) on version 1.7.4 and force-closing it using the same coordinator but updated to this branch. I've verified that the LN money is claimed on both sides after mining sufficient blocks. The DLC money is a bit more finicky because we have to mess with the expiry time, but given that this was already tested and that we haven't changed any of that code and that it was tested in `ln-dlc-node` on version 1.7.4, I don't see any risk.

Add endpoint to force-close LN-DLC channel

---

CHANGELOG.md
Cargo.lock
mobile/lib/common/amount_text_field.dart
mobile/lib/common/application/channel_info_service.dart
mobile/lib/features/trade/application/trade_values_service.dart
mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/native/src/api.rs
mobile/native/src/channel_trade_constraints.rs
mobile/test/trade_test.dart

- Sets the min quantity to 1 dollar
- Sets the min margin to 1 sat or 250k sat if there is no dlc channel yet.
https://github.com/get10101/10101/assets/382048/1a0d8d33-98ec-424b-971f-009f24888156

feat: Add min margin to channel trade constraints

---

coordinator/src/node.rs

this is because we are currently heavily overspending

chore: reduce confirmation target to background

---

Cargo.lock
mobile/native/src/ln_dlc/channel_status.rs

I think it's correct to assume that a `Established` channel is one that has a position. But a `RenewFinalized` channel is still pending
completion of the renew protocol and will eventually transition back to `Established`.
This behaviour can be seen in our `can_open_and_settle_offchain` test in the `ln-dlc-node` crate.

Map `SignedChannelState`  to `ChannelStatus` correctly

---

Cargo.lock
Cargo.toml

We had an issue where the app would panic because we fell behind in the protocol. This panic has been removed in this commit https://github.com/bonomat/rust-lightning-p2p-derivatives/commit/e49030e785408f0fd4da077f63f8101cc0b2436e.
This commit was built on top of our latest commit https://github.com/p2pderivatives/rust-lightning/commit/121bc324fec54cfb8b0335ec013f596ffc9d6f9f
I didn't feel good about pushing this to our usual fork in https://github.com/p2pderivatives/rust-lightning because it sounds dangerous and hence pushed it onto my own fork. We can drop this again in the future. 
(hopefully) resolves most panics.
Resolves https://github.com/get10101/10101/issues/1911

fix: remove one possible panic

---

CHANGELOG.md
Cargo.lock
Cargo.toml
coordinator/src/bin/coordinator.rs
coordinator/src/db/positions.rs
coordinator/src/dlc_handler.rs
coordinator/src/node.rs
crates/ln-dlc-node/src/dlc_message.rs
crates/ln-dlc-node/src/ln/dlc_channel_details.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-storage/src/lib.rs
crates/payout_curve/Cargo.toml
crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/src/setup.rs
crates/tests-e2e/tests/basic.rs
crates/tests-e2e/tests/open_position.rs
crates/tests-e2e/tests/reject_offer.rs
mobile/native/Cargo.toml
mobile/native/src/dlc_handler.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs
mobile/native/src/logger.rs
mobile/native/src/trade/order/mod.rs

Adds a handling for dlc channel offer, settle offer and renew offer. If the corresponding accept handling fails the protocol now attempts to reject the offer. 
If the app identifies that there is a pending offer (dlc channel, settle offer or renew offer) it will automatically try to reject it. I think this is the safest we can do given that 1. for dlc channels the utxo might not be reserved anymore and 2. (more importantly) the price might have changed again, so we probably don't want to continue a dlc protocol that started some days ago.
`rust-dlc` has been enhanced for a reject dlc channel offer flow allowing to reject dlc channel offers.
This change also adds a handling for updating the app layer (app, coordinator) state of the order and position.
- **Set timeout on `RenewOffered` …

feat: Reject dlc channel, settle and renew offer

---

crates/ln-dlc-node/src/ldk_node_wallet.rs

This is useful to see what height we have synced up to.
On the path of debugging https://github.com/get10101/10101/issues/1894 I wandered down the path of questioning our wallet design and if we miss a block or don't sync up to the latest height. This additional log field might help.

chore: print latest height after sync

---

Cargo.lock
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/wallet.rs
crates/tests-e2e/src/bitcoind.rs
crates/tests-e2e/src/setup.rs
crates/tests-e2e/tests/basic.rs
crates/tests-e2e/tests/open_position.rs
crates/tests-e2e/tests/open_position_small_utxos.rs
crates/tests-e2e/tests/reject_offer.rs
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

Fixes #1912.
There are more problems that can lead to #1912, but this is definitely one of them as was demonstrated with ccbd0c55cb5682b2c5e38de4f8e9046f5e55013f.
In a different PR I will address the problem of `rust-dlc` underestimating how much money each party needs to bring in to cover the fees for all the transactions that are involved in a DLC channel.

Smarter coin selection for DLC funding transaction

---

crates/ln-dlc-node/src/tests/mod.rs

The maturity time was hard coded to Feb 3rd 2024 which has expired now and was breaking our ln-dlc-node tests.
This change dynamically calculates a maturity time 7 days in the future.

chore: Set maturity time of dummy contract to the future

---

Cargo.lock
Cargo.toml

Points to the fixup in rust-dlc removing the test log
https://github.com/p2pderivatives/rust-dlc/commit/0786724f947af867d72bd221fa99db492360f936

chore: Remove test log

---

CHANGELOG.md
coordinator/src/node.rs
mobile/native/src/dlc_handler.rs

We need that as due to the bug https://github.com/get10101/10101/issues/1912 users have tried multiple times to submit their order. And since we don't check if the user already has an offered channel, we simply offer another one, which then again fails.
That will leave us with multiple positions in state `Proposed` and offered dlc channels. By simply rejected all offered on reconnect we clean up those positions and dlc channels.

chore: Reject all pending dlc channel offers

---

.github/workflows/android-fastlane.yml
CHANGELOG.md
justfile

Untested because I didn't want to play around with all the env variables on my fork :/
This will upload the APKs as artifact to the GitHub action. If the APKs work, we can use https://github.com/softprops/action-gh-release (or similar) to upload the APKs to our release. 
Step towards https://github.com/get10101/10101/issues/1642

feat: upload android apk

---

crates/ln-dlc-node/src/ln/dlc_channel_details.rs

Useful to know which output belonged to the funding tx.

feat: also show funding tx vout

---

crates/ln-dlc-node/src/dlc_message.rs

I opted to revert this change as it was a mere refactoring and it's not worth to break serializing and deserializing `last_outbound_dlc_messages.message` for it. Even if it would have had only a minor downside (being that the last message could not be resend and producing the below error).
fixes
```
[ERROR] TIME: 2024-02-03T15:39:38.448459Z r: Failed to process on connect event. unknown variant `temporaryChannelId`, expected one of `Offer`, `Accept`, `Sign`, `SettleOffer`, `SettleAccept`, `SettleConfirm`, `SettleFinalize`, `RenewOffer`, `RenewAccept`, `RenewConfirm`, `RenewFinalize`, `RenewRevoke`, `CollaborativeCloseOffer`, `Reject` at line 1 column 21 peer: 02dd6abec97f9a748bf76ad502b004ce05d1b2d1f43a9e76bd7d85e767ffb022c9
```

revert: Serialize channel message

---

.github/workflows/android-fastlane.yml

this action is executed from the workspace dir, hence, we need to provide the full path

fix: use correct path

---

coordinator/src/admin.rs
crates/ln-dlc-node/src/ln/dlc_channel_details.rs

This will sort the channels retrieved via `/api/admin/dlc_channels` by their `state` first and then by their signed_channel_state` if the `state` is equal.

feat(coordinator): sort dlc channels by state

---

Cargo.lock
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/fee_rate_estimator.rs
crates/ln-dlc-node/src/node/mod.rs
crates/mempool/Cargo.toml
crates/mempool/src/lib.rs

Replace our esplora fee rate estimator with a mempool.space client.

feat: replace fee rate estimator with mempool.space client

---

CHANGELOG.md
Cargo.lock
webapp/Cargo.toml
webapp/src/main.rs

Example mostly copied from here https://github.com/tokio-rs/axum/blob/main/examples/low-level-rustls/src/main.rs
Not sure if going low level makes this more stable, but lets see and hope for the best :)
maybe fixes #1938

refactor: Replace axum server with a low level rust-tls implementation

---

.github/workflows/ci.yml
crates/ln-dlc-node/src/tests/dlc_channel.rs
docker-compose.yml
justfile

Removes lnd and chopsticks from our dev setup.
The nigiri chopsticks container was only useful to create a wallet and generate the first 200 blocks. Other than that its just a technical burden.
This patch removes the chopstick service from our dev setup by manually creating a wallet and mining 300 blocks when running just docker.
‼️ docker-compose up -d on an wiped environment will not be sufficient anymore. You will have to use `just docker` to start the environment, which ensures that wallet is created and 101 blocks are mined.
‼️ Chopsticks weirdly always mined a block when broadcasting a transaction. This is changed now that we got rid of chopsticks.

chore: Cleanup docker compose

---

CHANGELOG.md
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs
crates/ln-dlc-node/src/node/wallet.rs
mobile/lib/common/routes.dart
mobile/lib/common/settings/settings_screen.dart
mobile/lib/common/settings/wallet_settings.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

I've decided against putting it into the recovery screen as the recommendation should be to increase this number incrementally. The reason is, the higher they gap, the slower the sync. 
If this setting would have been only available on the recover screen, a user might need to reset the app again to sync again, hence, it is kinda required to be used from a fully setup app. 
I've created a new category in the settings screen, which can come handy in the future, e.g. edit the esplora endpoint.
This fixes a problem where we don't see money in the wallet after recovering the wallet.
https://github.com/get10101/10101/assets/224613/10dc53a7-45cc-4537-a707-5ca83077986c

feat: allow to increase the number of addresses to sync for

---

CHANGELOG.md
coordinator/migrations/2024-02-08-105459_change_user_email_to_contact_detail/down.sql
coordinator/migrations/2024-02-08-105459_change_user_email_to_contact_detail/up.sql
coordinator/src/admin.rs
coordinator/src/db/user.rs
coordinator/src/orderbook/tests/registration_test.rs
coordinator/src/routes.rs
coordinator/src/schema.rs
crates/commons/src/lib.rs
mobile/lib/common/routes.dart
mobile/lib/common/service_status_notifier.dart
mobile/lib/common/settings/settings_screen.dart
mobile/lib/common/settings/user_screen.dart
mobile/lib/features/welcome/seed_import_screen.dart
mobile/lib/features/welcome/welcome_screen.dart
mobile/lib/util/preferences.dart
mobile/native/src/api.rs
mobile/native/src/orderbook.rs
mobile/native/src/trade/users/mod.rs

resolves #1727 
https://github.com/get10101/10101/assets/224613/78c2d9fa-0da6-46b1-8e76-33d0a2d94c4e

feat(mobile): allow users to change contact details

---

Cargo.lock
Cargo.toml
coordinator/src/dlc_handler.rs
mobile/native/src/dlc_handler.rs

The `Channel::CollaborativelyCloseOffered` state did not include who offered, so the `on_reconnect` logic incorrectly always tried to accept a collab close offer even if it has been proposed by themselves.
`rust-dlc` does not store that information, so I fix that in https://github.com/p2pderivatives/rust-dlc/commit/ba68a7bc5db4bdafb24f27fd485507fbf4322f81 by adding a `is_offer` flag to the `Channel::CollaborativelyCloseOffered` state. (analog to how it is done on the `Channel::RenewOffered` state)

fix(dlc_handler): Only accept collab close offer if not our own

---

mobile/lib/features/wallet/send/send_onchain_screen.dart

Proof of concept for #1925; major issue is how this should be handled in the amount field (see https://github.com/get10101/10101/issues/1925#issuecomment-1918602574). This is one possible solution but isn't the greatest as
1) If the fee increases it'd be over the amount again
2) It doesn't actually use the draining logic
That being said, it is still editable by the user instead of being an entirely new mode of interaction, which is a plus.
Resolves #1925

feat: add 'Max' button to sending on-chain screen

---

CHANGELOG.md
Cargo.lock
coordinator/migrations/2024-02-09-152833_add_nickname_to_user_table/down.sql
coordinator/migrations/2024-02-09-152833_add_nickname_to_user_table/up.sql
coordinator/src/db/positions.rs
coordinator/src/db/user.rs
coordinator/src/leaderboard.rs
coordinator/src/orderbook/tests/registration_test.rs
coordinator/src/orderbook/trading.rs
coordinator/src/routes.rs
coordinator/src/schema.rs
crates/commons/src/lib.rs
mobile/lib/common/settings/user_screen.dart
mobile/native/Cargo.toml
mobile/native/src/api.rs
mobile/native/src/lib.rs
mobile/native/src/names.rs
mobile/native/src/trade/users/mod.rs

Leader board has now a nickname which can be configured in the app (or is random generated on registration). 
There is no way to opt-out of the leader board at the moment. 
Also, the leaderboard api allows for defining a start and end date. 
e.g. use with 
`curl 'localhost:8000/api/leaderboard?top=3&category=Pnl&start=2024-02-11&end=2024-02-13' -v | jq .`
resolves [#341](https://github.com/get10101/meta/issues/341)

feat: finetune leader board

---

.github/workflows/android-fastlane.yml
justfile

Resolves #2025 
I've opted for also the split bundles, because the full one is so big.
This will generate different apk bundles: 
```
81M Feb 13 14:28 app-arm64-v8a-full-release.apk
40B Feb 13 14:29 app-arm64-v8a-full-release.apk.sha1
57M Feb 13 14:28 app-armeabi-v7a-full-release.apk
40B Feb 13 14:29 app-armeabi-v7a-full-release.apk.sha1
288M Feb 13 14:29 app-full-release.apk
40B Feb 13 14:29 app-full-release.apk.sha1
94M Feb 13 14:28 app-x86_64-full-release.apk
40B Feb 13 14:29 app-x86_64-full-release.apk.sha1
```

feat: build android fat bundle and split bundles

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/ln-dlc-node/src/tests/dlc_channel.rs
crates/ln-dlc-node/src/tests/mod.rs

Fixes https://github.com/get10101/10101/issues/2022.
3348fd7c4cae1e7fb13ac1c0e9c8cab6522eb4d1 adds 3 patches to our `rust-dlc` branch[^1]:
- https://github.com/p2pderivatives/rust-dlc/commit/6ad11f5dc32923a8a5c28df36fd7eb19007be20c.
- https://github.com/p2pderivatives/rust-dlc/commit/a01f92bd12e7422703f05dda0a1a3942ab447eae.
- https://github.com/p2pderivatives/rust-dlc/commit/1534c18731fd42d8e4219ad9c01beeb2d6f3a808.
Only the last one is relevant for this PR, but the other ones are probably good too.
[^1]: Atm the changes live in a separate branch: https://github.com/p2pderivatives/rust-dlc/commits/feature/ln-dlc-channels-10101-with-sign-psbt-fee-fix/.

Do not overpay funding transaction fees by 2x

---

.github/workflows/ios-fastlane.yml

this helps us to prevent errors where just was cached before

fix: force install just

---

CHANGELOG.md
crates/ln-dlc-node/src/node/dlc_channel.rs
mobile/native/src/channel_trade_constraints.rs
mobile/native/src/ln_dlc/mod.rs

The balance of the counterparty is the difference from the users balance and the total collateral.
Before we were calculating the max amount based on the initial collateral of the counterparty which can obviously change.
fixes #2002

fix(validation): Calculate counterparty balance from channel state

---

CHANGELOG.md
coordinator/src/node.rs
coordinator/src/routes.rs
coordinator/src/trade/mod.rs
crates/commons/src/message.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
mobile/native/src/orderbook.rs

If the trade execution takes longer than 30 seconds the http request times out and the thread gets killed.
However, the spawned blocking thread to propose the dlc channel is finishing and sending the offer message. That leads to the coordinator sending the dlc message without updating the 10101 meta data (e.g. creating the position, updating order, etc.)
This also applies to the renew and close position flows.
Note, this is not fixing the issue of why proposing a dlc channel would take such a long time, but will fix the issue that the user may end up in a broken state.
https://github.com/get10101/10101/assets/382048/0e15657b-a98c-4dfb-aacd-258b0b1c96e6

fix(trade): Spawn trade execution in dedicated task

---

Cargo.lock
Cargo.toml

We will be using our own fork of `rust-dlc` until:
- We can drop all the LN-DLC features. 
- `p2pderivatives/rust-dlc#master` includes certain patches currently only found in the LN-DLC branch.
Perhaps we will always want to maintain our own fork, although ideally we don't diverge too much from the original.

Use a fork of `rust-dlc` for now

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/ln-dlc-node/src/ldk_node_wallet.rs
crates/ln-dlc-node/src/ln_dlc_wallet.rs

Unreserves locked outpoints if a channel gets rejected. This would otherwise only happen if the coordinator gets restarted.
Adds the following commits to rust-dlc
- Set contract to rejected if channel gets cancelled. https://github.com/get10101/rust-dlc/pull/4/commits/12ee7b717a70e2b9da8d15cc919aa3c95543e10e
- Adds the unreserve utxos api to the wallet trait: https://github.com/get10101/rust-dlc/pull/4/commits/38c91beefa2e11938fae74e19593a1e707230be1

feat(wallet): Unreserve locked outpoints if channel gets rejected

---

coordinator/src/trade/mod.rs

In the past we set it to  because our feerate estimation was too far off. Now,  would be too low, hence, we switch to  which translates to  from mempool, i.e. it should get confirmed within 1h

fix(channel): use higher fee rate when opening a channel

---

CHANGELOG.md
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/native/src/db/models.rs
mobile/native/src/trade/order/handler.rs

I am not exactly sure why this is fixing the issue, but my assumption is the following.
If we receive the order match (async via websockets) before the `post_new_order` http request has finished. We'd still hold an open connection and the write lock on the order.
I presume this leads to the order match processing to fail because of `Could not load order from db: cannot acquire database connection: timed out waiting for connection`. But I am not sure why that would result into the processing of the order match running into a timeout when trying to get a connection.
When the `post_new_order` finally finishes the lock is freed up. I guess afterwards the pool would return connections again but we are already stuck because we do not send the trade request anymore (since processing the match …

fix: Insert channel params before posting new order

---

CHANGELOG.md
mobile/lib/features/welcome/loading_screen.dart
mobile/native/src/db/models.rs

So far, a failed order needed a reason when converting between types. However, we failed to do so when setting orders to failed. I've relaxed this constraint now. If there is no reason in the db, we assume an `Unknown` reason in the frontend. At the same time, we ensure that we set a reason when setting all orders to failed
Resolves #2031 
We should roll out a release after this is merged as it blocks at least one user and myself.

fix: relaxed constraint on failed orders

---

CHANGELOG.md
coordinator/Cargo.toml
mobile/pubspec.yaml

Hi @bonomat!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/7964714275.
I've bumped the versions in the manifest files in this commit: 3a48a06195658bf183821a7fed729a93aa8928df.

Release version 1.8.10

---

.github/workflows/android-fastlane.yml
.github/workflows/ios-fastlane.yml

I believe our CI issue is coming from the fact that we use two different macos versions but cache flutter for the same key

fix: use platform dependent cache

---

CHANGELOG.md
Cargo.lock
webapp/Cargo.toml
webapp/frontend/lib/common/channel_state_label.dart
webapp/frontend/lib/common/version_service.dart
webapp/frontend/lib/main.dart
webapp/frontend/lib/settings/channel_change_notifier.dart
webapp/frontend/lib/settings/channel_screen.dart
webapp/frontend/lib/settings/channel_service.dart
webapp/frontend/lib/settings/dlc_channel.dart
webapp/frontend/lib/settings/dlc_channel.g.dart
webapp/frontend/lib/settings/seed_screen.dart
webapp/frontend/lib/settings/settings_screen.dart
webapp/frontend/lib/settings/settings_service.dart
webapp/frontend/lib/settings/settings_service.g.dart
webapp/frontend/lib/trade/order_history_table.dart
webapp/frontend/lib/trade/position_table.dart
webapp/frontend/lib/trade/quote_service.dart
webapp/frontend/lib/trade/trade_confirmation_dialog.dart
webapp/frontend/lib/trade/trade_screen.dart
webapp/frontend/lib/wallet/history_screen.dart
webapp/frontend/lib/wallet/wallet_service.dart
webapp/frontend/pubspec.yaml
webapp/src/api.rs

resolves [#2061](https://github.com/get10101/10101/issues/2061)
Note: the error in the video is already fixed.
https://github.com/get10101/10101/assets/224613/c6fdb9c1-62c4-4942-ae90-defdfe714425

Webapp: Allow user to close/force-close channel

---

Cargo.lock
coordinator/src/cli.rs
webapp/src/cli.rs

Patch https://github.com/get10101/10101/commit/cd04992884b88d911c04b48c075e4c23883cfa0f changed the name of the `esplora` CLI argument to `electrs` for correctness. But the change was introduced in a backwards-incompatible manner.
This patch solves that issue by introducing an alias for the CLI argument with the original name.
All this applies to both the coordinator and the webapp.

Fix backwards-incompatible CLI change

---

Cargo.lock
Cargo.toml
crates/tests-e2e/tests/e2e_rollover_position.rs

See https://github.com/get10101/rust-dlc/commit/0191dc4.

Let app force-close after channel renewal

---

.github/workflows/android-fastlane.yml
.github/workflows/ios-fastlane.yml
justfile

Using default cache settings will stop us from caching cargo binaries. This might slow down our production build but hopefully gets rid of random errors where libraries were already installed.

Simplify cache

---

coordinator/example-settings/prod-coordinator-settings.toml
coordinator/example-settings/test-coordinator-settings.toml
coordinator/src/orderbook/routes.rs
coordinator/src/settings.rs
crates/commons/src/order.rs
mobile/native/src/trade/order/orderbook_client.rs

only whitelisted makers are allowed to post limit orders
Note: this is a breaking change: 
- apps which do not upgrade, cannot post orders --> I think this is a feature and not a bug :)
- our old maker won't work anymore --> we need to deploy our new maker in production

feat: sign orders and whitelist makers

---

coordinator/src/node/expired_positions.rs

Still not perfect that we set the position to `Closing`, but when we rework the position handling, we will get rid of the position state anyways - so I am not touching this for now.

chore: Set expired async orders to expired

---

justfile

This is not longer in this repo anymore

fix: remove line that runs clippy on maker/

---

CHANGELOG.md
crates/tests-e2e/src/setup.rs
crates/tests-e2e/tests/e2e_close_position.rs
crates/tests-e2e/tests/e2e_collaborative_close_channel.rs
crates/tests-e2e/tests/e2e_collaborative_revert.rs
crates/tests-e2e/tests/e2e_open_position_small_utxos.rs
mobile/lib/backend.dart
mobile/lib/features/wallet/balance_row.dart
mobile/lib/features/wallet/domain/wallet_balances.dart
mobile/lib/features/wallet/domain/wallet_info.dart
mobile/lib/features/wallet/send/send_onchain_screen.dart
mobile/lib/features/wallet/wallet_change_notifier.dart
mobile/lib/features/wallet/wallet_screen.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/ln_dlc/node.rs
webapp/src/api.rs

Let the app start even if the wallet sync fails.
If the wallet sync fails the balance will be set to `None`, telling the UI that we were unable to determine the balance.
fixes: #2075

fix: Handle wallet sync error during startup

---

Cargo.lock
Cargo.toml
coordinator/Cargo.toml
coordinator/src/admin.rs
coordinator/src/bin/coordinator.rs
coordinator/src/node/connection.rs
coordinator/src/routes.rs
crates/commons/Cargo.toml
crates/commons/src/message.rs
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/networking.rs
crates/ln-dlc-node/src/networking/axum.rs
crates/ln-dlc-node/src/networking/tcp.rs
crates/ln-dlc-node/src/networking/tungstenite.rs
crates/ln-dlc-node/src/node/connection.rs
crates/ln-dlc-node/src/node/mod.rs
crates/orderbook-client/Cargo.toml
crates/orderbook-client/src/lib.rs
mobile/native/Cargo.toml
mobile/native/src/config/mod.rs
mobile/native/src/orderbook.rs

This PR replaces all instances of TCP with WebSockets when the `ln_net_native_ws` or `ln_net_wasm_ws` features are enabled. This is step 1 for 10101 WASM :tada: 
The new, default, `ln_net_tcp` carries out the old behaviour. When it is not enabled, the node will not listen for incoming TCP connections. The coordinator supports both TCP and WS connections. WS connections simply connect to its HTTP endpoint at `/` with a Websocket upgrade header.
There is a _potential_ breaking protocol change in how we handle pings/pongs with the orderbook. I have swapped uses of `tungstenite` in transitive dependencies of `native` to the `tokio_tungstenite_wasm` crate, which is a facade over `tungstenite` and WASM websockets (depending on target). Since WASM websockets can't directly intercept …

Replace TCP with WebSockets (when feature gate enabled)

---

crates/tests-e2e/tests/e2e_reject_offer.rs

Fixes https://github.com/get10101/10101/issues/2072.

fix(test): Wait for a few seconds before retrying opening a dlc channel after rejection

---

mobile/lib/common/more_info.dart
mobile/lib/common/settings/app_info_screen.dart
mobile/lib/common/settings/share_logs_screen.dart

Fix https://github.com/get10101/10101/issues/2076.
The share button wasn't working on desktop anyway. On Linux it is just not supported. On Mac we heard that it did not work.
Desktop users (not officially supported) can now copy the log file location, find the log file using a file explorer, and share it with us.

Show log file location on desktop

---

mobile/lib/features/trade/trade_bottom_sheet_tab.dart

Removes the info icons from order modal on the balance and quantity.
fixes https://github.com/get10101/meta/issues/350

fix: Remove info icons on order modal

---

CHANGELOG.md
Cargo.lock
Cargo.toml
coordinator/src/collaborative_revert.rs
crates/ln-dlc-node/src/ln/dlc_channel_details.rs
mobile/lib/common/dlc_channel_change_notifier.dart
mobile/lib/common/domain/dlc_channel.dart
mobile/lib/common/settings/channel_screen.dart
mobile/native/src/dlc_channel.rs
mobile/native/src/ln_dlc/mod.rs
webapp/src/api.rs

Adds the closing txid to the dlc channels api and the channels screen in the settings (see screenshot below).
depends on https://github.com/get10101/rust-dlc/pull/13
Note this is a breaking change. Old closed channels can't be read anymore. But given that old closed channel state don't provide any valuable information, I think this is acceptable.

Feat: Add closing tx

---

Cargo.lock
webapp/Cargo.toml

No being super optimistic, but maybe the latest axum-login release fixes the issue with the randomly unresponsive webapp (https://github.com/get10101/10101/issues/1938)
It looks like axum-login had issues with deadlocks in the past, but with tower-sessions those deadlock should have been fixed. Bumping from `0.12` to `0.13.1` also bumps the `tower-session` dependency. So this might help 🤞.

chore(webapp): Bump axum-login dependency to 0.13.1

---

Cargo.lock
Cargo.toml
coordinator/src/collaborative_revert.rs
crates/ln-dlc-node/src/dlc_wallet.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/tests/dlc_channel.rs
mobile/lib/common/dlc_channel_service.dart
mobile/lib/features/trade/channel_configuration.dart
mobile/lib/features/trade/trade_bottom_sheet.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/wallet/domain/wallet_history.dart
mobile/lib/features/wallet/wallet_history_item.dart
mobile/lib/util/constants.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs
mobile/test/trade_test.dart

Fixes #2042.
https://github.com/get10101/10101/assets/9418575/9976d4d2-155b-4c12-8be3-8ec65530b5e1
_The video does not correspond to the latest version, but it's close enough._
---
See https://github.com/get10101/rust-dlc/pull/5 for the `rust-dlc` side of things.

Display more fee information when opening a DLC channel

---

.github/workflows/create_release.yml

As discussed in our last demo. We can skip creating manual change log entries if we are creating proper pull request titles.

chore(ci): Create pre-releases with generated release notes

---

coordinator/src/bin/coordinator.rs
coordinator/src/campaign.rs
coordinator/src/db/user.rs
coordinator/src/lib.rs
coordinator/src/message.rs
coordinator/src/notifications.rs
coordinator/src/routes.rs

Adds an admin api allowing to send targeted push notifications to a list of users using their node ids. Note, if the user opted to not receive notifications, he will not get that campaign message.
With the `dry_run` flag you can test to how many users the message will be sent to and validate if the message is as expected before actually sending it.
```
$ curl localhost:8000/api/admin/campaign/push -d '{"node_ids":["027775c06af68dd0fbd1591a3da81afd13f7680c015ec48a76ae290bf48225a486"], "title": "test", "message": "this is a test", "dry_run": false }' -H "Content-Type: application/json"
Sending push notification campaign (title: test, message: this is a test to 1 users%
```
fixes https://github.com/get10101/meta/issues/364

feat: Add admin api to send targeted push notifications

---

coordinator/src/node/rollover.rs

The recovery logic has been replaced generally with retrying to send the `last_outbound_dlc_message` this also applies to the rollover. Hence we should not rollback to the latest state if the app reconnects in an intermediate state.
fixes #2137

fix(rollover): Remove outdated rollover recovery logic

---

mobile/lib/common/scaffold_with_nav_bar.dart
mobile/lib/main.dart

This was the background color before the flutter upgrade. Also fixing the issue with the background color of the candlestick chart.
|                                       |						|
|:-------------------------------------:|:-------------------------------------:|
| ![Simulator Screenshot - iPhone 15 Pro - 2024-03-04 at 10 29 29](https://github.com/get10101/10101/assets/382048/272257b2-f738-4aa8-a356-f9d32a1531b4) | ![Simulator Screenshot - iPhone 15 Pro - 2024-03-04 at 10 29 20](https://github.com/get10101/10101/assets/382048/dfd70187-6458-4bd5-9856-667081fc6bdb) |

chore(app): Change background color back to grey

---

coordinator/migrations/2024-02-29-142400_add_dlc_action/down.sql
coordinator/migrations/2024-02-29-142400_add_dlc_action/up.sql
coordinator/src/db/custom_types.rs
coordinator/src/db/dlc_protocols.rs
coordinator/src/db/positions.rs
coordinator/src/db/trade_params.rs
coordinator/src/dlc_protocol.rs
coordinator/src/node.rs
coordinator/src/node/rollover.rs
coordinator/src/schema.rs
coordinator/src/trade/mod.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/tests-e2e/src/coordinator.rs
crates/tests-e2e/tests/e2e_close_position.rs

Adds a `dlc_protocol_type` to the `dlc_protocols` table, allowing us to show what action triggered the dlc protocol. I opted to adding this enum, as it is helpful in deciding post processing actions, and the renew protocol is used for rollover and opening positions, so it would be ambiguous picking that information from the `dlc_messages`. 
```
orderbook=# select protocol_type, previous_protocol_id, protocol_id, contract_id, channel_id, protocol_state from dlc_protocols where trader_pubkey='02e66db0280277b35f88b1a1fcf58f8b2208568b6c7ea9eb071d894836865bef63';
protocol_type |         previous_protocol_id         |             protocol_id              |                           contract_id                            |                            channel_id                            | …
```

chore(dlc_protocol): Track rollovers in dlc protocol table

---

coordinator/src/admin.rs
coordinator/src/routes.rs
mobile/lib/common/settings/emergency_kit_screen.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

This might become very handy in case the protocol got stuck in an intermediate state. Unfortunately this will not help if one side has already reached the final state, while the other hasn't.
e.g. helps to recover from that https://github.com/get10101/10101/issues/2137

chore(emergency kit): Add option to rollback channel to last stable state

---

mobile/native/src/ln_dlc/node.rs

Unlike rejecting a dlc channel offer if accepting fails, the `Channel::Offered` and `Contract::Offered` have not been stored to the dlc store.
Hence, there is no `rust-dlc` state to be cleaned up. However, `rust-dlc` expects the `Channel::Offered` to be found by it's `dlc_channel_id`, which if it can't will fail the function.
This patch implements the reject only on the application layer, but we might want to consider moving that code to `rust-dlc`
Prevents users from running into bugs like this https://github.com/get10101/10101/issues/2131 to end up in a stuck state.

chore(channel offer): Reject a dlc channel offer if the processing fails

---

crates/commons/src/lib.rs
mobile/lib/common/domain/background_task.dart
mobile/lib/common/full_sync_change_notifier.dart
mobile/lib/common/init_service.dart
mobile/lib/common/settings/wallet_settings.dart
mobile/native/src/event/api.rs
mobile/native/src/event/mod.rs
mobile/native/src/ln_dlc/mod.rs

Fixes https://github.com/get10101/10101/issues/2130.
With the recent upgrade to `bdk:1.0.0`, we dropped existing wallet DBs in favour of a new format. This meant that a user would have to manually populate the new wallet DB to be able to see their wallet history and funds.
This is not a very good user experience, as at least some users would be surprised by this. This is why we have decided to execute a full wallet sync on startup if we find an old wallet DB. Once complete, we delete the old wallet DB since the data is irrelevant and we do not want to run a full sync on startup every time.
---
The message is now updated based on the state of the background task :tada:  (Thanks, @holzeis).

Perform full sync of app on-chain wallet on startup if needed

---

coordinator/src/node.rs

chore(channel): Ignore invalid collab close offers

---

.github/workflows/draft_new_release.yml
Cargo.lock
coordinator/migrations/2024-03-06-1135500_add_version_to_user/down.sql
coordinator/migrations/2024-03-06-1135500_add_version_to_user/up.sql
coordinator/src/check_version.rs
coordinator/src/db/user.rs
coordinator/src/leaderboard.rs
coordinator/src/lib.rs
coordinator/src/node/rollover.rs
coordinator/src/orderbook/async_match.rs
coordinator/src/orderbook/routes.rs
coordinator/src/orderbook/tests/registration_test.rs
coordinator/src/orderbook/websocket.rs
coordinator/src/routes.rs
coordinator/src/schema.rs
crates/commons/src/lib.rs
crates/commons/src/message.rs
crates/orderbook-client/examples/authenticated.rs
crates/orderbook-client/src/lib.rs
mobile/lib/features/trade/domain/order.dart
mobile/native/Cargo.toml
mobile/native/src/api.rs
mobile/native/src/db/models.rs
mobile/native/src/orderbook.rs
mobile/native/src/trade/order/api.rs
mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/order/mod.rs
mobile/native/src/trade/order/orderbook_client.rs
mobile/native/src/trade/users/mod.rs
webapp/src/api.rs

I opted to use the Cargo.toml version instead of the pubspec.yaml version as it is easier to access from rust and should probably anyways be bumped with every release.
A minor downside of this is now that we have to different sources for the version. However, both versions are bumped by the same ci pipeline during `draft_new_release` - so eventually the source is the same.
https://github.com/get10101/10101/assets/382048/e0b4c9d2-5e85-4373-8894-11df107a8a9d
fixes #2141
fixes #1748

feat(trade): Block users from trading with an old app version 

---

coordinator/src/admin.rs
coordinator/src/routes.rs

This is necessary for one of the steps in https://github.com/get10101/meta/issues/381.

Allow coordinator to run full sync via HTTP API

---

.github/workflows/draft_new_release.yml

Also, cleans up some redundant steps.
follow-up PR from https://github.com/get10101/10101/pull/2174

fix(ci) cargo set-version needs the package not path

---

webapp/frontend/lib/common/scaffold_with_nav.dart
webapp/frontend/lib/trade/leverage_slider.dart
webapp/frontend/lib/trade/trade_screen_order_form.dart
webapp/frontend/pubspec.yaml

Resolves #2154 
https://github.com/get10101/10101/assets/224613/4aef9539-aa74-4496-a778-a4e9ea37b9e2

feat(webapp): add leverage slider

---

webapp/frontend/devtools_options.yaml
webapp/frontend/lib/common/truncate_text.dart
webapp/frontend/lib/main.dart
webapp/frontend/lib/settings/channel_screen.dart
webapp/frontend/lib/wallet/history_screen.dart
webapp/frontend/lib/wallet/onchain_payment_history_item.dart
webapp/frontend/lib/wallet/receive_screen.dart
webapp/frontend/lib/wallet/walle_history_detail_dialog.dart
webapp/frontend/lib/wallet/wallet_change_notifier.dart
webapp/frontend/lib/wallet/wallet_screen.dart

resolves https://github.com/get10101/10101/issues/1927
https://github.com/get10101/10101/assets/224613/7dac6402-af1e-4237-bb15-c64869ff98d8

feat(web): show transaction details in a dialog

---

Cargo.lock
crates/ln-dlc-node/Cargo.toml
crates/ln-dlc-node/src/lib.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/node/wallet.rs
crates/ln-dlc-node/src/on_chain_wallet.rs
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

Fixes https://github.com/get10101/10101/issues/2190.
When the user is about to send on-chain and is typing the send amount, we dynamically calculate a fee estimate so that we can update the screen as they update the value.
This is nice, but the user will inevitably start by typing in small amounts for which calculating a fee does not make economical sense.
We enhance the library code to handle this case explicitly by using a error enum variant `EstimateFeeError::SendAmountBelowDust`. We can then leverage this in the app backend to simply ignore this kind of error.

Do not error when user is typing send amount

---

crates/tests-e2e/src/app.rs
crates/tests-e2e/src/setup.rs
crates/tests-e2e/tests/e2e_collaborative_revert.rs
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

Fixes https://github.com/get10101/10101/issues/2082 [^1].
In the past we were concerned about running all these tasks together, but after the `bdk` upgrade and the pivot away from Lightning there should be no problems. Also, any error that might occur during `sync_dlc_channels` is simply logged and does not interfere with updating the wallet history and balance.
A nice consequence of this change is that if a user triggers a wallet refresh and a fund transaction or a collaborative close transaction is found to be confirmed, the corresponding channel should update automatically, ensuring that the app's state is up-to-date and ready to keep trading.
[^1]: In my testing, I didn't find a problem that prevented the app from transitioning to the correct state. Instead, I noticed that it would …

Run DLC channels checks during wallet refresh

---

coordinator/migrations/2024-03-10-042249_add_delete_state_to_order/down.sql
coordinator/migrations/2024-03-10-042249_add_delete_state_to_order/up.sql
coordinator/src/bin/coordinator.rs
coordinator/src/dlc_protocol.rs
coordinator/src/node.rs
coordinator/src/orderbook/db/custom_types.rs
coordinator/src/orderbook/db/orders.rs
coordinator/src/orderbook/routes.rs
coordinator/src/routes.rs
coordinator/src/trade/mod.rs
coordinator/src/trade/websocket.rs
crates/commons/src/message.rs
crates/commons/src/order.rs
mobile/native/src/orderbook.rs

This new websocket will send trade/position updates as seen from the coordinator's perspective.
No need to do an indepth review, but please let me know what you think about this approach and I'll continue

feat: websocket for sending position/trade updates

---

crates/ln-dlc-node/src/on_chain_wallet.rs

It turns out that we don't need to watch literaly all the UTXOs ever :facepalm:

Only sync UTXOs owned by the wallet

---

Cargo.lock
Cargo.toml
coordinator/src/routes.rs
crates/ln-dlc-node/src/blockchain.rs
crates/ln-dlc-node/src/dlc_wallet.rs
crates/ln-dlc-node/src/node/mod.rs
crates/ln-dlc-node/src/tests/dlc_channel.rs
mobile/native/src/ln_dlc/mod.rs

Fixes https://github.com/get10101/10101/issues/2205.
With the update to `rust-dlc`, we no longer need to run `periodic_chain_monitor` periodically, nor does `rust-dlc` have to process blocks independently of the our on-chain wallet.
Matching pull request in our `rust-dlc` fork: https://github.com/get10101/rust-dlc/pull/14.
---
If the tests pass, I think this is okay :D

Remove `periodic_chain_monitor`

---

.esplora.env
.github/workflows/ci.yml
.gitignore
docker-compose.yml

This will allow us to overwrite the esplora environment variables to point to the correct electrs if run on a remote machine.
⚠️ Note, the file_env argument used in docker-compose requires at least v2.24
If you haven't already make sure to upgrade your docker-compose version as otherwise you won't be able to run `docker-compose up`
I also had to allow cors on our test setup as electrs and esplora are running on different ports. We could have used our nginx reverse proxy to circumvent that issue, but I figured its easier to simply allow cors on our test setup.
fixes https://github.com/get10101/cloud-conf/issues/257

chore(test): Add environment file for esplora

---

coordinator/src/node/expired_positions.rs
coordinator/src/orderbook/db/orders.rs
coordinator/src/orderbook/tests/sample_test.rs
crates/commons/Cargo.toml
crates/commons/src/order.rs
mobile/native/src/trade/order/mod.rs

Note: this is a breaking change as old formats will be serialized differently. 
Creating NewOrders with an old version will simply fail until the user upgrades.

Fix: make NewOrderRequest serialization deterministic

---

coordinator/src/orderbook/routes.rs

We have a specific function for deleting orders. Update would do the same, but this is easier to follow.

fix(app): use specific function to delete an order

---

coordinator/src/admin.rs
crates/ln-dlc-node/src/ln/contract_details.rs

```
{
"dlc_channel_id": "467d121ab8f5ba7f0d64bce2f7e78f34cf61b8b16edad88685240082ef05d094",
"counter_party": "03cb9f87a078e4a35c7cfd3aaf3a144b23cc52433ef6d5772ceb84b12fd1f935d5",
"channel_state": "Signed",
"signed_channel_state": "Established",
"update_idx": 281474976710653,
"fee_rate_per_vb": 3,
"funding_txid": "d48266275348fe69bb070f7c8888116a3190157a30e2d2cb4fd03fbfbf8fec94",
"funding_tx_vout": 2,
"closing_txid": null,
"contract_id": "48dc031ca469e145a92829a88ba625acb55029473c0c1ce5be79bf95244dbcd6",
"temporary_contract_id": "9c5e653bf7211f2c122f26d4032e34c684c03c3d0ceece2ef1a9802a9bc25040",
"contract_state": "Confirmed",
"offered_funding_sats": 342325,
"accepted_funding_sats": 344379,
"event_id": "btcusd1710460800",
"user_email": "",
"user_registration_timestamp": …
```

chore: Add trader and coordinator reserve to dlc channels api

---

webapp/frontend/web/index.html

`/favicon.png` didn't seem to have been copied over. This works though.

fix(webapp): favicon and title

---

Cargo.lock
coordinator/src/admin.rs
coordinator/src/bin/coordinator.rs
coordinator/src/node/rollover.rs
coordinator/src/routes.rs
coordinator/src/scheduler.rs
crates/tests-e2e/src/coordinator.rs
mobile/lib/features/trade/async_order_change_notifier.dart
mobile/lib/features/trade/rollover_change_notifier.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs
mobile/native/src/orderbook.rs
mobile/native/src/trade/position/handler.rs

fixes #2226 
fixes #2200 
- Rollover api has been moved to admin
- The coordinator now checks on a p2p connection if the users position needs to get rolled over
- Combines the logic for checking rollover from job an on connect, fixing the issue of notifying the user about the rollover window if there is already an expired position. (Note, the job did not check if the position was already expired)
- Adds a small fix to wait for the current context to become available before opening a dialog (async match and rollover)
- Connects to the coordinator on the websocket before starting the node. That prevents a possible race condition where the p2p connection could be already established but the websocket connection isn't.

chore(rollover): Directly propose rollover on p2p connection

---

mobile/native/src/ln_dlc/mod.rs

With https://github.com/get10101/10101/pull/2198/ we are now depending on the node to be set in the state when syncing the node.
This can end up in a race condition during startup as the task might already try to run a sync before the node is actually set into the state.
This fix moves setting the node state right after the node is constructed, ensuring that the node is available for `sync_node` when needed.
fixes #2245

fix: Set node state once node is created

---

mobile/lib/util/compare_coordinator_version.dart

This will show the dialog on the wallet / trade screen instead of the onboarding screen. Giving the user more time to react on the message.
https://github.com/get10101/10101/assets/382048/792033b1-04a8-4455-ad95-428f509f76eb
fixes #2249

fix: Show new version dialog on shell context

---

.github/actions/setup-fvm/action.yml
.github/workflows/android-fastlane.yml
.github/workflows/build-release-binaries.yml
.github/workflows/ci.yml
.github/workflows/docker.yml
.github/workflows/ios-fastlane.yml
.gitignore
README.md
justfile
mobile/.fvmrc
webapp/.gitignore
webapp/frontend/.fvmrc

This allows us to have different flutter versions for webapp and mobile. It is needed, because the webapp can be built best with the current `beta` version. Using latest `stable` will break the webapp in firefox and we would need to fall back to a different renderer which comes at the cost of performance.
This might be controversial but I was debugging issue #2234 and upgraded flutter to `beta` which solved an issue at least @holzeis is aware off: the latest flutter version does not work flawlessly in firefox - to make it work we had to switch to a different renderer (which was done in[`a8646e1` (#2081)](https://github.com/get10101/10101/pull/2081/commits/a8646e153e9768ad5da32ccd2a8d5bc64563e63d)). However, this actually comes at performance and responsiveness cost - which I thought was …

chore: introduce fvm (flutter version manager)

---

crates/commons/src/message.rs

Fixes https://github.com/get10101/10101/issues/2261.
Does this do it, @holzeis?

Keep context for `TradingError::Other`

---

coordinator/src/orderbook/async_match.rs
coordinator/src/orderbook/trading.rs

This must have been somehow slipped through. We don't need to spawn a thread here anymore, since the trade is already executed in a dedicated thread.

chore: Do not spawn on trade execution

---

mobile/lib/common/recover_dlc_change_notifier.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/native/src/ln_dlc/node.rs

fixes some issues with the recover dialog being displayed after the app got closed in the middle of a protocol.
fixes #2262 
fixes #2263 (169ad6b5c9de22d8a1f4af9783095d71805b59fb)

chore: Wait for current context to get available when showing recover dlc dialog

---

mobile/lib/common/settings/force_close_screen.dart

Otherwise it could happen that we don't see the swipe button as the state is not yet refreshed.

fix: Refresh dlc channels when opening force close channel screen

---

crates/ln-dlc-node/src/ln/dlc_channel_details.rs
mobile/lib/common/dlc_channel_change_notifier.dart
mobile/lib/common/domain/dlc_channel.dart
mobile/lib/common/settings/channel_screen.dart
mobile/native/src/dlc_channel.rs
webapp/frontend/lib/settings/channel_screen.dart
webapp/src/api.rs

chore: Show settle transaction txid on dlc channels api

---

.github/workflows/ci.yml
crates/commons/src/lib.rs
crates/commons/src/price.rs
crates/dev-maker/src/main.rs
crates/dev-maker/src/orderbook_client.rs
justfile

This should help with flaky e2e tests and improve the dev experience as well as fix a problem where we saw expired orders in the app.

dev/app: A few fixes and clean-ups

---

coordinator/src/admin.rs
coordinator/src/emergency_kit.rs
coordinator/src/lib.rs
coordinator/src/routes.rs

- Adds an admin api to resent the renew revoke message
- Adds an emergency kit to recreate the position from the signed channel and last failed order. This might be needed if the app set the order to fail, which will block the app from recreating the app. I opted to not make the code smarter when processing the `RenewRevoke` message but rather add an emergency kit feature. That will hopefully be less failure prune.
fixes https://github.com/get10101/meta/issues/413

chore: Add admin api to resend renew revoke message

---

coordinator/src/dlc_handler.rs
coordinator/src/emergency_kit.rs
coordinator/src/node.rs
coordinator/src/node/channel.rs
coordinator/src/node/rollover.rs
coordinator/src/trade/mod.rs
crates/ln-dlc-node/src/networking/tcp.rs
crates/ln-dlc-node/src/node/connection.rs
crates/ln-dlc-node/src/node/dlc_channel.rs
crates/ln-dlc-node/src/node/event.rs
crates/ln-dlc-node/src/tests/dlc_channel.rs
crates/ln-dlc-node/src/tests/mod.rs
mobile/native/src/dlc_handler.rs
mobile/native/src/emergency_kit.rs
mobile/native/src/ln_dlc/node.rs

The message will firstly be stored into the last outbound dlc messages table. This will ensure as well that once we create a response we won't lose it anymore if something goes wrong afterwards.
Once the processing was successful the last dlc message is sent.
resolves #2127

fix: Only send dlc messages if processing was successful

---

coordinator/migrations/2024-03-22-145200_add_total_collateral_to_dlc_channels/down.sql
coordinator/migrations/2024-03-22-145200_add_total_collateral_to_dlc_channels/up.sql
coordinator/src/admin.rs
coordinator/src/db/dlc_channels.rs
coordinator/src/node/channel.rs
coordinator/src/schema.rs

feat: Add coordinator and trader funding collateral to dlc channels

---

.github/workflows/android-fastlane.yml
.github/workflows/ios-fastlane.yml

The cache step was missing the path input, but apparently the cache wasn't even used anymore. Removing it hopefully fixes #2302

chore(ci): Remove unused cache step

---

.github/workflows/android-fastlane.yml
.github/workflows/deliverables-push-main.yml
.github/workflows/ios-fastlane.yml

I noticed that we checked on changes of the old `ios.yml` instead of the `ios-fastlane.yml`. Also the `android-app` did check on changes on the `ios-fastlane.yml`.

chore(ci): Check if *-fastlane file has changed

---

.github/workflows/docker.yml
justfile

This is needed for CI where we can't interact with the terminal and answer the question with `yes`.
For local flutter version and channel use
```
just gen
```
For overwriting the channel use
```
just gen beta
```

fix: allow to overwrite flutter version

---

mobile/lib/features/trade/channel_configuration.dart
mobile/native/src/ln_dlc/node.rs

Fixes https://github.com/get10101/10101/issues/2309.
With an overestimation we can be sure that the user won't run into problems during coin selection. Obviously they will not be able to use the true maximum, but the difference is small. We can never realistically hit the true maximum anyway.

Overestimate funding TX fee when calculating max usable on-chain balance

---

crates/ln-dlc-node/src/on_chain_wallet.rs

Fixes #2222.
The original logic was flawed because it would correctly show 1 confirmation when the transaction was included in a block, but it would subsequently deduct 1 confirmation after the second confirmation.
We were already doing this correctly for the `Blockchain` struct, so there is nothing to fix there.

Compute confirmations correctly

---

coordinator/src/node/expired_positions.rs
coordinator/src/orderbook/routes.rs
coordinator/src/orderbook/trading.rs
coordinator/src/routes.rs
crates/dev-maker/src/orderbook_client.rs

This is needed to prevent race conditions where a client tries to delete an order before it was inserted. This could happened because before this patch we were processing and inserting order asyncronously.

chore: store orders in db immediately in route

---

coordinator/src/db/positions.rs
coordinator/src/dlc_protocol.rs

We were using the closing trade trader direction instead of the position direction.

Calculate coordinator position PNL correctly

---

Cargo.lock
coordinator/Cargo.toml
coordinator/src/check_version.rs

With this patch we say `patch`-releases are compatible with older versions

feat: introduce semantic versioning

---

coordinator/src/node/expired_positions.rs
coordinator/src/orderbook/db/orders.rs
coordinator/src/orderbook/routes.rs
coordinator/src/orderbook/tests/sample_test.rs
crates/commons/src/order.rs
crates/dev-maker/src/main.rs
crates/dev-maker/src/orderbook_client.rs
mobile/lib/common/amount_input_modalised.dart
mobile/lib/common/amount_text_input_form_field.dart
mobile/lib/common/domain/model.dart
mobile/lib/features/trade/application/order_service.dart
mobile/lib/features/trade/application/trade_values_service.dart
mobile/lib/features/trade/channel_configuration.dart
mobile/lib/features/trade/domain/position.dart
mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_value_change_notifier.dart
mobile/lib/features/wallet/receive/receive_usdp_dialog.dart
mobile/lib/features/wallet/send/confirm_payment_modal.dart
mobile/lib/features/wallet/send/fee_picker.dart
mobile/lib/features/wallet/send/send_onchain_screen.dart
mobile/native/src/trade/order/handler.rs
mobile/native/src/trade/order/mod.rs
mobile/native/src/trade/order/orderbook_client.rs
mobile/test/trade_test.dart
webapp/frontend/lib/common/amount_text_input_form_field.dart
webapp/frontend/lib/trade/trade_screen_order_form.dart
webapp/frontend/lib/wallet/send_screen.dart

Extracted from https://github.com/get10101/10101/pull/2282

[breaking-api-change] A bit of refactoring 

---

mobile/ios/Runner.xcodeproj/project.pbxproj

I was only able to test this with an ios version 15.0 as older version are not available to download for me anymore. I would still keep compatibility to 12.0 as it may still work.

chore: Add ios compatibility to starting from 12.0

---

mobile/native/src/dlc_handler.rs

fix: Do not publish recover dlc background task if settled closing

---

mobile/lib/common/app_bar_wrapper.dart
mobile/lib/features/trade/trade_screen.dart

I think it looks better if the trading pair is shown in the app bar instead directly below it. It makes the components a little bit better aligned. Happy to drop that PR if you disagree.. (but I hope you don't :))
| before |	after |
|:-:|:-:|
| ![IMG_A3F1E78B6A77-1](https://github.com/get10101/10101/assets/382048/0ddbeacc-3e81-4b2b-a641-eb0799e3cd66) | ![image](https://github.com/get10101/10101/assets/382048/da04d92f-8dac-4b22-b301-0e801cf65d55) |

chore: Move trading pair to app bar title

---

mobile/pubspec.lock
mobile/pubspec.yaml
webapp/frontend/lib/common/scaffold_with_nav.dart
webapp/frontend/lib/main.dart
webapp/frontend/lib/wallet/send_screen.dart
webapp/frontend/pubspec.yaml

Since we no longer use `Flogs`, we don't need this dependency override[^1]. It was creating problems in CI[^2] (and locally too I suppose).
[^1]: https://github.com/zubairehman/Flogs/issues/87.
[^2]: https://github.com/get10101/10101/actions/runs/8565195140/job/23472971318?pr=2352#step:9:357.

Remove unneeded Flutter dependency override

---

mobile/lib/features/trade/domain/trade_values.dart
mobile/native/src/api.rs
mobile/native/src/ln_dlc/mod.rs

The max quantity could be set to 0 at startup as it is only recalculated when we get a price update. Before that patch we could have received a price before the node was started, for which the on-chain balance could not get determined. Leaving the max quantity at 0 until the next price is received.
Additionally the max quantity was set to 0 when we only received an ask or bid price.
fixes #2353

fix: Subscribe to the websocket after the node has started

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/8575214332.
I've bumped the versions in the manifest files in this commit: 76708dc9cd5e5d78a4652f26f4967f883131e591.

Release version 2.1.1

---

coordinator/src/payout_curve.rs

In response to https://github.com/get10101/10101/pull/2352#discussion_r1554574504.

Clarify payout function test

---

coordinator/migrations/2024-04-03-105900_add_coordinator_liquidation_price/up.sql

follow up to review remarks on https://github.com/get10101/10101/pull/2354

chore: Fix liquidation migration script for coordinator leverage = 1

---

mobile/ios/PrivacyInfo.xcprivacy
mobile/ios/Runner.xcodeproj/project.pbxproj
mobile/ios/Runner/Info.plist

Since solution 1 did not work, let's try with solution 2 as described [here](https://github.com/FlutterFlow/flutterflow-issues/issues/2527#issuecomment-1998885560)
fixes https://github.com/get10101/meta/issues/400

fix: Create dedicated ios privacy info manifest

---

mobile/native/migrations/2024-04-09-105312_ensure_old_orders_have_matching_fee/down.sql
mobile/native/migrations/2024-04-09-105312_ensure_old_orders_have_matching_fee/up.sql
mobile/native/src/db/mod.rs
mobile/native/src/db/models.rs
mobile/native/src/trade/order/handler.rs

resolves #2382 (hopefully). 
It ensures that this bug cannot happen again and sets the matching fee for existing orders in the db. 
My interpretation is that this error came from the fact that we introduced a new field `matching_fee_sats` which was obviously not set for existing orders.

fix: ensure filling/filled orders have matching fee

---

mobile/lib/features/trade/leverage_slider.dart

fix: ensure leverage slider buttons are also disabled

---

webapp/frontend/lib/trade/create_channel_confirmation_dialog.dart
webapp/frontend/lib/trade/create_order_confirmation_dialog.dart

It looks like we always posted an order with the opposite direction from the webapp.

fix: Post correct order direction

---

coordinator/migrations/2024-04-10-142400_add_liquidation_side_to_order_reason/down.sql
coordinator/migrations/2024-04-10-142400_add_liquidation_side_to_order_reason/up.sql
coordinator/src/campaign.rs
coordinator/src/db/orders_helper.rs
coordinator/src/node/liquidated_positions.rs
coordinator/src/notifications.rs
coordinator/src/orderbook/async_match.rs
coordinator/src/orderbook/db/custom_types.rs
coordinator/src/orderbook/db/orders.rs
coordinator/src/orderbook/trading.rs
coordinator/src/scheduler.rs
crates/commons/src/order.rs
mobile/native/src/db/custom_types.rs
mobile/native/src/db/models.rs
mobile/native/src/trade/order/api.rs
mobile/native/src/trade/order/mod.rs

Subject for discussion, but I think the adapted messages might be clearer and more fun. :)
|	|	|
|:-:|:-:|
| ![IMG_4989](https://github.com/get10101/10101/assets/382048/1ffde41c-dee6-491d-aab1-9febb1c5bd85) | ![IMG_4988](https://github.com/get10101/10101/assets/382048/191cee0f-b263-40b8-aeb1-427709929bcd) | 
| ![IMG_4987](https://github.com/get10101/10101/assets/382048/054601d7-6e44-4e65-b8d7-1bba98f94a54) | ![IMG_4986](https://github.com/get10101/10101/assets/382048/f1f86424-821c-4a22-a2d9-53ea1e342ca9) |
follow up to review remarks on https://github.com/get10101/10101/pull/2354

chore: Improve notification messages

---

mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_value_change_notifier.dart

It's an edge case where the user funds their wallet for the first time and did not receive a new price after the balance was updated. This fix ensures that the max quantity is always calculated when the order view is opened.
fixes #2398

fix: Ensure the max quantity is always calculated

---

mobile/lib/common/fiat_text.dart
mobile/lib/features/wallet/send/fee_text.dart
mobile/lib/features/wallet/wallet_history_item.dart

Fixes truncation of sats here: 
And overall wherever we are using Fiat values we remove the decimal place, e.g. here:

fix: don't truncate sats

---

coordinator/src/orderbook/db/orders.rs
coordinator/src/orderbook/routes.rs
coordinator/src/orderbook/websocket.rs
coordinator/src/routes.rs
crates/commons/src/message.rs
crates/commons/src/order.rs

Related to https://github.com/get10101/aristides/issues/39.

Add insert and delete APIs to orderbook WS

---

mobile/lib/features/trade/rollover_change_notifier.dart

The task dialog will show the close button if the state will remain in pending after it timed out.

chore: Do not show rollover task as failed after timeout

---

mobile/native/src/trade/position/mod.rs

Fixes https://github.com/get10101/10101/issues/2419.
I have verified that the value was already computed correctly by the coordinator.

Compute liquidation price correctly after direction change

---

coordinator/src/referrals.rs

when calculating the trader's bonus we check if he has an existing bonus and if he has, we return the best bonus at the end.
resolves https://github.com/get10101/10101/issues/2407

fix: return highest bonus

---

Cargo.lock
webapp/Cargo.toml
webapp/src/api.rs
webapp/src/auth.rs
webapp/src/main.rs

It is a bit of manual work and boiler plates but once set up it's quite nice. 
I've enabled redoc and swagger UI for now but I guess one of them is enough
- OpenApi/Swagger can be found under: http://localhost:3001/swagger-ui
- Redoc can be found under: http://localhost:3001/redoc
Note: our authentication seems to be non-standard, and hence, it does not fit to the Swagger authentication. Imho we should fix this to have a fully working swagger client. Supported authentication schemes can be found [here](https://docs.rs/utoipa/latest/utoipa/openapi/security/enum.SecurityScheme.html) 
Helps with https://github.com/get10101/10101/issues/2284

feat(webapp): introduce openapi/swagger specification

---

Cargo.lock

GitHub reported a vulnerability[^1].
[^1]: https://seanmonstar.com/blog/hyper-http2-continuation-flood/.

Update `h2` to version `0.4.4`

---

coordinator/migrations/2024-04-16-035239_add_reported_errors/down.sql
coordinator/migrations/2024-04-16-035239_add_reported_errors/up.sql
coordinator/src/db/mod.rs
coordinator/src/db/reported_errors.rs
coordinator/src/routes.rs
coordinator/src/schema.rs
crates/commons/src/lib.rs
crates/commons/src/reported_error.rs
crates/ln-dlc-node/src/networking/tcp.rs
justfile
mobile/native/src/lib.rs
mobile/native/src/report_error.rs
mobile/native/src/trade/order/handler.rs
rust-toolchain.toml

Fixes https://github.com/get10101/meta/issues/269.
It's just a start, but we should be able to build on this.
User runs into this error twice:
Database looks like this:
```
orderbook=# select * from reported_errors;
id |                           trader_pubkey                            |                            error                            
----+--------------------------------------------------------------------+-------------------------------------------------------------
1 | 0315bb4b3561fc219c2ace72018600049a556ad788db430318cdeedd76a4281634 | DLC channel not yet confirmed: has 0 confirmations, needs 1
2 | 0315bb4b3561fc219c2ace72018600049a556ad788db430318cdeedd76a4281634 | DLC channel not yet confirmed: has 0 confirmations, needs 1
(2 rows)
```

Forward `SubmitOrderErrors` from app to coordinator

---

webapp/src/main.rs

We do not support any of the accepted standards, hence, it's better to just remove

chore: remove authentication scheme from swagger

---

mobile/lib/features/wallet/referral_widget.dart
mobile/lib/features/wallet/wallet_screen.dart

This is not ideal, but since the referral code can be derived deterministically from the node id its safe to do and will ensure that the app will not fail to start.
This fixes an issue where the referral status is not yet set because the app hasn't processed the authenticated message from the coordinator yet. (happened because the referral widget will be shown immediately on the wallet screen after init, which can lead to that race condition)
fixes #2442

fix: Derive referral code from node id for referral widget

---

mobile/lib/common/domain/model.dart
mobile/lib/common/dummy_values.dart
mobile/lib/features/trade/application/trade_values_service.dart
mobile/lib/features/trade/channel_configuration.dart
mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/submit_order_change_notifier.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart
mobile/lib/features/trade/trade_value_change_notifier.dart
mobile/lib/features/wallet/receive/receive_usdp_dialog.dart
mobile/lib/features/wallet/send/confirm_payment_modal.dart
mobile/native/migrations/2024-04-16-144000_add_accumulated_order_matching_fee_to_position/down.sql
mobile/native/migrations/2024-04-16-144000_add_accumulated_order_matching_fee_to_position/up.sql
mobile/native/src/api.rs
mobile/native/src/channel_trade_constraints.rs
mobile/native/src/db/models.rs
mobile/native/src/emergency_kit.rs
mobile/native/src/max_quantity.rs
mobile/native/src/schema.rs
mobile/native/src/trade/position/mod.rs
mobile/test/trade_test.dart
webapp/frontend/lib/services/trade_constraints_service.dart
webapp/frontend/lib/services/trade_constraints_service.g.dart
webapp/frontend/lib/trade/create_channel_confirmation_dialog.dart
webapp/src/api.rs

Calculates the max quantity considering
- open quantity: Quantity of an existing position of the opposite direction. (needed for fee calculation)
- accumulated order matching fee: As the coordinator is not using already collected order matching fees as collateral for new trades, this has to be deducted from the max coordinator margin.
fixes #2391

fix: Calculate max quantity for resizing

---

mobile/lib/common/domain/model.dart
mobile/lib/features/trade/domain/trade_values.dart
mobile/lib/features/trade/trade_bottom_sheet_confirmation.dart
mobile/lib/features/trade/trade_bottom_sheet_tab.dart

fixes #2403 
Additionally I reworked the confirmation screen a bit. Nothing fundamental, but tweaked a little bit what information is shown depending on the corresponding trade action.
https://github.com/get10101/10101/assets/382048/a06b0121-7122-4263-b410-14578368ba0b

fix: Calculate liquidation price from opposite direction if the position is reduced

---

Cargo.toml

Fixes #2377.
The fix is in `rust-dlc`, hence the dependency update. See https://github.com/p2pderivatives/rust-dlc/commit/974c56b.

Do not hog `chain_monitor` lock during `periodic_check`

---

mobile/lib/features/trade/trade_bottom_sheet_tab.dart

If we don't have a position we default the quantity to the max quantity. If we have an open position we default the quantity to zero because the contracts will be defaulted to the open quantity.
The behaviour should be that in case of an open position the default contracts on the opposite direction is to close the position.
fixes #2465

fix: Set quantity to zero when initiation order view with open position

---

.github/workflows/android-fastlane.yml

Whenever we build APKs for main, we create a new release with the _date_ format and attach the APKs
Untested... YOLO.

feat: create release and add APK to CI release

---

.github/workflows/android-fastlane.yml

our CI started failing because of
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
which might be because of an outdated java version
fix: #2479

bump: outdated java version

---

.github/workflows/build-release-binaries.yml

We are on Rust 1.77.2 according to the `rust-toolchain.toml` file.

Remove unused environment variable in CI

---

coordinator/src/db/trade_params.rs

fix: Store matching fee and trader pnl into trade params

---

coordinator/migrations/2024-05-09-051816_add_timestamp_and_version_to_error_logs/down.sql
coordinator/migrations/2024-05-09-051816_add_timestamp_and_version_to_error_logs/up.sql
coordinator/src/db/reported_errors.rs
coordinator/src/schema.rs
crates/xxi-node/src/commons/reported_error.rs
mobile/native/src/report_error.rs

I opted for not introducing a breaking change. If a user fails and posts an error prior 2.3.1 (which will be the next release hopefully), we will see `<2.3.1` in the db.
resolves #2435

feat: add version and timestamp to error logs

---

mobile/.fvmrc
webapp/frontend/.fvmrc

To avoid random breaking changes showing up in CI.
AFAIK these were the versions we were using before `stable` was updated.

Fix Flutter versions

---

crates/xxi-node/src/on_chain_wallet.rs
mobile/lib/features/wallet/application/wallet_service.dart

there were two bugs:
1. we need to check if `amount` is `null` and set the sending amount to 0. This is because if we click `Max` we set `amount` to null
2. in the backend we checked if the sending amount is below dust. Sending 0 is an edge case which is clearly below dust but will be checked later to drain the wallet.
fixes #2542

fix: drain on-chain wallet

---

mobile/native/src/trade/order/handler.rs

Otherwise it could happen that we may process the offer setting the order to `Filling` before we set the order to `Open` (which would overwrite the execution price).
fixes #2547

fix: Set order to open before the market order is posted

---

mobile/native/src/trade/order/handler.rs

Obviously the second set order state to `Open` should have been removed. 🤦

fix: Remove multiple order update to open

---

coordinator/src/db/positions.rs
coordinator/src/node.rs
mobile/native/src/dlc/dlc_handler.rs
mobile/native/src/trade/order/handler.rs

In case of a rollover we do not have an order id or and order in filling. As a result this logic failed when trying to reject a rollover offer.
The solution is still hacky as with the correct context information we shouldn't even try to set the order to failed, but that context is missing when we are reconnecting in the `on_connect` function and finding a dlc channel in state `RenewOffered`.
fixes #2554

fix: Ignore missing order id when rejecting a rollover offer

---

crates/xxi-node/src/on_chain_wallet.rs

Before we were printing all known utxos, even not from our own wallet.

fix: return only wallet unspent utxos

---

crates/xxi-node/src/node/wallet.rs

on each blockchain sync we clear the lcoked utxos. This is fine, because we are syncing with the blockchain and are learning about all acutally spent utxos.

fix: Unreserve utxos on wallet sync

---

mobile/lib/features/trade/application/order_service.dart
mobile/lib/features/trade/channel_creation_flow/channel_funding_screen.dart
mobile/native/src/hodl_invoice.rs
mobile/native/src/unfunded_channel_opening_order.rs

If we can't receive a hodl invoice the app gracefully handles that scenario and shows an according message instead of the invoice.
https://github.com/get10101/10101/assets/382048/0998f5d2-a3a1-4782-9716-bc84544edb8c

feat: Handle error when requesting a hodl invoice

---

mobile/lib/features/trade/channel_creation_flow/channel_configuration_screen.dart

The lnd node is running separately on the test vm, which can lead to a delay when requesting a new invoice.
This patch disables the button and indicates to the user that the request is being processed.
https://github.com/get10101/10101/assets/382048/f62af30d-f12e-4b93-a9cf-1d43c03547b1

fix: Prevent multiple next button clicks

---

mobile/lib/common/countdown.dart
mobile/lib/features/trade/channel_creation_flow/channel_funding_screen.dart

feat: Show invoice expiry

---

crates/lnd-bridge/examples/mock.rs
crates/tests-e2e/src/test_subscriber.rs
mobile/native/src/dlc/mod.rs
mobile/native/src/event/api.rs
mobile/native/src/event/mod.rs
mobile/native/src/event/subscriber.rs
mobile/native/src/orderbook.rs
mobile/native/src/state.rs
mobile/native/src/unfunded_channel_opening_order.rs
mobile/native/src/watcher.rs

This PR fixes two issues.
1. Any paid invoice that has been created by the coordinator will produce a `LnPaymentReceived` event. Before that change we would have simply assumed that this was the payment we've been waiting for. But it could have happened that the users went back and forth multiple times and thus created multiple invoices. So if an old invoice would have been paid, we would have triggered the order creation which would have failed, because the shared pre-image would have been incorrect. We do now verify that the received r_hash is equal to the watched r_hash.
2. On every creation of a hodl invoice we subscribed the `InvoiceWatcher` for `LnPaymentReceived` events. These subscribers lived forever and never got cancelled, producing various error messages since the receiver has …

fix: Watch for specific r_hash

---

coordinator/src/node/rollover.rs

This was a safe-guard added when the app triggered the rollover through the publicly exposed rollover api. Now that we have changed that it is convenient to rollover also expired contracts for support cases.
fixes #2555

chore: Allow rollover even if the contract is expired

---

coordinator/src/node/channel.rs
coordinator/src/routes/admin.rs

Force closing a channel should not get recorded as regular collab close dlc protocol.
This lead to an issue where the dlc channel did not get updated properly because the contract was missing.

fix: Do not create dlc protocol entry for force closed channels

---

coordinator/src/node/liquidated_positions.rs
coordinator/src/trade/mod.rs
crates/xxi-node/src/node/dlc_channel.rs
mobile/native/src/dlc/mod.rs
mobile/native/src/trade/order/handler.rs
webapp/src/api.rs

This is covering an edge case where the user opens a dlc channel and wants to close the position within the sync window of the coordinator.
It allows to instantly close the position without having to manually sync the wallet after the dlc channel has been created.
---
It's probably not the most important feature for prod, but it makes testing a bit easier... Happy to close this PR if the reviewer thinks that this is an unnecessary overhead.

feat: Sync wallet when contract is not confirmed yet.

---

mobile/lib/common/app_bar_wrapper.dart
mobile/lib/features/wallet/receive_screen.dart
mobile/lib/features/welcome/seed_import_screen.dart

fix: don't change app bar colour when scrolling

---

Cargo.lock
coordinator/migrations/2024-05-31-144618_add-canceled-invoice-state/down.sql
coordinator/migrations/2024-05-31-144618_add-canceled-invoice-state/up.sql
coordinator/src/bin/coordinator.rs
coordinator/src/db/custom_types.rs
coordinator/src/db/hodl_invoice.rs
coordinator/src/node/invoice.rs
coordinator/src/trade/mod.rs
crates/lnd-bridge/examples/cancel_invoice_api.rs
crates/lnd-bridge/src/lib.rs
mobile/native/Cargo.toml
mobile/native/src/watcher.rs

feat: Cancel hodl invoice if dlc proposal fails

---

mobile/lib/common/init_service.dart
mobile/lib/features/wallet/application/faucet_service.dart
mobile/lib/features/wallet/receive_screen.dart

feat: use mutinynet faucet

---

coordinator/src/db/hodl_invoice.rs
coordinator/src/node/invoice.rs
coordinator/src/trade/mod.rs

It's better to update our state only if the same state has been applied to lnd.

chore: Set hodl invoice to `Settled` on lnd event

---

.github/workflows/testflight-for-review.yml

Looks like the [daily task ](https://github.com/get10101/10101/actions/workflows/testflight-for-review.yml) never worked because we did not build the ios archive 🙈 . 
Should be fixed now.

fix: build ios archive was missing

---

mobile/lib/common/scrollable_safe_area.dart
mobile/lib/features/welcome/welcome_screen.dart

fix: Stop welcome screen overflowing

---

mobile/lib/common/amount_text_field.dart

Fixes #2592. For some reason we had different padding here. Here's how it looks now:

fix: Make margin box size match quantity

---

mobile/lib/common/routes.dart

Fixes #2525 
I can say for certain that going into settings still triggers a refresh - I'm not sure if we care about this, though. Otherwise, it seems to work and it does not refresh when swapping from wallet to trading tab. If this general approach is acceptable (which maybe has wider-reaching impacts?), then I can re-add the animation to swap from wallet to trade tabs and we can merge this.

fix: Don't refresh TradingView when switching from wallet to trading tab

---

coordinator/src/funding_fee.rs

I was trying to fail at compile time based on a runtime value (the settings). This is dumb.
We now fail at runtime if we try to use a fixed index price in release mode. Production always runs on release, so this exists to prevent using a fixed index price in production.
Obviously, release does not always equal production, but using the real index price from BitMEX is fine in most scenarios (except for the e2e tests and some instances of local testing).
---
This should fix problems like [this one](https://github.com/get10101/10101/actions/runs/9367310775/job/25786706679), which were preventing us from building the coordinator in release mode 🤦

Remove insane `compile_error!`

---

mobile/lib/features/trade/trade_screen.dart

Thanks to @holzeis for the inspiration!

Display next funding rate below candlestick chart

---

coordinator/migrations/2024-06-06-045129_add_unique_end_date_constraint/down.sql
coordinator/migrations/2024-06-06-045129_add_unique_end_date_constraint/up.sql
coordinator/src/funding_fee/db/funding_rates.rs

We only need one funding rate entry per `end_date`.
Without this change we were getting a new duplicate entry per maker restart.

Add `unique_end_date` constraint to `funding_rates` table

---

mobile/lib/features/trade/channel_creation_flow/channel_funding_screen.dart
mobile/lib/features/wallet/application/faucet_service.dart
mobile/lib/features/wallet/receive_screen.dart

resolves https://github.com/get10101/10101/issues/2600.
Imho it should work but it's blocked by https://github.com/get10101/cloud-conf/issues/264
https://github.com/get10101/10101/assets/224613/fdfcd1a3-85af-4e8e-a5cc-28a42f5c2dd9

feat: use mutinynet faucet for channel opening fundings

---

coordinator/example-settings/prod-coordinator-settings.toml
coordinator/example-settings/test-coordinator-settings.toml
coordinator/src/orderbook/websocket.rs
coordinator/src/settings.rs
crates/xxi-node/src/commons/message.rs
mobile/lib/common/application/tentenone_config_change_notifier.dart
mobile/lib/common/domain/tentenone_config.dart
mobile/lib/features/trade/leverage_slider.dart
mobile/native/src/api.rs
webapp/frontend/lib/services/trade_constraints_service.dart
webapp/frontend/lib/services/trade_constraints_service.g.dart
webapp/frontend/lib/trade/leverage_slider.dart
webapp/src/api.rs

A simple feature allowing us to configure higher leverages through the coordinator's settings.

feat: higher leverages

---

mobile/lib/common/settings/seed_words.dart

fix: Show the number of seed words correctly (don't split across lines)

---

mobile/lib/common/task_status_dialog.dart

- Don't show thin white pixel artifact around status dialog
- Clamp size of dialogue so that it always shows the entire header image
Before:
After:

fix: Better task status dialogue

---

coordinator/src/node/rollover.rs

This has been accidentally reintroduce with 246db2420baa22c0739c0aee3bf6d0edb2d343a5.

fix: Rollover expired position

---

webapp/frontend/lib/common/model.dart

We should backport this to 2.4.5 and release a new version

fix: fee rate was not parsed correctly

---

Cargo.lock
coordinator/Cargo.toml
mobile/native/Cargo.toml
mobile/pubspec.yaml
webapp/Cargo.toml

Hi @holzeis!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/get10101/10101/actions/runs/10214008436.
I've bumped the versions in the manifest files in this commit: 7b095129ff029827a2334abb0796ac4659498872.

Release version 2.4.8

---

mobile/lib/features/trade/trade_screen.dart

It is very unlikely that the absolute funding rate will be below 0.0001, so 4 decimal places should be informational enough.

Show 4 decimal places on next funding rate

---

crates/bitmex-client/src/client.rs
crates/bitmex-client/src/models.rs

This allows us to fetch funding rates etc from bitmex.

feat(bitmex-client): introduce getter for instrument from bitmex

---

.github/workflows/build-release-binaries.yml
Cargo.lock
webapp/README.md

Since we are winding down the 10101 coordinator, apps will only work if they use an alternative API, such as Blockstream's public API.

Use blockstream's public API for clients

---

Cargo.lock
Cargo.toml

There is actually no protocol pressure to claim these outputs quickly, so it seems foolish to pay a possibly very high price for these claim transactions.
See https://github.com/get10101/rust-dlc/commit/906cb4d422dbd90bf2fe35991f2a709801c250e7.

Use `ConfirmationTarget::Background` to claim settle TX outputs
